var PORTAL_TRANSLATIONS = {
  en: {
    _title: 'Hızlı Çekiliş – Quick Raffle & Random Pick App',
    _description: 'All-in-one raffle and random pick app: name picker, number draw, wheel, lottery, team picker, dice, coin flip, card draw, list shuffler, bingo and more. Fast, fair, and fun.',
    nav_back: '← Sogepps',
    nav_features: 'Features',
    nav_privacy: 'Privacy Policy',
    hero_badge: '🎰 All-in-One Raffle App',
    hero_title: 'Raffles, Draws &<br /><span class="grad">Random Picks</span>',
    hero_desc: 'Hızlı Çekiliş is a fast, fair, and fun all-in-one raffle and random pick app. Name picker, number draw, wheel, lottery, team picker, dice, coin flip, card draw, list shuffler, bingo, yes/no, Secret Santa, bracket, Magic 8 Ball, password generator and more.',
    btn_google_play: 'Get it on Google Play',
    btn_see_features: 'See Features ↓',
    cta_btn: 'Download on Google Play',
    feat_label: '◆ Features',
    feat_title: 'Powerful Tools in One App',
    feat_desc: 'Ideal for giveaways, social media contests, class activities, meetings, tournaments, parties and games.',
    feat1_title: 'Name Picker',
    feat1_desc: 'Pick a random winner from your list. Perfect for Instagram giveaways, school activities, and group games.',
    feat2_title: 'Wheel & Number Draw',
    feat2_desc: 'Spin the wheel or generate random numbers. Fair and unbiased random algorithms for every result.',
    feat3_title: 'Team Picker',
    feat3_desc: 'Split participants into balanced teams in seconds. Great for sports, games, and group activities.',
    feat4_title: 'Dice, Coin, Cards & More',
    feat4_desc: 'Dice roll, coin flip, card draw, list shuffler, bingo number picker, yes/no, Secret Santa, tournament bracket, Magic 8 Ball, password generator, random color.',
    feat5_title: 'Privacy First',
    feat5_desc: 'No personal data required. Names, numbers and lists are used only on your device and are not sent to our servers.',
    feat6_title: 'Fast & Easy',
    feat6_desc: 'Modern, clean design. Everyone can use it easily. Get instant results for decisions and fun.',
    how_label: '◆ How It Works',
    how_title: 'Simple Steps',
    step1_title: 'Choose Tool',
    step1_desc: 'Pick name picker, wheel, number draw, team picker, dice, or any other tool you need.',
    step2_title: 'Add Your Data',
    step2_desc: 'Enter names, numbers, or options. Everything stays on your device.',
    step3_title: 'Get Result',
    step3_desc: 'Fair random result in seconds. Perfect for giveaways, decisions, and games.',
    cta_title: 'Ready to Use?',
    cta_desc: 'Download Hızlı Çekiliş and make your raffles, decisions, and games more fun and practical. All results are fair and unbiased.',
    footer_brand: 'Hızlı Çekiliş',
    footer_by: 'by',
    footer_app: 'App',
    footer_google_play: 'Google Play',
    footer_features: 'Features',
    footer_legal: 'Legal',
    footer_privacy: 'Privacy Policy',
    footer_contact: 'Contact',
    footer_rights: '© 2026',
  },
  tr: {
    _title: 'Hızlı Çekiliş – Çekiliş ve Rastgele Seçim Uygulaması',
    _description: 'Hızlı Çekiliş: çekiliş, kura, hediye, sosyal medya yarışmaları ve karar vermek için hepsi bir arada uygulama. İsim seçici, şans çarkı, sayı çekilişi, takım oluşturucu ve daha fazlası.',
    nav_back: '← Sogepps',
    nav_features: 'Özellikler',
    nav_privacy: 'Gizlilik Politikası',
    hero_badge: '🎰 Hepsi Bir Arada Çekiliş Uygulaması',
    hero_title: 'Çekilişler, Kuralar &amp;<br /><span class="grad">Rastgele Seçimler</span>',
    hero_desc: 'Hızlı Çekiliş, hızlı, adil ve eğlenceli sonuçlar sunan hepsi bir arada bir çekiliş ve rastgele seçim uygulamasıdır. İsim seçici, sayı çekilişi, şans çarkı, loto, takım oluşturucu, zar, yazı tura, kart çekme, liste karıştırıcı, bingo ve daha fazlası.',
    btn_google_play: 'Google Play\'den İndir',
    btn_see_features: 'Özellikleri Gör ↓',
    cta_btn: 'Google Play\'den İndir',
    feat_label: '◆ Özellikler',
    feat_title: 'Tek Uygulamada Güçlü Araçlar',
    feat_desc: 'Çekilişler, kuralar, hediyeler, sosyal medya yarışmaları, sınıf etkinlikleri, toplantılar, turnuvalar, partiler ve oyunlar için ideal.',
    feat1_title: 'İsim Seçici',
    feat1_desc: 'Listeden rastgele kazanan seçin. Instagram çekilişleri, okul aktiviteleri ve grup oyunları için mükemmel.',
    feat2_title: 'Şans Çarkı ve Sayı Çekilişi',
    feat2_desc: 'Çarkı çevirin veya rastgele sayılar üretin. Tüm sonuçlar adil ve tarafsız rastgele algoritmalarla oluşturulur.',
    feat3_title: 'Takım Oluşturucu',
    feat3_desc: 'Katılımcıları saniyeler içinde dengeli takımlara ayırın. Spor, oyunlar ve grup aktiviteleri için harika.',
    feat4_title: 'Zar, Yazı Tura, Kartlar ve Daha Fazlası',
    feat4_desc: 'Zar atma, yazı tura, kart çekme, liste karıştırıcı, bingo numara çekici, evet/hayır, Secret Santa, turnuva fikstürü, Sihirli 8 Top, şifre oluşturucu, rastgele renk.',
    feat5_title: 'Gizlilik Öncelikli',
    feat5_desc: 'Kişisel veri gerekmez. İsimler, sayılar ve listeler yalnızca cihazınızda kullanılır ve sunucularımıza gönderilmez.',
    feat6_title: 'Hızlı ve Kolay',
    feat6_desc: 'Modern ve sade tasarım. Herkes kolayca kullanabilir. Kararlar ve eğlence için anında sonuç alın.',
    how_label: '◆ Nasıl Çalışır',
    how_title: 'Basit Adımlar',
    step1_title: 'Araç Seçin',
    step1_desc: 'İsim seçici, çark, sayı çekilişi, takım oluşturucu, zar veya ihtiyacınız olan başka bir aracı seçin.',
    step2_title: 'Verilerinizi Ekleyin',
    step2_desc: 'İsimleri, sayıları veya seçenekleri girin. Her şey cihazınızda kalır.',
    step3_title: 'Sonucu Alın',
    step3_desc: 'Saniyeler içinde adil rastgele sonuç. Çekilişler, kararlar ve oyunlar için mükemmel.',
    cta_title: 'Kullanmaya Hazır mısınız?',
    cta_desc: 'Hızlı Çekiliş\'i indirin ve çekilişlerinizi, kararlarınızı ve oyunlarınızı daha eğlenceli ve pratik hale getirin. Tüm sonuçlar adil ve tarafsızdır.',
    footer_brand: 'Hızlı Çekiliş',
    footer_by: 'yapımcı',
    footer_app: 'Uygulama',
    footer_google_play: 'Google Play',
    footer_features: 'Özellikler',
    footer_legal: 'Yasal',
    footer_privacy: 'Gizlilik Politikası',
    footer_contact: 'İletişim',
    footer_rights: '© 2026',
  },
};
