var PRIVACY_TRANSLATIONS = {
  en: {
    _title: 'Privacy Policy – Hızlı Çekiliş (Quick Raffle)',
    _description: 'Privacy Policy for Hızlı Çekiliş mobile application by Sogepps.',
    nav_back: '← Quick Raffle',
    nav_privacy: 'Privacy Policy',
    page_title: '🔐 Privacy Policy – Hızlı Çekiliş',
    page_date: 'Last updated: 2 March 2026',
    intro: 'We at <strong>Hızlı Çekiliş</strong> ("App") value your privacy. This Privacy Policy explains what information is collected when you use the app, how it is used, and how it is protected.<br /><br />By using the App, you accept this Privacy Policy.',
    s1_title: '1. Information We Collect',
    s1_p1: 'Hızlı Çekiliş does not require the collection of personal data. The app runs raffles and random selection without asking for identity information from the user.',
    s1_p2: 'Data entered within the app:',
    s1_li1: 'Name lists',
    s1_li2: 'Numbers',
    s1_li3: 'Lists',
    s1_li4: 'Team information',
    s1_p3: 'is used only temporarily on the user\'s device and is not sent to our servers.',
    s2_title: '2. Automatically Collected Information',
    s2_p1: 'To improve the app\'s performance and stability, the following anonymous information may be collected automatically:',
    s2_li1: 'App usage statistics',
    s2_li2: 'Error and crash reports',
    s2_li3: 'Device type and operating system information',
    s2_p2: 'This data does not contain personally identifiable information and is used only for app development purposes.',
    s3_title: '3. Advertising',
    s3_p1: 'Hızlı Çekiliş may use third-party advertising services (e.g. Google AdMob). These services may collect anonymous data to show more relevant ads to users.',
    s3_p2: 'Ad providers are subject to their own privacy policies. Users can disable personalized ads in their device settings.',
    s4_title: '4. Children\'s Privacy',
    s4_p1: 'Hızlı Çekiliş does not knowingly collect personal data from children under 13. If you are a parent or guardian and notice that your child has shared personal information, you may contact us.',
    s5_title: '5. Data Security',
    s5_p1: 'The security of user data is important to us. The app keeps user data on the device as much as possible and takes necessary measures against unauthorized access.',
    s5_p2: 'However, no data transmission over the internet or digital environment can be guaranteed to be 100% secure.',
    s6_title: '6. Third-Party Links',
    s6_p1: 'The app may contain links to third-party websites or services. Hızlı Çekiliş is not responsible for the privacy practices of these sites. We recommend reviewing the privacy policies of third parties.',
    s7_title: '7. Changes to This Privacy Policy',
    s7_p1: 'This Privacy Policy may be updated from time to time. Any changes will be published on this page and will be effective from the date of publication.',
    s8_title: '8. Contact',
    s8_p1: 'For questions about this Privacy Policy, you can contact us at:',
    s8_email: '📧 Email:',
    s8_web: '🌐 Website:',
    footer_brand: 'Hızlı Çekiliş',
    footer_by: 'by',
  },
  tr: {
    _title: 'Gizlilik Politikası – Hızlı Çekiliş',
    _description: 'Hızlı Çekiliş mobil uygulaması Gizlilik Politikası – Sogepps.',
    nav_back: '← Hızlı Çekiliş',
    nav_privacy: 'Gizlilik Politikası',
    page_title: '🔐 Gizlilik Politikası – Hızlı Çekiliş',
    page_date: 'Son güncelleme: 2 Mart 2026',
    intro: '<strong>Hızlı Çekiliş</strong> ("Uygulama") olarak kullanıcılarımızın gizliliğine önem veriyoruz. Bu Gizlilik Politikası, uygulamayı kullandığınızda hangi bilgilerin toplandığını, nasıl kullanıldığını ve nasıl korunduğunu açıklar.<br /><br />Uygulamayı kullanarak bu Gizlilik Politikası\'nı kabul etmiş olursunuz.',
    s1_title: '1. Toplanan Bilgiler',
    s1_p1: 'Hızlı Çekiliş, kişisel veri toplamayı zorunlu kılmaz. Uygulama, çekiliş ve rastgele seçim işlemlerini kullanıcıdan kimlik bilgisi talep etmeden çalışır.',
    s1_p2: 'Uygulama kapsamında girilen:',
    s1_li1: 'İsim listeleri',
    s1_li2: 'Sayılar',
    s1_li3: 'Listeler',
    s1_li4: 'Takım bilgileri',
    s1_p3: 'yalnızca kullanıcının cihazında, geçici olarak kullanılır ve sunucularımıza gönderilmez.',
    s2_title: '2. Otomatik Olarak Toplanan Bilgiler',
    s2_p1: 'Uygulamanın performansını ve kararlılığını artırmak amacıyla aşağıdaki anonim bilgiler otomatik olarak toplanabilir:',
    s2_li1: 'Uygulama kullanım istatistikleri',
    s2_li2: 'Hata ve çökme raporları',
    s2_li3: 'Cihaz türü ve işletim sistemi bilgileri',
    s2_p2: 'Bu veriler kişisel kimlik bilgisi içermez ve yalnızca uygulamanın geliştirilmesi amacıyla kullanılır.',
    s3_title: '3. Reklamlar',
    s3_p1: 'Hızlı Çekiliş, üçüncü taraf reklam hizmetleri (örneğin Google AdMob) kullanabilir. Bu hizmetler, kullanıcılara daha uygun reklamlar sunabilmek için anonim veriler toplayabilir.',
    s3_p2: 'Reklam sağlayıcıları kendi gizlilik politikalarına tabidir. Kullanıcılar, cihaz ayarları üzerinden kişiselleştirilmiş reklamları devre dışı bırakabilir.',
    s4_title: '4. Çocukların Gizliliği',
    s4_p1: 'Hızlı Çekiliş, 13 yaş altındaki çocuklardan bilerek kişisel veri toplamaz. Eğer bir ebeveyn veya vasi olarak çocuğunuzun kişisel bilgi paylaştığını fark ederseniz, bizimle iletişime geçebilirsiniz.',
    s5_title: '5. Veri Güvenliği',
    s5_p1: 'Kullanıcı verilerinin güvenliği bizim için önemlidir. Uygulama, kullanıcı verilerini mümkün olduğunca cihaz içinde tutar ve yetkisiz erişime karşı gerekli önlemleri alır.',
    s5_p2: 'Ancak internet veya dijital ortam üzerinden yapılan hiçbir veri aktarımının %100 güvenli olduğu garanti edilemez.',
    s6_title: '6. Üçüncü Taraf Bağlantılar',
    s6_p1: 'Uygulama, üçüncü taraf web sitelerine veya hizmetlere bağlantılar içerebilir. Bu sitelerin gizlilik uygulamalarından Hızlı Çekiliş sorumlu değildir. Üçüncü tarafların gizlilik politikalarını incelemenizi öneririz.',
    s7_title: '7. Gizlilik Politikasındaki Değişiklikler',
    s7_p1: 'Bu Gizlilik Politikası zaman zaman güncellenebilir. Yapılan değişiklikler bu sayfa üzerinde yayınlanır ve yayınlandığı tarihten itibaren geçerli olur.',
    s8_title: '8. İletişim',
    s8_p1: 'Bu Gizlilik Politikası ile ilgili sorularınız için bizimle iletişime geçebilirsiniz:',
    s8_email: '📧 E-posta:',
    s8_web: '🌐 Web sitesi:',
    footer_brand: 'Hızlı Çekiliş',
    footer_by: 'yapımcı',
  },
};
