var PRIVACY_TRANSLATIONS = {
  en: {
    _title: 'Privacy Policy – HomeParty',
    _description: 'Privacy Policy for the HomeParty mobile application by Sogepps.',
    nav_back: '← HomeParty',
    nav_privacy: 'Privacy Policy',
    page_title: '🔐 Privacy Policy – HomeParty',
    page_date: 'Last updated: 23 June 2026',
    intro: 'We at <strong>HomeParty</strong> ("App") value your privacy. This Privacy Policy explains what information is collected when you use the app, how it is used, and how it is protected.<br /><br />By using the App, you accept this Privacy Policy.',
    s1_title: '1. Information We Collect',
    s1_p1: 'HomeParty does not require an account, login, or mandatory personal data such as your real name, email address, or phone number.',
    s1_p2: 'Data created during gameplay may include:',
    s1_li1: 'Default or custom player labels (e.g. Player1, Player2)',
    s1_li2: 'In-game scores, votes, and team assignments for the current session',
    s1_li3: 'Selected game mode, player count, and game settings',
    s1_li4: 'Short text entered in some modes (e.g. True or False statements)',
    s1_li5: 'Drawings created during a session in modes such as Draw Chain',
    s1_li6: 'Language and sound preferences',
    s1_p3: 'This information is stored only on your device to run the game. It is not uploaded to our servers. Word, question, and challenge prompts shown in the game are pre-written content for entertainment; the App does not access your phone history, contacts, photos, microphone, or other private device data.',
    s2_title: '2. Automatically Collected Information',
    s2_p1: 'To improve performance and stability, the following anonymous information may be collected automatically:',
    s2_li1: 'App usage and crash analytics',
    s2_li2: 'Device type and operating system version',
    s2_li3: 'General diagnostic data from the app platform',
    s2_p2: 'This data does not include player names, scores, votes, or custom text and drawings from your game sessions.',
    s3_title: '3. Advertising',
    s3_p1: 'HomeParty may use third-party advertising services (such as Google AdMob) to show ads. These providers may collect advertising identifiers and anonymous usage data to deliver and measure ads.',
    s3_p2: 'Ad providers are governed by their own privacy policies. You can limit personalized ads in your device settings (Google Ads settings on Android, or privacy settings on iOS).',
    s4_title: '4. Children\'s Privacy',
    s4_p1: 'HomeParty is a group party game that may be played by younger players as well. We do not knowingly collect personal data from children under 13. Some game modes (Hot Seat, Wheel Challenge, Most Likely, etc.) include social questions or challenges meant to be played verbally among players in the same room. Parents and guardians should supervise younger players.',
    s5_title: '5. Data Security',
    s5_p1: 'We design HomeParty to keep gameplay data on your device. We take reasonable measures to protect any data processed by the App.',
    s5_p2: 'No method of electronic storage or transmission is 100% secure. Uninstalling the app removes locally stored game data from your device.',
    s6_title: '6. Third-Party Services',
    s6_p1: 'The App may rely on third-party services (e.g. Google Mobile Ads, Unity analytics) with their own privacy practices. HomeParty is not responsible for how those services handle data. We recommend reviewing their policies.',
    s7_title: '7. Changes to This Privacy Policy',
    s7_p1: 'We may update this Privacy Policy from time to time. Changes will be posted on this page and take effect when published.',
    s8_title: '8. Contact',
    s8_p1: 'For questions about this Privacy Policy, contact us:',
    s8_email: '📧 Email:',
    s8_web: '🌐 Website:',
    footer_brand: 'HomeParty',
    footer_by: 'by'
  },
  tr: {
    _title: 'Gizlilik Politikası – HomeParty',
    _description: 'HomeParty mobil uygulaması Gizlilik Politikası – Sogepps.',
    nav_back: '← HomeParty',
    nav_privacy: 'Gizlilik Politikası',
    page_title: '🔐 Gizlilik Politikası – HomeParty',
    page_date: 'Son güncelleme: 23 Haziran 2026',
    intro: '<strong>HomeParty</strong> ("Uygulama") olarak kullanıcılarımızın gizliliğine önem veriyoruz. Bu Gizlilik Politikası, uygulamayı kullandığınızda hangi bilgilerin toplandığını, nasıl kullanıldığını ve nasıl korunduğunu açıklar.<br /><br />Uygulamayı kullanarak bu Gizlilik Politikası\'nı kabul etmiş olursunuz.',
    s1_title: '1. Toplanan Bilgiler',
    s1_p1: 'HomeParty hesap açmayı, giriş yapmayı veya ad, e-posta, telefon gibi zorunlu kişisel veri paylaşımını gerektirmez.',
    s1_p2: 'Oyun sırasında oluşan veriler şunları içerebilir:',
    s1_li1: 'Varsayılan veya özelleştirilmiş oyuncu isimleri (ör. Oyuncu1, Oyuncu2)',
    s1_li2: 'Mevcut oturumdaki puanlar, oylamalar ve takım atamaları',
    s1_li3: 'Seçilen oyun modu, oyuncu sayısı ve oyun ayarları',
    s1_li4: 'Bazı modlarda girilen kısa metinler (ör. Doğru mu Yalan mı cümleleri)',
    s1_li5: 'Çizim Zinciri gibi modlarda oturum içinde oluşturulan çizimler',
    s1_li6: 'Dil ve ses tercihleri',
    s1_p3: 'Bu bilgiler yalnızca oyunu çalıştırmak için cihazınızda tutulur. Sunucularımıza yüklenmez. Oyunda gösterilen kelime, soru ve görev metinleri eğlence amaçlı hazır içeriklerdir; Uygulama telefon geçmişinize, rehberinize, fotoğraflarınıza, mikrofonunuza veya diğer özel cihaz verilerinize erişmez.',
    s2_title: '2. Otomatik Olarak Toplanan Bilgiler',
    s2_p1: 'Performans ve kararlılığı artırmak için aşağıdaki anonim bilgiler otomatik toplanabilir:',
    s2_li1: 'Uygulama kullanım ve çökme analitiği',
    s2_li2: 'Cihaz türü ve işletim sistemi sürümü',
    s2_li3: 'Uygulama platformundan gelen genel tanılama verileri',
    s2_p2: 'Bu veriler oyuncu isimlerini, puanları, oylamaları veya oyun oturumunuzdaki özel metin ve çizimleri içermez.',
    s3_title: '3. Reklamlar',
    s3_p1: 'HomeParty, reklam göstermek için üçüncü taraf reklam hizmetleri (örneğin Google AdMob) kullanabilir. Bu sağlayıcılar reklam tanımlayıcıları ve anonim kullanım verileri toplayabilir.',
    s3_p2: 'Reklam sağlayıcıları kendi gizlilik politikalarına tabidir. Kişiselleştirilmiş reklamları cihaz ayarlarından (Android\'de Google Reklamlar, iOS\'ta gizlilik ayarları) sınırlayabilirsiniz.',
    s4_title: '4. Çocukların Gizliliği',
    s4_p1: 'HomeParty, genç oyuncuların da yer alabileceği bir grup parti oyunudur. 13 yaş altındaki çocuklardan bilerek kişisel veri toplamayız. Bazı oyun modları (Sıcak Koltuk, Şans Çarkı, En Çok Kim vb.) sosyal sorular veya görevler içerebilir; bunlar aynı odadaki oyuncular arasında sözlü oynanmak üzere tasarlanmıştır. Ebeveynlerin küçük oyunculara eşlik etmesini öneririz.',
    s5_title: '5. Veri Güvenliği',
    s5_p1: 'HomeParty, oyun verilerinizi cihazınızda tutacak şekilde tasarlanmıştır. Uygulama tarafından işlenen verileri korumak için makul önlemler alırız.',
    s5_p2: 'Elektronik depolama veya aktarım yöntemlerinin hiçbiri %100 güvenli değildir. Uygulamayı kaldırmak, cihazdaki yerel oyun verilerini siler.',
    s6_title: '6. Üçüncü Taraf Hizmetler',
    s6_p1: 'Uygulama, kendi gizlilik uygulamaları olan üçüncü taraf hizmetlere (ör. Google Mobile Ads, Unity analitiği) dayanabilir. HomeParty bu hizmetlerin veri işleme süreçlerinden sorumlu değildir. İlgili politikaları incelemenizi öneririz.',
    s7_title: '7. Gizlilik Politikasındaki Değişiklikler',
    s7_p1: 'Bu Gizlilik Politikası zaman zaman güncellenebilir. Değişiklikler bu sayfada yayınlanır ve yayınlandığı tarihten itibaren geçerli olur.',
    s8_title: '8. İletişim',
    s8_p1: 'Bu Gizlilik Politikası ile ilgili sorularınız için:',
    s8_email: '📧 E-posta:',
    s8_web: '🌐 Web sitesi:',
    footer_brand: 'HomeParty',
    footer_by: 'yapımcı'
  }
};
