var SPINIFY_TRANSLATIONS = (function () {
  var en = {
    _title: 'Spinify - Custom Wheel & Decision Spinner App',
    _description: 'Spinify is an advanced wheel spinner app: create custom wheels, set probability weights, use 14 presets, nested wheels, and full spin customization.',
    nav_home: '← Sogepps Home',
    nav_screens: 'Screenshots',
    nav_wheels: 'Preset Wheels',
    nav_features: 'Features',
    nav_how: 'How It Works',
    nav_privacy: 'Privacy Policy',
    hero_title: 'Spinify<br />Luck Is In Your Hands',
    hero_lead: 'Spinify is a powerful wheel and decision spinner for food picks, party games, chores, workouts, travel ideas, and everyday choices. Build your own wheels or start with ready-made presets.',
    tag_1: '14 preset wheels',
    tag_2: 'Weighted odds',
    tag_3: 'Nested wheels',
    tag_4: '24 languages',
    screens_title: 'Spinify In Action',
    screens_desc: 'Screens from the app: library, spin animation, editor, weights, presets, nested wheels, results, and settings.',
    s_1_t: 'Wheel Library',
    s_1_d: 'Browse your custom wheels and ready-made presets with search and category filters.',
    s_2_t: 'Smooth Spin Animation',
    s_2_d: 'Realistic wheel physics with haptics, confetti, and a clear winning slice.',
    s_3_t: 'Live Wheel Editor',
    s_3_d: 'Edit slices, emoji, colors, and descriptions with a live preview.',
    s_4_t: 'Probability Weights',
    s_4_d: 'Slice size reflects real landing chance — rare outcomes stay rare.',
    s_5_t: 'Ready-made Wheels',
    s_5_d: '14 presets for food, drinks, decisions, party, chores, workout, and more.',
    s_6_t: 'Nested Wheels',
    s_6_d: 'Link a slice to a second wheel — great for evening plans and combos.',
    s_7_t: 'Celebration Result',
    s_7_d: 'Confetti and a bold result screen when the wheel stops.',
    s_8_t: 'Spin Customization',
    s_8_d: 'Tune duration, turns, easing, direction, labels, and elimination mode.',
    wheels_title: 'Ready-made Wheels',
    wheels_desc: 'Start instantly with 14 built-in wheels — customize or duplicate any of them.',
    w_food_t: 'What to Eat Today?',
    w_food_d: 'End dinner indecision.',
    w_drink_t: 'What to Drink?',
    w_drink_d: 'Coffee, tea, lemonade, and more.',
    w_movie_t: 'Movie Genre',
    w_movie_d: 'Action, comedy, horror, sci-fi, and more.',
    w_yesno_t: 'Yes / No',
    w_yesno_d: 'The classic quick decision wheel.',
    w_decision_t: 'Decision Wheel',
    w_decision_d: 'Definitely yes, maybe, later, no, up to you.',
    w_truth_t: 'Truth or Dare?',
    w_truth_d: 'Perfect for game night.',
    w_chores_t: 'Who Does the Chore?',
    w_chores_d: 'Dishes, sweeping, trash, laundry, or day off.',
    w_workout_t: 'Workout Wheel',
    w_workout_d: 'Push-ups, squats, plank, burpees, run, or rest.',
    w_pays_t: 'Who Pays the Bill?',
    w_pays_d: 'You, me, them, or split.',
    w_numbers_t: 'Lucky Number (1-8)',
    w_numbers_d: 'Pick a random number from 1 to 8.',
    w_party_t: 'Dare Penalty Wheel',
    w_party_d: 'Sing, dance, joke, impression, pardoned, or secret.',
    w_travel_t: 'Where to Travel?',
    w_travel_d: 'Beach, mountains, city, camping, abroad, or stay home.',
    w_prize_t: 'Prize Wheel',
    w_prize_d: 'Weighted odds — grand prize lands rarely.',
    w_evening_t: 'Evening Plan? (Nested)',
    w_evening_d: 'Opens food or movie wheels when a slice wins.',
    feat_title: 'Why Spinify?',
    feat_desc: 'More than a basic spinner — full control over odds, design, and flow.',
    f_1_t: 'True Probability',
    f_1_d: 'Adjust slice weights so landing chances match what you set.',
    f_2_t: 'Nested Wheels',
    f_2_d: 'Chain wheels together for multi-step decisions.',
    f_3_t: 'Elimination Mode',
    f_3_d: 'Remove winners each round until one slice remains.',
    f_4_t: 'Save Locally',
    f_4_d: 'Create, duplicate, and keep your wheels on device.',
    f_5_t: '24 Languages',
    f_5_d: 'Interface and presets adapt to your language.',
    f_6_t: 'Dark Modern UI',
    f_6_d: 'Polished design with SVG wheels and smooth animation.',
    how_title: 'How Spinify Works',
    how_desc: 'From idea to result in seconds.',
    how_1_t: '1) Pick or create a wheel',
    how_1_d: 'Choose a preset or build slices with emoji and colors.',
    how_2_t: '2) Set weights and options',
    how_2_d: 'Fine-tune odds, spin speed, haptics, and nested links.',
    how_3_t: '3) Tap SPIN',
    how_3_d: 'Watch the wheel spin with realistic slowdown.',
    how_4_t: '4) Get your result',
    how_4_d: 'See the winner with confetti — spin again or open a child wheel.',
    cta_title: 'Let the Wheel Decide',
    cta_desc: 'Spinify is the 4th app in the Sogepps family — fast, fair, and fun decisions on your phone.',
    btn_home: 'Back to Sogepps home',
    btn_contact: 'Contact',
    footer_privacy: 'Privacy Policy'
  };

  var tr = {
    _title: 'Spinify - Özel Çark ve Karar Uygulaması',
    _description: 'Spinify ile özel çarklar oluşturun, olasılık ağırlıkları ayarlayın, 14 hazır çark kullanın, iç içe çarklar ve tam dönüş özelleştirmesi.',
    nav_home: '← Sogepps ana sayfa',
    nav_screens: 'Görseller',
    nav_wheels: 'Hazır Çarklar',
    nav_features: 'Özellikler',
    nav_how: 'Nasıl Çalışır',
    nav_privacy: 'Gizlilik Politikası',
    hero_title: 'Spinify<br />Şans Senin Elinde',
    hero_lead: 'Spinify; yemek seçimi, parti oyunları, ev işleri, egzersiz, tatil fikirleri ve günlük kararlar için gelişmiş bir çark uygulamasıdır. Kendi çarkını oluştur veya hazır şablonlarla başla.',
    tag_1: '14 hazır çark',
    tag_2: 'Olasılık ağırlığı',
    tag_3: 'İç içe çarklar',
    tag_4: '24 dil',
    screens_title: 'Spinify Ekranları',
    screens_desc: 'Uygulamadan ekran görüntüleri: kütüphane, çevirme, düzenleyici, ağırlıklar, hazır çarklar, iç içe çark, sonuç ve ayarlar.',
    s_1_t: 'Çark Kütüphanesi',
    s_1_d: 'Özel çarklarını ve hazır şablonları arama ve kategori filtresiyle keşfet.',
    s_2_t: 'Akıcı Çevirme',
    s_2_d: 'Gerçekçi fizik, titreşim, konfeti ve net kazanan dilimi.',
    s_3_t: 'Canlı Düzenleyici',
    s_3_d: 'Dilim, emoji, renk ve açıklamaları canlı önizleme ile düzenle.',
    s_4_t: 'Olasılık Ağırlıkları',
    s_4_d: 'Dilim boyutu gerçek gelme şansını yansıtır — nadir sonuçlar nadir kalır.',
    s_5_t: 'Hazır Çarklar',
    s_5_d: 'Yemek, içecek, karar, parti, ev işi ve daha fazlası için 14 şablon.',
    s_6_t: 'İç İçe Çarklar',
    s_6_d: 'Bir dilimi ikinci çarka bağla — akşam planı gibi çok adımlı kararlar için.',
    s_7_t: 'Kutlama Sonucu',
    s_7_d: 'Çark durunca konfeti ve belirgin sonuç ekranı.',
    s_8_t: 'Dönüş Ayarları',
    s_8_d: 'Süre, tur sayısı, yavaşlama, yön, etiketler ve eleme modu.',
    wheels_title: 'Hazır Çarklar',
    wheels_desc: '14 yerleşik çarkla anında başla — istediğini özelleştir veya kopyala.',
    w_food_t: 'Bugün Ne Yesek?',
    w_food_d: 'Akşam yemeği kararsızlığına son.',
    w_drink_t: 'Ne İçsem?',
    w_drink_d: 'Kahve, çay, limonata ve daha fazlası.',
    w_movie_t: 'Film Türü',
    w_movie_d: 'Aksiyon, komedi, korku, bilim kurgu ve daha fazlası.',
    w_yesno_t: 'Evet / Hayır',
    w_yesno_d: 'Hızlı karar için klasik çark.',
    w_decision_t: 'Karar Çarkı',
    w_decision_d: 'Kesinlikle evet, belki, sonra, hayır, sen bilirsin.',
    w_truth_t: 'Doğruluk mu Cesaret mi?',
    w_truth_d: 'Oyun gecesi için ideal.',
    w_chores_t: 'Ev İşi Kim Yapacak?',
    w_chores_d: 'Bulaşık, süpürme, çöp, çamaşır veya izin günü.',
    w_workout_t: 'Egzersiz Çarkı',
    w_workout_d: 'Şınav, squat, plank, burpee, koşu veya dinlen.',
    w_pays_t: 'Hesabı Kim Ödeyecek?',
    w_pays_d: 'Sen, ben, o veya ortak.',
    w_numbers_t: 'Şanslı Sayı (1-8)',
    w_numbers_d: '1 ile 8 arasında rastgele sayı.',
    w_party_t: 'Ceza Çarkı',
    w_party_d: 'Şarkı, dans, fıkra, taklit, affedildin veya sır.',
    w_travel_t: 'Tatil Nereye?',
    w_travel_d: 'Deniz, dağ, şehir, kamp, yurt dışı veya evde kal.',
    w_prize_t: 'Ödül Çarkı',
    w_prize_d: 'Ağırlıklı olasılık — büyük ödül nadir gelir.',
    w_evening_t: 'Akşam Ne Yapsak? (İç İçe)',
    w_evening_d: 'Kazanan dilim yemek veya film çarkını açar.',
    feat_title: 'Neden Spinify?',
    feat_desc: 'Basit bir çarktan fazlası — olasılık, tasarım ve akış üzerinde tam kontrol.',
    f_1_t: 'Gerçek Olasılık',
    f_1_d: 'Dilim ağırlıklarını ayarla, gelme şansı tam istediğin gibi olsun.',
    f_2_t: 'İç İçe Çarklar',
    f_2_d: 'Çok adımlı kararlar için çarkları zincirle.',
    f_3_t: 'Eleme Modu',
    f_3_d: 'Her turda kazananı çıkar, tek dilim kalana kadar devam et.',
    f_4_t: 'Yerel Kayıt',
    f_4_d: 'Çarklarını oluştur, kopyala ve cihazında sakla.',
    f_5_t: '24 Dil',
    f_5_d: 'Arayüz ve hazır çarklar diline uyum sağlar.',
    f_6_t: 'Modern Koyu Arayüz',
    f_6_d: 'SVG çarklar ve akıcı animasyonla şık tasarım.',
    how_title: 'Spinify Nasıl Çalışır?',
    how_desc: 'Fikirden sonuca saniyeler içinde.',
    how_1_t: '1) Çark seç veya oluştur',
    how_1_d: 'Hazır şablondan başla veya emoji ve renklerle dilim ekle.',
    how_2_t: '2) Ağırlık ve ayarları yap',
    how_2_d: 'Olasılık, dönüş hızı, titreşim ve iç çark bağlantılarını ayarla.',
    how_3_t: '3) ÇEVİR\'e bas',
    how_3_d: 'Gerçekçi yavaşlama ile çarkın dönmesini izle.',
    how_4_t: '4) Sonucu gör',
    how_4_d: 'Konfeti ile kazananı gör — tekrar çevir veya iç çarkı aç.',
    cta_title: 'Kararı Çarka Bırak',
    cta_desc: 'Spinify, Sogepps ailesinin 4. uygulaması — hızlı, adil ve eğlenceli kararlar telefonunda.',
    btn_home: 'Sogepps ana sayfaya dön',
    btn_contact: 'İletişim',
    footer_privacy: 'Gizlilik Politikası'
  };

  var translations = {};
  var shared = ['de', 'fr', 'es', 'it', 'pt', 'nl', 'ru', 'ja', 'ko', 'ar', 'hi', 'id', 'pl'];
  translations.en = en;
  translations.tr = tr;
  shared.forEach(function (code) { translations[code] = en; });
  return translations;
})();
