var PRIVACY_TRANSLATIONS = {
  en: {
    _title: 'Privacy Policy – Spinify',
    _description: 'Privacy Policy for the Spinify mobile application by Sogepps.',
    nav_back: '← Spinify',
    nav_privacy: 'Privacy Policy',
    page_title: '🔐 Privacy Policy – Spinify',
    page_date: 'Last updated: 18 June 2026',
    intro: 'We at <strong>Spinify</strong> ("App") value your privacy. This Privacy Policy explains what information is collected when you use the app, how it is used, and how it is protected.<br /><br />By using the App, you accept this Privacy Policy.',
    s1_title: '1. Information We Collect',
    s1_p1: 'Spinify does not require an account or mandatory personal data. The app works as a local wheel and decision tool without asking for your name, email, or phone number.',
    s1_p2: 'Data you create in the app may include:',
    s1_li1: 'Custom wheel names, categories, and descriptions',
    s1_li2: 'Slice labels, emoji, colors, and probability weights',
    s1_li3: 'Spin settings (duration, turns, effects, elimination mode)',
    s1_li4: 'Language preference',
    s1_p3: 'This information is stored only on your device (local storage) to save your wheels and preferences. It is not uploaded to our servers.',
    s2_title: '2. Automatically Collected Information',
    s2_p1: 'To improve performance and stability, the following anonymous information may be collected automatically:',
    s2_li1: 'App usage and crash analytics',
    s2_li2: 'Device type and operating system version',
    s2_li3: 'General diagnostic data from the app platform',
    s2_p2: 'This data does not include the content of your wheels and is used only to maintain and improve the App.',
    s3_title: '3. Advertising',
    s3_p1: 'Spinify may use third-party advertising services (such as Google AdMob) to show interstitial ads. These providers may collect advertising identifiers and anonymous usage data to deliver and measure ads.',
    s3_p2: 'Ad providers are governed by their own privacy policies. You can limit personalized ads in your device settings (Google Ads settings on Android, or App Tracking / privacy settings on iOS).',
    s4_title: '4. Children\'s Privacy',
    s4_p1: 'Spinify does not knowingly collect personal data from children under 13. If you are a parent or guardian and believe your child has provided personal information, please contact us.',
    s5_title: '5. Data Security',
    s5_p1: 'We design Spinify to keep your wheel data on your device. We take reasonable measures to protect any data processed by the App.',
    s5_p2: 'No method of electronic storage or transmission is 100% secure. Uninstalling the app removes locally stored wheel data from your device.',
    s6_title: '6. Third-Party Services',
    s6_p1: 'The App may rely on third-party services (e.g. Google Mobile Ads) with their own privacy practices. Spinify is not responsible for how those services handle data. We recommend reviewing their policies.',
    s7_title: '7. Changes to This Privacy Policy',
    s7_p1: 'We may update this Privacy Policy from time to time. Changes will be posted on this page and take effect when published.',
    s8_title: '8. Contact',
    s8_p1: 'For questions about this Privacy Policy, contact us:',
    s8_email: '📧 Email:',
    s8_web: '🌐 Website:',
    footer_brand: 'Spinify',
    footer_by: 'by',
  },
  tr: {
    _title: 'Gizlilik Politikası – Spinify',
    _description: 'Spinify mobil uygulaması Gizlilik Politikası – Sogepps.',
    nav_back: '← Spinify',
    nav_privacy: 'Gizlilik Politikası',
    page_title: '🔐 Gizlilik Politikası – Spinify',
    page_date: 'Son güncelleme: 18 Haziran 2026',
    intro: '<strong>Spinify</strong> ("Uygulama") olarak kullanıcılarımızın gizliliğine önem veriyoruz. Bu Gizlilik Politikası, uygulamayı kullandığınızda hangi bilgilerin toplandığını, nasıl kullanıldığını ve nasıl korunduğunu açıklar.<br /><br />Uygulamayı kullanarak bu Gizlilik Politikası\'nı kabul etmiş olursunuz.',
    s1_title: '1. Toplanan Bilgiler',
    s1_p1: 'Spinify hesap açmayı veya zorunlu kişisel veri paylaşımını gerektirmez. Uygulama; ad, e-posta veya telefon bilgisi istemeden yerel bir çark ve karar aracı olarak çalışır.',
    s1_p2: 'Uygulamada oluşturduğunuz veriler şunları içerebilir:',
    s1_li1: 'Özel çark adları, kategoriler ve açıklamalar',
    s1_li2: 'Dilim etiketleri, emoji, renkler ve olasılık ağırlıkları',
    s1_li3: 'Dönüş ayarları (süre, tur sayısı, efektler, eleme modu)',
    s1_li4: 'Dil tercihi',
    s1_p3: 'Bu bilgiler yalnızca çarklarınızı ve tercihlerinizi saklamak için cihazınızda (yerel depolama) tutulur. Sunucularımıza yüklenmez.',
    s2_title: '2. Otomatik Olarak Toplanan Bilgiler',
    s2_p1: 'Performans ve kararlılığı artırmak için aşağıdaki anonim bilgiler otomatik toplanabilir:',
    s2_li1: 'Uygulama kullanım ve çökme analitiği',
    s2_li2: 'Cihaz türü ve işletim sistemi sürümü',
    s2_li3: 'Uygulama platformundan gelen genel tanılama verileri',
    s2_p2: 'Bu veriler çark içeriklerinizi içermez ve yalnızca uygulamanın geliştirilmesi için kullanılır.',
    s3_title: '3. Reklamlar',
    s3_p1: 'Spinify, ara reklamlar göstermek için üçüncü taraf reklam hizmetleri (örneğin Google AdMob) kullanabilir. Bu sağlayıcılar reklam tanımlayıcıları ve anonim kullanım verileri toplayabilir.',
    s3_p2: 'Reklam sağlayıcıları kendi gizlilik politikalarına tabidir. Kişiselleştirilmiş reklamları cihaz ayarlarından (Android\'de Google Reklamlar, iOS\'ta gizlilik ayarları) sınırlayabilirsiniz.',
    s4_title: '4. Çocukların Gizliliği',
    s4_p1: 'Spinify, 13 yaş altındaki çocuklardan bilerek kişisel veri toplamaz. Ebeveyn veya vasi iseniz ve çocuğunuzun bilgi paylaştığını düşünüyorsanız bizimle iletişime geçin.',
    s5_title: '5. Veri Güvenliği',
    s5_p1: 'Spinify, çark verilerinizi cihazınızda tutacak şekilde tasarlanmıştır. Uygulama tarafından işlenen verileri korumak için makul önlemler alırız.',
    s5_p2: 'Elektronik depolama veya aktarım yöntemlerinin hiçbiri %100 güvenli değildir. Uygulamayı kaldırmak, cihazdaki yerel çark verilerini siler.',
    s6_title: '6. Üçüncü Taraf Hizmetler',
    s6_p1: 'Uygulama, kendi gizlilik uygulamaları olan üçüncü taraf hizmetlere (ör. Google Mobile Ads) dayanabilir. Spinify bu hizmetlerin veri işleme süreçlerinden sorumlu değildir. İlgili politikaları incelemenizi öneririz.',
    s7_title: '7. Gizlilik Politikasındaki Değişiklikler',
    s7_p1: 'Bu Gizlilik Politikası zaman zaman güncellenebilir. Değişiklikler bu sayfada yayınlanır ve yayınlandığı tarihten itibaren geçerli olur.',
    s8_title: '8. İletişim',
    s8_p1: 'Bu Gizlilik Politikası ile ilgili sorularınız için:',
    s8_email: '📧 E-posta:',
    s8_web: '🌐 Web sitesi:',
    footer_brand: 'Spinify',
    footer_by: 'yapımcı',
  },
};
