var PRIVACY_TRANSLATIONS = {
  en: {
    _title: 'Privacy Policy – League & Tournament Maker',
    _description: 'Privacy Policy for League & Tournament Maker mobile application by Sogepps.',
    nav_back: '← Tournament Maker',
    nav_privacy: 'Privacy Policy',
    nav_delete: 'Delete Account',
    page_title: '🔐 Privacy Policy',
    page_date: 'Last updated: 28 February 2026',
    intro: 'This Privacy Policy explains how we collect, use, and protect your information when you use our mobile application <strong>League &amp; Tournament Maker</strong> ("App"). By using the App, you agree to the collection and use of information in accordance with this policy.',
    s1_title: '1. Information We Collect',
    s1a_title: 'a) Personal Information',
    s1a_p1: 'We do not require users to provide personally identifiable information such as name, address, or phone number.',
    s1a_p2: 'If you sign in using third-party services (such as Google Sign-In), authentication data is handled securely by the respective provider and is not stored directly by us.',
    s1b_title: 'b) Usage Data',
    s1b_p1: 'We may collect limited, non-personal information automatically, including:',
    s1b_li1: 'App usage statistics',
    s1b_li2: 'Device type and operating system',
    s1b_li3: 'Crash reports and performance data',
    s1b_p2: 'This data is used solely to improve app stability and user experience.',
    s1c_title: 'c) Advertising Data',
    s1c_p1: 'Our App may display advertisements provided by Google AdMob.',
    s1c_p2: 'AdMob may collect and process information such as:',
    s1c_li1: 'Device identifiers',
    s1c_li2: 'Approximate location (country-level)',
    s1c_li3: 'Ad interaction data',
    s1c_p3: 'This information is used to display ads and measure their performance.',
    s2_title: '2. Advertisements & Consent',
    s2a_title: 'a) User Consent',
    s2a_p1: 'For users located in regions where consent is required (such as the European Economic Area, the United Kingdom, and Switzerland), we request user consent before showing personalized ads.',
    s2a_p2: 'Users may choose:',
    s2a_li1: 'Personalized ads',
    s2a_li2: 'Non-personalized ads',
    s2a_li3: 'Or decline consent where applicable',
    s2a_p3: 'Ad serving behavior respects the user\'s consent choices.',
    s2b_title: 'b) Non-Personalized Ads',
    s2b_p1: 'If consent is not provided, ads may still be shown in a non-personalized manner, in accordance with Google\'s policies.',
    s3_title: '3. Credits, Free Usage & Premium Features',
    s3_p1: 'The App offers limited free usage through a credit-based system.',
    s3_p2: 'Free credits may renew automatically after a defined waiting period.',
    s3_p3: 'Optional premium features may be available through in-app purchases.',
    s3_p4: 'Watching advertisements is never mandatory to access core functionality.',
    s4_title: '4. Data Sharing',
    s4_p1: 'We do not sell, trade, or rent user data to third parties.',
    s4_p2: 'Limited data may be shared with trusted service providers strictly for:',
    s4_li1: 'Analytics',
    s4_li2: 'Advertising',
    s4_li3: 'App performance monitoring',
    s4_p3: 'All such providers comply with applicable data protection regulations.',
    s5_title: '5. Children\'s Privacy',
    s5_p1: 'Our App is not intended for children under the age of 13.',
    s5_p2: 'We do not knowingly collect personal information from children. If you believe that a child has provided personal data through the App, please contact us so we can remove the information.',
    s6_title: '6. Data Security',
    s6_p1: 'We take reasonable measures to protect user data from unauthorized access, alteration, or disclosure.',
    s6_p2: 'However, no method of electronic transmission or storage is 100% secure.',
    s7_title: '7. Third-Party Services',
    s7_p1: 'The App may use third-party services that have their own privacy policies, including but not limited to:',
    s7_li1: 'Google AdMob',
    s7_li2: 'Google Analytics for Firebase',
    s7_p2: 'We recommend reviewing the privacy policies of these providers for more information.',
    s8_title: '8. Your Rights',
    s8_p1: 'Depending on your location, you may have rights to:',
    s8_li1: 'Access your data',
    s8_li2: 'Request deletion of your data',
    s8_li3: 'Withdraw consent for personalized advertising',
    s8_p2: 'Requests can be made using the contact information below.',
    s9_title: '9. Changes to This Policy',
    s9_p1: 'We may update this Privacy Policy from time to time.',
    s9_p2: 'Any changes will be posted on this page with an updated revision date.',
    s10_title: '10. Contact Us',
    s10_p1: 'If you have any questions or concerns about this Privacy Policy, you can contact us at:',
    s10_p2: 'Email:',
    footer_brand: 'League & Tournament Maker',
    footer_by: 'by',
  },
  tr: {
    _title: 'Gizlilik Politikası – Lig ve Turnuva Oluşturucu',
    _description: 'Lig ve Turnuva Oluşturucu mobil uygulaması için Gizlilik Politikası.',
    nav_back: '← Turnuva Oluşturucu',
    nav_privacy: 'Gizlilik Politikası',
    nav_delete: 'Hesap Sil',
    page_title: '🔐 Gizlilik Politikası',
    page_date: 'Son güncelleme: 28 Şubat 2026',
    intro: 'Bu Gizlilik Politikası, <strong>Lig ve Turnuva Oluşturucu</strong> ("Uygulama") mobil uygulamamızı kullandığınızda bilgilerinizi nasıl topladığımızı, kullandığımızı ve koruduğumuzu açıklar. Uygulamayı kullanarak, bu politikaya uygun olarak bilgi toplanmasını ve kullanılmasını kabul edersiniz.',
    s1_title: '1. Topladığımız Bilgiler',
    s1a_title: 'a) Kişisel Bilgiler',
    s1a_p1: 'Kullanıcılardan ad, adres veya telefon numarası gibi kişisel tanımlayıcı bilgiler sağlamalarını istemiyoruz.',
    s1a_p2: 'Üçüncü taraf hizmetleri (Google ile Oturum Açma gibi) kullanarak giriş yaparsanız, kimlik doğrulama verileri ilgili sağlayıcı tarafından güvenli bir şekilde işlenir ve doğrudan tarafımızca saklanmaz.',
    s1b_title: 'b) Kullanım Verileri',
    s1b_p1: 'Aşağıdakiler dahil sınırlı, kişisel olmayan bilgileri otomatik olarak toplayabiliriz:',
    s1b_li1: 'Uygulama kullanım istatistikleri',
    s1b_li2: 'Cihaz türü ve işletim sistemi',
    s1b_li3: 'Çökme raporları ve performans verileri',
    s1b_p2: 'Bu veriler yalnızca uygulama kararlılığını ve kullanıcı deneyimini iyileştirmek için kullanılır.',
    s1c_title: 'c) Reklam Verileri',
    s1c_p1: 'Uygulamamız, Google AdMob tarafından sağlanan reklamlar gösterebilir.',
    s1c_p2: 'AdMob şu tür bilgileri toplayabilir ve işleyebilir:',
    s1c_li1: 'Cihaz tanımlayıcıları',
    s1c_li2: 'Yaklaşık konum (ülke düzeyinde)',
    s1c_li3: 'Reklam etkileşim verileri',
    s1c_p3: 'Bu bilgiler reklamları görüntülemek ve performanslarını ölçmek için kullanılır.',
    s2_title: '2. Reklamlar ve Onay',
    s2a_title: 'a) Kullanıcı Onayı',
    s2a_p1: 'Onay gereken bölgelerde (Avrupa Ekonomik Alanı, Birleşik Krallık ve İsviçre gibi) bulunan kullanıcılar için kişiselleştirilmiş reklamları göstermeden önce kullanıcı onayı isteriz.',
    s2a_p2: 'Kullanıcılar şunları seçebilir:',
    s2a_li1: 'Kişiselleştirilmiş reklamlar',
    s2a_li2: 'Kişiselleştirilmemiş reklamlar',
    s2a_li3: 'Veya uygulanabilir olduğunda onayı reddetme',
    s2a_p3: 'Reklam sunma davranışı kullanıcının onay tercihlerine saygı gösterir.',
    s2b_title: 'b) Kişiselleştirilmemiş Reklamlar',
    s2b_p1: 'Onay verilmezse, Google politikalarına uygun olarak reklamlar kişiselleştirilmemiş şekilde gösterilebilir.',
    s3_title: '3. Krediler, Ücretsiz Kullanım ve Premium Özellikler',
    s3_p1: 'Uygulama, kredi tabanlı bir sistem aracılığıyla sınırlı ücretsiz kullanım sunar.',
    s3_p2: 'Ücretsiz krediler belirli bir bekleme süresinden sonra otomatik olarak yenilenebilir.',
    s3_p3: 'Opsiyonel premium özellikler uygulama içi satın alma yoluyla kullanılabilir.',
    s3_p4: 'Temel işlevselliğe erişmek için reklam izlemek asla zorunlu değildir.',
    s4_title: '4. Veri Paylaşımı',
    s4_p1: 'Kullanıcı verilerini üçüncü taraflara satmıyoruz, takas etmiyoruz veya kiralamıyoruz.',
    s4_p2: 'Sınırlı veriler güvenilir hizmet sağlayıcılarla yalnızca şu amaçlarla paylaşılabilir:',
    s4_li1: 'Analitik',
    s4_li2: 'Reklamcılık',
    s4_li3: 'Uygulama performans izleme',
    s4_p3: 'Tüm bu sağlayıcılar geçerli veri koruma düzenlemelerine uygundur.',
    s5_title: '5. Çocukların Gizliliği',
    s5_p1: 'Uygulamamız 13 yaşın altındaki çocuklar için tasarlanmamıştır.',
    s5_p2: 'Çocuklardan bilerek kişisel bilgi toplamıyoruz. Bir çocuğun Uygulama aracılığıyla kişisel veri sağladığına inanıyorsanız, bilgileri kaldırabilmemiz için lütfen bizimle iletişime geçin.',
    s6_title: '6. Veri Güvenliği',
    s6_p1: 'Kullanıcı verilerini yetkisiz erişim, değiştirme veya ifşadan korumak için makul önlemler alıyoruz.',
    s6_p2: 'Ancak, hiçbir elektronik iletim veya depolama yöntemi %100 güvenli değildir.',
    s7_title: '7. Üçüncü Taraf Hizmetleri',
    s7_p1: 'Uygulama, kendi gizlilik politikalarına sahip üçüncü taraf hizmetlerini kullanabilir, bunlar arasında:',
    s7_li1: 'Google AdMob',
    s7_li2: 'Google Analytics for Firebase',
    s7_p2: 'Daha fazla bilgi için bu sağlayıcıların gizlilik politikalarını incelemenizi öneririz.',
    s8_title: '8. Haklarınız',
    s8_p1: 'Konumunuza bağlı olarak şu haklara sahip olabilirsiniz:',
    s8_li1: 'Verilerinize erişim',
    s8_li2: 'Verilerinizin silinmesini talep etme',
    s8_li3: 'Kişiselleştirilmiş reklamcılık için onayı geri çekme',
    s8_p2: 'Talepler aşağıdaki iletişim bilgileri kullanılarak yapılabilir.',
    s9_title: '9. Bu Politikadaki Değişiklikler',
    s9_p1: 'Bu Gizlilik Politikasını zaman zaman güncelleyebiliriz.',
    s9_p2: 'Değişiklikler bu sayfada güncellenmiş bir revizyon tarihi ile yayınlanacaktır.',
    s10_title: '10. Bize Ulaşın',
    s10_p1: 'Bu Gizlilik Politikası hakkında sorularınız veya endişeleriniz varsa bize şu adresten ulaşabilirsiniz:',
    s10_p2: 'E-posta:',
    footer_brand: 'Lig ve Turnuva Oluşturucu',
    footer_by: 'yapımcı',
  },
  de: {
    _title: 'Datenschutzrichtlinie – Liga & Turnier Ersteller',
    _description: 'Datenschutzrichtlinie für die mobile Anwendung Liga & Turnier Ersteller von Sogepps.',
    nav_back: '← Turnier Ersteller',
    nav_privacy: 'Datenschutzrichtlinie',
    nav_delete: 'Konto löschen',
    page_title: '🔐 Datenschutzrichtlinie',
    page_date: 'Zuletzt aktualisiert: 28. Februar 2026',
    intro: 'Diese Datenschutzrichtlinie erklärt, wie wir Ihre Informationen erfassen, verwenden und schützen, wenn Sie unsere mobile Anwendung <strong>Liga &amp; Turnier Ersteller</strong> („App") nutzen. Durch die Nutzung der App stimmen Sie der Erfassung und Verwendung von Informationen gemäß dieser Richtlinie zu.',
    s1_title: '1. Informationen, die wir erfassen',
    s1a_title: 'a) Persönliche Informationen',
    s1a_p1: 'Wir verlangen von Benutzern keine personenbezogenen Daten wie Name, Adresse oder Telefonnummer.',
    s1a_p2: 'Wenn Sie sich über Drittanbieter-Dienste (wie Google-Anmeldung) anmelden, werden die Authentifizierungsdaten vom jeweiligen Anbieter sicher verarbeitet und nicht direkt von uns gespeichert.',
    s1b_title: 'b) Nutzungsdaten',
    s1b_p1: 'Wir können automatisch begrenzte, nicht-personenbezogene Informationen erfassen, darunter:',
    s1b_li1: 'App-Nutzungsstatistiken',
    s1b_li2: 'Gerätetyp und Betriebssystem',
    s1b_li3: 'Absturzberichte und Leistungsdaten',
    s1b_p2: 'Diese Daten werden ausschließlich zur Verbesserung der App-Stabilität und Benutzererfahrung verwendet.',
    s1c_title: 'c) Werbedaten',
    s1c_p1: 'Unsere App kann Werbung anzeigen, die von Google AdMob bereitgestellt wird.',
    s1c_p2: 'AdMob kann Informationen wie die folgenden erfassen und verarbeiten:',
    s1c_li1: 'Gerätekennungen',
    s1c_li2: 'Ungefährer Standort (Länderebene)',
    s1c_li3: 'Anzeigen-Interaktionsdaten',
    s1c_p3: 'Diese Informationen werden verwendet, um Anzeigen darzustellen und deren Leistung zu messen.',
    s2_title: '2. Werbung & Einwilligung',
    s2a_title: 'a) Benutzereinwilligung',
    s2a_p1: 'Für Benutzer in Regionen, in denen eine Einwilligung erforderlich ist (wie dem Europäischen Wirtschaftsraum, dem Vereinigten Königreich und der Schweiz), bitten wir um Benutzereinwilligung, bevor personalisierte Anzeigen geschaltet werden.',
    s2a_p2: 'Benutzer können wählen:',
    s2a_li1: 'Personalisierte Anzeigen',
    s2a_li2: 'Nicht-personalisierte Anzeigen',
    s2a_li3: 'Oder die Einwilligung ablehnen, sofern zutreffend',
    s2a_p3: 'Das Anzeigenverhalten respektiert die Einwilligungsentscheidungen des Benutzers.',
    s2b_title: 'b) Nicht-personalisierte Anzeigen',
    s2b_p1: 'Wenn keine Einwilligung erteilt wird, können Anzeigen dennoch in nicht-personalisierter Form gemäß den Richtlinien von Google geschaltet werden.',
    s3_title: '3. Credits, kostenlose Nutzung & Premium-Funktionen',
    s3_p1: 'Die App bietet eine begrenzte kostenlose Nutzung über ein Credit-basiertes System.',
    s3_p2: 'Kostenlose Credits können nach einer festgelegten Wartezeit automatisch erneuert werden.',
    s3_p3: 'Optionale Premium-Funktionen können über In-App-Käufe verfügbar sein.',
    s3_p4: 'Das Ansehen von Werbung ist niemals erforderlich, um auf die Kernfunktionalität zuzugreifen.',
    s4_title: '4. Datenweitergabe',
    s4_p1: 'Wir verkaufen, tauschen oder vermieten Benutzerdaten nicht an Dritte.',
    s4_p2: 'Begrenzte Daten können mit vertrauenswürdigen Dienstleistern ausschließlich für folgende Zwecke geteilt werden:',
    s4_li1: 'Analytik',
    s4_li2: 'Werbung',
    s4_li3: 'App-Leistungsüberwachung',
    s4_p3: 'Alle diese Anbieter halten die geltenden Datenschutzbestimmungen ein.',
    s5_title: '5. Datenschutz für Kinder',
    s5_p1: 'Unsere App ist nicht für Kinder unter 13 Jahren bestimmt.',
    s5_p2: 'Wir erfassen wissentlich keine persönlichen Daten von Kindern. Wenn Sie glauben, dass ein Kind über die App persönliche Daten bereitgestellt hat, kontaktieren Sie uns bitte, damit wir die Informationen entfernen können.',
    s6_title: '6. Datensicherheit',
    s6_p1: 'Wir ergreifen angemessene Maßnahmen, um Benutzerdaten vor unbefugtem Zugriff, Änderung oder Offenlegung zu schützen.',
    s6_p2: 'Jedoch ist keine Methode der elektronischen Übertragung oder Speicherung zu 100 % sicher.',
    s7_title: '7. Dienste Dritter',
    s7_p1: 'Die App kann Dienste Dritter nutzen, die eigene Datenschutzrichtlinien haben, darunter:',
    s7_li1: 'Google AdMob',
    s7_li2: 'Google Analytics for Firebase',
    s7_p2: 'Wir empfehlen, die Datenschutzrichtlinien dieser Anbieter für weitere Informationen zu lesen.',
    s8_title: '8. Ihre Rechte',
    s8_p1: 'Abhängig von Ihrem Standort haben Sie möglicherweise das Recht auf:',
    s8_li1: 'Zugriff auf Ihre Daten',
    s8_li2: 'Löschung Ihrer Daten beantragen',
    s8_li3: 'Einwilligung für personalisierte Werbung widerrufen',
    s8_p2: 'Anfragen können über die unten angegebenen Kontaktinformationen gestellt werden.',
    s9_title: '9. Änderungen dieser Richtlinie',
    s9_p1: 'Wir können diese Datenschutzrichtlinie von Zeit zu Zeit aktualisieren.',
    s9_p2: 'Änderungen werden auf dieser Seite mit einem aktualisierten Überarbeitungsdatum veröffentlicht.',
    s10_title: '10. Kontaktieren Sie uns',
    s10_p1: 'Wenn Sie Fragen oder Bedenken zu dieser Datenschutzrichtlinie haben, können Sie uns kontaktieren unter:',
    s10_p2: 'E-Mail:',
    footer_brand: 'Liga & Turnier Ersteller',
    footer_by: 'von',
  },
  fr: {
    _title: 'Politique de confidentialité – Ligue & Créateur de Tournois',
    _description: 'Politique de confidentialité pour l\'application mobile Ligue & Créateur de Tournois par Sogepps.',
    nav_back: '← Créateur de Tournois',
    nav_privacy: 'Politique de confidentialité',
    nav_delete: 'Supprimer le compte',
    page_title: '🔐 Politique de confidentialité',
    page_date: 'Dernière mise à jour : 28 février 2026',
    intro: 'Cette Politique de confidentialité explique comment nous collectons, utilisons et protégeons vos informations lorsque vous utilisez notre application mobile <strong>Ligue &amp; Créateur de Tournois</strong> (« Application »). En utilisant l\'Application, vous acceptez la collecte et l\'utilisation des informations conformément à cette politique.',
    s1_title: '1. Informations que nous collectons',
    s1a_title: 'a) Informations personnelles',
    s1a_p1: 'Nous n\'exigeons pas des utilisateurs qu\'ils fournissent des informations personnelles identifiables telles que le nom, l\'adresse ou le numéro de téléphone.',
    s1a_p2: 'Si vous vous connectez via des services tiers (comme Google Sign-In), les données d\'authentification sont traitées de manière sécurisée par le fournisseur concerné et ne sont pas stockées directement par nous.',
    s1b_title: 'b) Données d\'utilisation',
    s1b_p1: 'Nous pouvons collecter automatiquement des informations limitées et non personnelles, notamment :',
    s1b_li1: 'Statistiques d\'utilisation de l\'application',
    s1b_li2: 'Type d\'appareil et système d\'exploitation',
    s1b_li3: 'Rapports de plantage et données de performance',
    s1b_p2: 'Ces données sont utilisées uniquement pour améliorer la stabilité de l\'application et l\'expérience utilisateur.',
    s1c_title: 'c) Données publicitaires',
    s1c_p1: 'Notre Application peut afficher des publicités fournies par Google AdMob.',
    s1c_p2: 'AdMob peut collecter et traiter des informations telles que :',
    s1c_li1: 'Identifiants d\'appareil',
    s1c_li2: 'Localisation approximative (niveau pays)',
    s1c_li3: 'Données d\'interaction publicitaire',
    s1c_p3: 'Ces informations sont utilisées pour afficher des publicités et mesurer leur performance.',
    s2_title: '2. Publicités et consentement',
    s2a_title: 'a) Consentement de l\'utilisateur',
    s2a_p1: 'Pour les utilisateurs situés dans des régions où le consentement est requis (comme l\'Espace économique européen, le Royaume-Uni et la Suisse), nous demandons le consentement de l\'utilisateur avant d\'afficher des publicités personnalisées.',
    s2a_p2: 'Les utilisateurs peuvent choisir :',
    s2a_li1: 'Publicités personnalisées',
    s2a_li2: 'Publicités non personnalisées',
    s2a_li3: 'Ou refuser le consentement le cas échéant',
    s2a_p3: 'Le comportement de diffusion des publicités respecte les choix de consentement de l\'utilisateur.',
    s2b_title: 'b) Publicités non personnalisées',
    s2b_p1: 'Si le consentement n\'est pas accordé, des publicités peuvent toujours être affichées de manière non personnalisée, conformément aux politiques de Google.',
    s3_title: '3. Crédits, utilisation gratuite et fonctionnalités Premium',
    s3_p1: 'L\'Application offre une utilisation gratuite limitée via un système basé sur des crédits.',
    s3_p2: 'Les crédits gratuits peuvent se renouveler automatiquement après une période d\'attente définie.',
    s3_p3: 'Des fonctionnalités premium optionnelles peuvent être disponibles via des achats intégrés.',
    s3_p4: 'Regarder des publicités n\'est jamais obligatoire pour accéder aux fonctionnalités principales.',
    s4_title: '4. Partage de données',
    s4_p1: 'Nous ne vendons, n\'échangeons ni ne louons les données des utilisateurs à des tiers.',
    s4_p2: 'Des données limitées peuvent être partagées avec des prestataires de services de confiance strictement pour :',
    s4_li1: 'Analytique',
    s4_li2: 'Publicité',
    s4_li3: 'Surveillance des performances de l\'application',
    s4_p3: 'Tous ces fournisseurs respectent les réglementations applicables en matière de protection des données.',
    s5_title: '5. Confidentialité des enfants',
    s5_p1: 'Notre Application n\'est pas destinée aux enfants de moins de 13 ans.',
    s5_p2: 'Nous ne collectons pas sciemment d\'informations personnelles auprès des enfants. Si vous pensez qu\'un enfant a fourni des données personnelles via l\'Application, veuillez nous contacter afin que nous puissions supprimer ces informations.',
    s6_title: '6. Sécurité des données',
    s6_p1: 'Nous prenons des mesures raisonnables pour protéger les données des utilisateurs contre tout accès non autorisé, toute modification ou divulgation.',
    s6_p2: 'Cependant, aucune méthode de transmission ou de stockage électronique n\'est sécurisée à 100 %.',
    s7_title: '7. Services tiers',
    s7_p1: 'L\'Application peut utiliser des services tiers qui ont leurs propres politiques de confidentialité, notamment :',
    s7_li1: 'Google AdMob',
    s7_li2: 'Google Analytics for Firebase',
    s7_p2: 'Nous recommandons de consulter les politiques de confidentialité de ces fournisseurs pour plus d\'informations.',
    s8_title: '8. Vos droits',
    s8_p1: 'En fonction de votre emplacement, vous pouvez avoir le droit de :',
    s8_li1: 'Accéder à vos données',
    s8_li2: 'Demander la suppression de vos données',
    s8_li3: 'Retirer votre consentement pour la publicité personnalisée',
    s8_p2: 'Les demandes peuvent être effectuées en utilisant les coordonnées ci-dessous.',
    s9_title: '9. Modifications de cette politique',
    s9_p1: 'Nous pouvons mettre à jour cette Politique de confidentialité de temps en temps.',
    s9_p2: 'Toute modification sera publiée sur cette page avec une date de révision mise à jour.',
    s10_title: '10. Nous contacter',
    s10_p1: 'Si vous avez des questions ou des préoccupations concernant cette Politique de confidentialité, vous pouvez nous contacter à :',
    s10_p2: 'E-mail :',
    footer_brand: 'Ligue & Créateur de Tournois',
    footer_by: 'par',
  },
  es: {
    _title: 'Política de Privacidad – Liga & Creador de Torneos',
    _description: 'Política de Privacidad de la aplicación móvil Liga & Creador de Torneos de Sogepps.',
    nav_back: '← Creador de Torneos',
    nav_privacy: 'Política de Privacidad',
    nav_delete: 'Eliminar cuenta',
    page_title: '🔐 Política de Privacidad',
    page_date: 'Última actualización: 28 de febrero de 2026',
    intro: 'Esta Política de Privacidad explica cómo recopilamos, usamos y protegemos su información cuando utiliza nuestra aplicación móvil <strong>Liga &amp; Creador de Torneos</strong> ("Aplicación"). Al usar la Aplicación, usted acepta la recopilación y el uso de información de acuerdo con esta política.',
    s1_title: '1. Información que recopilamos',
    s1a_title: 'a) Información personal',
    s1a_p1: 'No requerimos que los usuarios proporcionen información de identificación personal como nombre, dirección o número de teléfono.',
    s1a_p2: 'Si inicia sesión a través de servicios de terceros (como el inicio de sesión con Google), los datos de autenticación son gestionados de forma segura por el proveedor correspondiente y no son almacenados directamente por nosotros.',
    s1b_title: 'b) Datos de uso',
    s1b_p1: 'Podemos recopilar automáticamente información limitada y no personal, que incluye:',
    s1b_li1: 'Estadísticas de uso de la aplicación',
    s1b_li2: 'Tipo de dispositivo y sistema operativo',
    s1b_li3: 'Informes de fallos y datos de rendimiento',
    s1b_p2: 'Estos datos se utilizan únicamente para mejorar la estabilidad de la aplicación y la experiencia del usuario.',
    s1c_title: 'c) Datos publicitarios',
    s1c_p1: 'Nuestra Aplicación puede mostrar anuncios proporcionados por Google AdMob.',
    s1c_p2: 'AdMob puede recopilar y procesar información como:',
    s1c_li1: 'Identificadores de dispositivo',
    s1c_li2: 'Ubicación aproximada (nivel de país)',
    s1c_li3: 'Datos de interacción con anuncios',
    s1c_p3: 'Esta información se utiliza para mostrar anuncios y medir su rendimiento.',
    s2_title: '2. Anuncios y consentimiento',
    s2a_title: 'a) Consentimiento del usuario',
    s2a_p1: 'Para los usuarios ubicados en regiones donde se requiere consentimiento (como el Espacio Económico Europeo, el Reino Unido y Suiza), solicitamos el consentimiento del usuario antes de mostrar anuncios personalizados.',
    s2a_p2: 'Los usuarios pueden elegir:',
    s2a_li1: 'Anuncios personalizados',
    s2a_li2: 'Anuncios no personalizados',
    s2a_li3: 'O rechazar el consentimiento cuando corresponda',
    s2a_p3: 'El comportamiento de publicación de anuncios respeta las decisiones de consentimiento del usuario.',
    s2b_title: 'b) Anuncios no personalizados',
    s2b_p1: 'Si no se otorga el consentimiento, los anuncios aún pueden mostrarse de manera no personalizada, de acuerdo con las políticas de Google.',
    s3_title: '3. Créditos, uso gratuito y funciones Premium',
    s3_p1: 'La Aplicación ofrece un uso gratuito limitado a través de un sistema basado en créditos.',
    s3_p2: 'Los créditos gratuitos pueden renovarse automáticamente después de un período de espera definido.',
    s3_p3: 'Las funciones premium opcionales pueden estar disponibles mediante compras dentro de la aplicación.',
    s3_p4: 'Ver anuncios nunca es obligatorio para acceder a la funcionalidad principal.',
    s4_title: '4. Compartición de datos',
    s4_p1: 'No vendemos, intercambiamos ni alquilamos datos de usuarios a terceros.',
    s4_p2: 'Los datos limitados pueden compartirse con proveedores de servicios de confianza estrictamente para:',
    s4_li1: 'Analítica',
    s4_li2: 'Publicidad',
    s4_li3: 'Monitoreo del rendimiento de la aplicación',
    s4_p3: 'Todos estos proveedores cumplen con las normativas de protección de datos aplicables.',
    s5_title: '5. Privacidad de los niños',
    s5_p1: 'Nuestra Aplicación no está dirigida a niños menores de 13 años.',
    s5_p2: 'No recopilamos deliberadamente información personal de niños. Si cree que un niño ha proporcionado datos personales a través de la Aplicación, contáctenos para que podamos eliminar la información.',
    s6_title: '6. Seguridad de los datos',
    s6_p1: 'Tomamos medidas razonables para proteger los datos de los usuarios contra el acceso no autorizado, la alteración o la divulgación.',
    s6_p2: 'Sin embargo, ningún método de transmisión o almacenamiento electrónico es 100 % seguro.',
    s7_title: '7. Servicios de terceros',
    s7_p1: 'La Aplicación puede utilizar servicios de terceros que tienen sus propias políticas de privacidad, incluyendo pero no limitándose a:',
    s7_li1: 'Google AdMob',
    s7_li2: 'Google Analytics for Firebase',
    s7_p2: 'Recomendamos revisar las políticas de privacidad de estos proveedores para obtener más información.',
    s8_title: '8. Sus derechos',
    s8_p1: 'Dependiendo de su ubicación, puede tener derecho a:',
    s8_li1: 'Acceder a sus datos',
    s8_li2: 'Solicitar la eliminación de sus datos',
    s8_li3: 'Retirar el consentimiento para publicidad personalizada',
    s8_p2: 'Las solicitudes pueden realizarse utilizando la información de contacto a continuación.',
    s9_title: '9. Cambios en esta política',
    s9_p1: 'Podemos actualizar esta Política de Privacidad de vez en cuando.',
    s9_p2: 'Cualquier cambio se publicará en esta página con una fecha de revisión actualizada.',
    s10_title: '10. Contáctenos',
    s10_p1: 'Si tiene alguna pregunta o inquietud sobre esta Política de Privacidad, puede contactarnos en:',
    s10_p2: 'Correo electrónico:',
    footer_brand: 'Liga & Creador de Torneos',
    footer_by: 'por',
  },
  it: {
    _title: 'Informativa sulla Privacy – Lega & Creatore di Tornei',
    _description: 'Informativa sulla Privacy per l\'applicazione mobile Lega & Creatore di Tornei di Sogepps.',
    nav_back: '← Creatore di Tornei',
    nav_privacy: 'Informativa sulla Privacy',
    nav_delete: 'Elimina account',
    page_title: '🔐 Informativa sulla Privacy',
    page_date: 'Ultimo aggiornamento: 28 febbraio 2026',
    intro: 'Questa Informativa sulla Privacy spiega come raccogliamo, utilizziamo e proteggiamo le vostre informazioni quando utilizzate la nostra applicazione mobile <strong>Lega &amp; Creatore di Tornei</strong> ("App"). Utilizzando l\'App, accettate la raccolta e l\'utilizzo delle informazioni in conformità con questa politica.',
    s1_title: '1. Informazioni che raccogliamo',
    s1a_title: 'a) Informazioni personali',
    s1a_p1: 'Non richiediamo agli utenti di fornire informazioni di identificazione personale come nome, indirizzo o numero di telefono.',
    s1a_p2: 'Se effettuate l\'accesso tramite servizi di terze parti (come Google Sign-In), i dati di autenticazione vengono gestiti in modo sicuro dal rispettivo fornitore e non sono memorizzati direttamente da noi.',
    s1b_title: 'b) Dati di utilizzo',
    s1b_p1: 'Possiamo raccogliere automaticamente informazioni limitate e non personali, tra cui:',
    s1b_li1: 'Statistiche di utilizzo dell\'app',
    s1b_li2: 'Tipo di dispositivo e sistema operativo',
    s1b_li3: 'Rapporti sugli arresti anomali e dati sulle prestazioni',
    s1b_p2: 'Questi dati vengono utilizzati esclusivamente per migliorare la stabilità dell\'app e l\'esperienza utente.',
    s1c_title: 'c) Dati pubblicitari',
    s1c_p1: 'La nostra App può visualizzare annunci pubblicitari forniti da Google AdMob.',
    s1c_p2: 'AdMob può raccogliere ed elaborare informazioni come:',
    s1c_li1: 'Identificatori del dispositivo',
    s1c_li2: 'Posizione approssimativa (livello nazionale)',
    s1c_li3: 'Dati di interazione con gli annunci',
    s1c_p3: 'Queste informazioni vengono utilizzate per visualizzare gli annunci e misurare le loro prestazioni.',
    s2_title: '2. Pubblicità e consenso',
    s2a_title: 'a) Consenso dell\'utente',
    s2a_p1: 'Per gli utenti situati in regioni in cui è richiesto il consenso (come lo Spazio Economico Europeo, il Regno Unito e la Svizzera), richiediamo il consenso dell\'utente prima di mostrare annunci personalizzati.',
    s2a_p2: 'Gli utenti possono scegliere:',
    s2a_li1: 'Annunci personalizzati',
    s2a_li2: 'Annunci non personalizzati',
    s2a_li3: 'O rifiutare il consenso ove applicabile',
    s2a_p3: 'Il comportamento di pubblicazione degli annunci rispetta le scelte di consenso dell\'utente.',
    s2b_title: 'b) Annunci non personalizzati',
    s2b_p1: 'Se il consenso non viene fornito, gli annunci possono comunque essere mostrati in modo non personalizzato, in conformità con le politiche di Google.',
    s3_title: '3. Crediti, utilizzo gratuito e funzionalità Premium',
    s3_p1: 'L\'App offre un utilizzo gratuito limitato attraverso un sistema basato su crediti.',
    s3_p2: 'I crediti gratuiti possono rinnovarsi automaticamente dopo un periodo di attesa definito.',
    s3_p3: 'Le funzionalità premium opzionali possono essere disponibili tramite acquisti in-app.',
    s3_p4: 'Guardare pubblicità non è mai obbligatorio per accedere alle funzionalità principali.',
    s4_title: '4. Condivisione dei dati',
    s4_p1: 'Non vendiamo, scambiamo o affittiamo i dati degli utenti a terze parti.',
    s4_p2: 'Dati limitati possono essere condivisi con fornitori di servizi fidati esclusivamente per:',
    s4_li1: 'Analisi',
    s4_li2: 'Pubblicità',
    s4_li3: 'Monitoraggio delle prestazioni dell\'app',
    s4_p3: 'Tutti questi fornitori rispettano le normative applicabili sulla protezione dei dati.',
    s5_title: '5. Privacy dei minori',
    s5_p1: 'La nostra App non è destinata a bambini di età inferiore ai 13 anni.',
    s5_p2: 'Non raccogliamo consapevolmente informazioni personali dai minori. Se ritenete che un bambino abbia fornito dati personali tramite l\'App, contattateci in modo che possiamo rimuovere le informazioni.',
    s6_title: '6. Sicurezza dei dati',
    s6_p1: 'Adottiamo misure ragionevoli per proteggere i dati degli utenti da accesso non autorizzato, alterazione o divulgazione.',
    s6_p2: 'Tuttavia, nessun metodo di trasmissione o archiviazione elettronica è sicuro al 100%.',
    s7_title: '7. Servizi di terze parti',
    s7_p1: 'L\'App può utilizzare servizi di terze parti che hanno le proprie informative sulla privacy, tra cui:',
    s7_li1: 'Google AdMob',
    s7_li2: 'Google Analytics for Firebase',
    s7_p2: 'Vi consigliamo di consultare le informative sulla privacy di questi fornitori per maggiori informazioni.',
    s8_title: '8. I vostri diritti',
    s8_p1: 'A seconda della vostra posizione, potreste avere il diritto di:',
    s8_li1: 'Accedere ai vostri dati',
    s8_li2: 'Richiedere la cancellazione dei vostri dati',
    s8_li3: 'Revocare il consenso per la pubblicità personalizzata',
    s8_p2: 'Le richieste possono essere effettuate utilizzando le informazioni di contatto riportate di seguito.',
    s9_title: '9. Modifiche a questa politica',
    s9_p1: 'Possiamo aggiornare questa Informativa sulla Privacy di tanto in tanto.',
    s9_p2: 'Eventuali modifiche saranno pubblicate su questa pagina con una data di revisione aggiornata.',
    s10_title: '10. Contattaci',
    s10_p1: 'Se avete domande o dubbi su questa Informativa sulla Privacy, potete contattarci a:',
    s10_p2: 'E-mail:',
    footer_brand: 'Lega & Creatore di Tornei',
    footer_by: 'di',
  },
  pt: {
    _title: 'Política de Privacidade – Liga & Criador de Torneios',
    _description: 'Política de Privacidade do aplicativo móvel Liga & Criador de Torneios da Sogepps.',
    nav_back: '← Criador de Torneios',
    nav_privacy: 'Política de Privacidade',
    nav_delete: 'Excluir conta',
    page_title: '🔐 Política de Privacidade',
    page_date: 'Última atualização: 28 de fevereiro de 2026',
    intro: 'Esta Política de Privacidade explica como coletamos, usamos e protegemos suas informações quando você usa nosso aplicativo móvel <strong>Liga &amp; Criador de Torneios</strong> ("Aplicativo"). Ao usar o Aplicativo, você concorda com a coleta e o uso de informações de acordo com esta política.',
    s1_title: '1. Informações que coletamos',
    s1a_title: 'a) Informações pessoais',
    s1a_p1: 'Não exigimos que os usuários forneçam informações de identificação pessoal, como nome, endereço ou número de telefone.',
    s1a_p2: 'Se você fizer login usando serviços de terceiros (como o Login do Google), os dados de autenticação são tratados de forma segura pelo respectivo provedor e não são armazenados diretamente por nós.',
    s1b_title: 'b) Dados de uso',
    s1b_p1: 'Podemos coletar automaticamente informações limitadas e não pessoais, incluindo:',
    s1b_li1: 'Estatísticas de uso do aplicativo',
    s1b_li2: 'Tipo de dispositivo e sistema operacional',
    s1b_li3: 'Relatórios de falhas e dados de desempenho',
    s1b_p2: 'Esses dados são usados exclusivamente para melhorar a estabilidade do aplicativo e a experiência do usuário.',
    s1c_title: 'c) Dados de publicidade',
    s1c_p1: 'Nosso Aplicativo pode exibir anúncios fornecidos pelo Google AdMob.',
    s1c_p2: 'O AdMob pode coletar e processar informações como:',
    s1c_li1: 'Identificadores de dispositivo',
    s1c_li2: 'Localização aproximada (nível de país)',
    s1c_li3: 'Dados de interação com anúncios',
    s1c_p3: 'Essas informações são usadas para exibir anúncios e medir seu desempenho.',
    s2_title: '2. Anúncios e consentimento',
    s2a_title: 'a) Consentimento do usuário',
    s2a_p1: 'Para usuários localizados em regiões onde o consentimento é necessário (como o Espaço Econômico Europeu, o Reino Unido e a Suíça), solicitamos o consentimento do usuário antes de exibir anúncios personalizados.',
    s2a_p2: 'Os usuários podem escolher:',
    s2a_li1: 'Anúncios personalizados',
    s2a_li2: 'Anúncios não personalizados',
    s2a_li3: 'Ou recusar o consentimento quando aplicável',
    s2a_p3: 'O comportamento de exibição de anúncios respeita as escolhas de consentimento do usuário.',
    s2b_title: 'b) Anúncios não personalizados',
    s2b_p1: 'Se o consentimento não for fornecido, os anúncios ainda podem ser exibidos de forma não personalizada, de acordo com as políticas do Google.',
    s3_title: '3. Créditos, uso gratuito e recursos Premium',
    s3_p1: 'O Aplicativo oferece uso gratuito limitado por meio de um sistema baseado em créditos.',
    s3_p2: 'Os créditos gratuitos podem ser renovados automaticamente após um período de espera definido.',
    s3_p3: 'Recursos premium opcionais podem estar disponíveis por meio de compras no aplicativo.',
    s3_p4: 'Assistir a anúncios nunca é obrigatório para acessar a funcionalidade principal.',
    s4_title: '4. Compartilhamento de dados',
    s4_p1: 'Não vendemos, trocamos ou alugamos dados de usuários a terceiros.',
    s4_p2: 'Dados limitados podem ser compartilhados com provedores de serviços confiáveis estritamente para:',
    s4_li1: 'Análise',
    s4_li2: 'Publicidade',
    s4_li3: 'Monitoramento de desempenho do aplicativo',
    s4_p3: 'Todos esses provedores cumprem as regulamentações de proteção de dados aplicáveis.',
    s5_title: '5. Privacidade das crianças',
    s5_p1: 'Nosso Aplicativo não é destinado a crianças menores de 13 anos.',
    s5_p2: 'Não coletamos intencionalmente informações pessoais de crianças. Se você acredita que uma criança forneceu dados pessoais por meio do Aplicativo, entre em contato conosco para que possamos remover as informações.',
    s6_title: '6. Segurança dos dados',
    s6_p1: 'Tomamos medidas razoáveis para proteger os dados dos usuários contra acesso não autorizado, alteração ou divulgação.',
    s6_p2: 'No entanto, nenhum método de transmissão ou armazenamento eletrônico é 100% seguro.',
    s7_title: '7. Serviços de terceiros',
    s7_p1: 'O Aplicativo pode usar serviços de terceiros que possuem suas próprias políticas de privacidade, incluindo, mas não se limitando a:',
    s7_li1: 'Google AdMob',
    s7_li2: 'Google Analytics for Firebase',
    s7_p2: 'Recomendamos a revisão das políticas de privacidade desses provedores para mais informações.',
    s8_title: '8. Seus direitos',
    s8_p1: 'Dependendo da sua localização, você pode ter o direito de:',
    s8_li1: 'Acessar seus dados',
    s8_li2: 'Solicitar a exclusão de seus dados',
    s8_li3: 'Retirar o consentimento para publicidade personalizada',
    s8_p2: 'As solicitações podem ser feitas usando as informações de contato abaixo.',
    s9_title: '9. Alterações nesta política',
    s9_p1: 'Podemos atualizar esta Política de Privacidade periodicamente.',
    s9_p2: 'Quaisquer alterações serão publicadas nesta página com uma data de revisão atualizada.',
    s10_title: '10. Fale conosco',
    s10_p1: 'Se você tiver dúvidas ou preocupações sobre esta Política de Privacidade, pode entrar em contato conosco em:',
    s10_p2: 'E-mail:',
    footer_brand: 'Liga & Criador de Torneios',
    footer_by: 'por',
  },
  nl: {
    _title: 'Privacybeleid – Competitie & Toernooi Maker',
    _description: 'Privacybeleid voor de mobiele applicatie Competitie & Toernooi Maker van Sogepps.',
    nav_back: '← Toernooi Maker',
    nav_privacy: 'Privacybeleid',
    nav_delete: 'Account verwijderen',
    page_title: '🔐 Privacybeleid',
    page_date: 'Laatst bijgewerkt: 28 februari 2026',
    intro: 'Dit Privacybeleid legt uit hoe wij uw informatie verzamelen, gebruiken en beschermen wanneer u onze mobiele applicatie <strong>Competitie &amp; Toernooi Maker</strong> ("App") gebruikt. Door de App te gebruiken, gaat u akkoord met het verzamelen en gebruiken van informatie in overeenstemming met dit beleid.',
    s1_title: '1. Informatie die wij verzamelen',
    s1a_title: 'a) Persoonlijke informatie',
    s1a_p1: 'Wij vereisen niet dat gebruikers persoonlijk identificeerbare informatie verstrekken zoals naam, adres of telefoonnummer.',
    s1a_p2: 'Als u inlogt via diensten van derden (zoals Google Sign-In), worden de authenticatiegegevens veilig verwerkt door de betreffende aanbieder en worden niet direct door ons opgeslagen.',
    s1b_title: 'b) Gebruiksgegevens',
    s1b_p1: 'Wij kunnen automatisch beperkte, niet-persoonlijke informatie verzamelen, waaronder:',
    s1b_li1: 'Gebruiksstatistieken van de app',
    s1b_li2: 'Apparaattype en besturingssysteem',
    s1b_li3: 'Crashrapporten en prestatiegegevens',
    s1b_p2: 'Deze gegevens worden uitsluitend gebruikt om de stabiliteit van de app en de gebruikerservaring te verbeteren.',
    s1c_title: 'c) Advertentiegegevens',
    s1c_p1: 'Onze App kan advertenties tonen die worden aangeboden door Google AdMob.',
    s1c_p2: 'AdMob kan informatie verzamelen en verwerken zoals:',
    s1c_li1: 'Apparaat-identificatoren',
    s1c_li2: 'Geschatte locatie (op landniveau)',
    s1c_li3: 'Advertentie-interactiegegevens',
    s1c_p3: 'Deze informatie wordt gebruikt om advertenties weer te geven en hun prestaties te meten.',
    s2_title: '2. Advertenties & toestemming',
    s2a_title: 'a) Toestemming van de gebruiker',
    s2a_p1: 'Voor gebruikers in regio\'s waar toestemming vereist is (zoals de Europese Economische Ruimte, het Verenigd Koninkrijk en Zwitserland), vragen wij toestemming van de gebruiker voordat gepersonaliseerde advertenties worden weergegeven.',
    s2a_p2: 'Gebruikers kunnen kiezen:',
    s2a_li1: 'Gepersonaliseerde advertenties',
    s2a_li2: 'Niet-gepersonaliseerde advertenties',
    s2a_li3: 'Of toestemming weigeren indien van toepassing',
    s2a_p3: 'Het gedrag van advertentieweergave respecteert de toestemmingskeuzes van de gebruiker.',
    s2b_title: 'b) Niet-gepersonaliseerde advertenties',
    s2b_p1: 'Als er geen toestemming wordt gegeven, kunnen advertenties nog steeds op een niet-gepersonaliseerde manier worden weergegeven, in overeenstemming met het beleid van Google.',
    s3_title: '3. Credits, gratis gebruik & Premium-functies',
    s3_p1: 'De App biedt beperkt gratis gebruik via een op credits gebaseerd systeem.',
    s3_p2: 'Gratis credits kunnen automatisch worden vernieuwd na een vastgestelde wachtperiode.',
    s3_p3: 'Optionele premium-functies kunnen beschikbaar zijn via in-app-aankopen.',
    s3_p4: 'Het bekijken van advertenties is nooit verplicht om toegang te krijgen tot de kernfunctionaliteit.',
    s4_title: '4. Gegevensdeling',
    s4_p1: 'Wij verkopen, verhandelen of verhuren gebruikersgegevens niet aan derden.',
    s4_p2: 'Beperkte gegevens kunnen worden gedeeld met vertrouwde dienstverleners uitsluitend voor:',
    s4_li1: 'Analyse',
    s4_li2: 'Advertenties',
    s4_li3: 'Monitoring van app-prestaties',
    s4_p3: 'Al deze aanbieders voldoen aan de toepasselijke wetgeving inzake gegevensbescherming.',
    s5_title: '5. Privacy van kinderen',
    s5_p1: 'Onze App is niet bedoeld voor kinderen onder de 13 jaar.',
    s5_p2: 'Wij verzamelen niet bewust persoonlijke informatie van kinderen. Als u van mening bent dat een kind persoonlijke gegevens heeft verstrekt via de App, neem dan contact met ons op zodat wij de informatie kunnen verwijderen.',
    s6_title: '6. Gegevensbeveiliging',
    s6_p1: 'Wij nemen redelijke maatregelen om gebruikersgegevens te beschermen tegen ongeautoriseerde toegang, wijziging of openbaarmaking.',
    s6_p2: 'Echter, geen enkele methode van elektronische overdracht of opslag is 100% veilig.',
    s7_title: '7. Diensten van derden',
    s7_p1: 'De App kan diensten van derden gebruiken die hun eigen privacybeleid hebben, waaronder maar niet beperkt tot:',
    s7_li1: 'Google AdMob',
    s7_li2: 'Google Analytics for Firebase',
    s7_p2: 'Wij raden aan het privacybeleid van deze aanbieders te raadplegen voor meer informatie.',
    s8_title: '8. Uw rechten',
    s8_p1: 'Afhankelijk van uw locatie heeft u mogelijk het recht om:',
    s8_li1: 'Toegang te krijgen tot uw gegevens',
    s8_li2: 'Verwijdering van uw gegevens te verzoeken',
    s8_li3: 'Toestemming voor gepersonaliseerde advertenties in te trekken',
    s8_p2: 'Verzoeken kunnen worden ingediend via de onderstaande contactgegevens.',
    s9_title: '9. Wijzigingen in dit beleid',
    s9_p1: 'Wij kunnen dit Privacybeleid van tijd tot tijd bijwerken.',
    s9_p2: 'Eventuele wijzigingen worden op deze pagina gepubliceerd met een bijgewerkte herzieningsdatum.',
    s10_title: '10. Neem contact met ons op',
    s10_p1: 'Als u vragen of zorgen heeft over dit Privacybeleid, kunt u contact met ons opnemen via:',
    s10_p2: 'E-mail:',
    footer_brand: 'Competitie & Toernooi Maker',
    footer_by: 'door',
  },
  ru: {
    _title: 'Политика конфиденциальности – Лига и Создатель Турниров',
    _description: 'Политика конфиденциальности мобильного приложения Лига и Создатель Турниров от Sogepps.',
    nav_back: '← Создатель Турниров',
    nav_privacy: 'Политика конфиденциальности',
    nav_delete: 'Удалить аккаунт',
    page_title: '🔐 Политика конфиденциальности',
    page_date: 'Последнее обновление: 28 февраля 2026 г.',
    intro: 'Настоящая Политика конфиденциальности объясняет, как мы собираем, используем и защищаем вашу информацию при использовании нашего мобильного приложения <strong>Лига &amp; Создатель Турниров</strong> («Приложение»). Используя Приложение, вы соглашаетесь на сбор и использование информации в соответствии с настоящей политикой.',
    s1_title: '1. Информация, которую мы собираем',
    s1a_title: 'а) Персональная информация',
    s1a_p1: 'Мы не требуем от пользователей предоставления персональных данных, таких как имя, адрес или номер телефона.',
    s1a_p2: 'Если вы входите в систему через сторонние сервисы (например, Google Sign-In), данные аутентификации обрабатываются безопасно соответствующим поставщиком и не хранятся нами напрямую.',
    s1b_title: 'б) Данные об использовании',
    s1b_p1: 'Мы можем автоматически собирать ограниченную неперсональную информацию, включая:',
    s1b_li1: 'Статистику использования приложения',
    s1b_li2: 'Тип устройства и операционную систему',
    s1b_li3: 'Отчёты о сбоях и данные о производительности',
    s1b_p2: 'Эти данные используются исключительно для улучшения стабильности приложения и пользовательского опыта.',
    s1c_title: 'в) Рекламные данные',
    s1c_p1: 'Наше Приложение может отображать рекламу, предоставленную Google AdMob.',
    s1c_p2: 'AdMob может собирать и обрабатывать такую информацию, как:',
    s1c_li1: 'Идентификаторы устройства',
    s1c_li2: 'Приблизительное местоположение (на уровне страны)',
    s1c_li3: 'Данные о взаимодействии с рекламой',
    s1c_p3: 'Эта информация используется для показа рекламы и измерения её эффективности.',
    s2_title: '2. Реклама и согласие',
    s2a_title: 'а) Согласие пользователя',
    s2a_p1: 'Для пользователей, находящихся в регионах, где требуется согласие (таких как Европейская экономическая зона, Великобритания и Швейцария), мы запрашиваем согласие пользователя перед показом персонализированной рекламы.',
    s2a_p2: 'Пользователи могут выбрать:',
    s2a_li1: 'Персонализированную рекламу',
    s2a_li2: 'Неперсонализированную рекламу',
    s2a_li3: 'Или отказаться от согласия, если это применимо',
    s2a_p3: 'Поведение показа рекламы учитывает выбор пользователя в отношении согласия.',
    s2b_title: 'б) Неперсонализированная реклама',
    s2b_p1: 'Если согласие не предоставлено, реклама может по-прежнему показываться в неперсонализированном виде в соответствии с политикой Google.',
    s3_title: '3. Кредиты, бесплатное использование и Premium-функции',
    s3_p1: 'Приложение предлагает ограниченное бесплатное использование через систему кредитов.',
    s3_p2: 'Бесплатные кредиты могут автоматически обновляться после установленного периода ожидания.',
    s3_p3: 'Дополнительные Premium-функции могут быть доступны через покупки в приложении.',
    s3_p4: 'Просмотр рекламы никогда не является обязательным для доступа к основной функциональности.',
    s4_title: '4. Обмен данными',
    s4_p1: 'Мы не продаём, не обмениваем и не сдаём в аренду данные пользователей третьим лицам.',
    s4_p2: 'Ограниченные данные могут быть переданы доверенным поставщикам услуг исключительно для:',
    s4_li1: 'Аналитики',
    s4_li2: 'Рекламы',
    s4_li3: 'Мониторинга производительности приложения',
    s4_p3: 'Все такие поставщики соблюдают применимые нормы защиты данных.',
    s5_title: '5. Конфиденциальность детей',
    s5_p1: 'Наше Приложение не предназначено для детей младше 13 лет.',
    s5_p2: 'Мы сознательно не собираем персональную информацию от детей. Если вы считаете, что ребёнок предоставил персональные данные через Приложение, пожалуйста, свяжитесь с нами, чтобы мы могли удалить эту информацию.',
    s6_title: '6. Безопасность данных',
    s6_p1: 'Мы принимаем разумные меры для защиты данных пользователей от несанкционированного доступа, изменения или раскрытия.',
    s6_p2: 'Однако ни один метод электронной передачи или хранения не является на 100% безопасным.',
    s7_title: '7. Сторонние сервисы',
    s7_p1: 'Приложение может использовать сторонние сервисы, имеющие собственные политики конфиденциальности, включая, но не ограничиваясь:',
    s7_li1: 'Google AdMob',
    s7_li2: 'Google Analytics for Firebase',
    s7_p2: 'Мы рекомендуем ознакомиться с политиками конфиденциальности этих поставщиков для получения дополнительной информации.',
    s8_title: '8. Ваши права',
    s8_p1: 'В зависимости от вашего местоположения вы можете иметь право на:',
    s8_li1: 'Доступ к вашим данным',
    s8_li2: 'Запрос на удаление ваших данных',
    s8_li3: 'Отзыв согласия на персонализированную рекламу',
    s8_p2: 'Запросы можно отправить, используя контактную информацию ниже.',
    s9_title: '9. Изменения в настоящей политике',
    s9_p1: 'Мы можем время от времени обновлять настоящую Политику конфиденциальности.',
    s9_p2: 'Любые изменения будут опубликованы на этой странице с обновлённой датой пересмотра.',
    s10_title: '10. Свяжитесь с нами',
    s10_p1: 'Если у вас есть вопросы или опасения относительно настоящей Политики конфиденциальности, вы можете связаться с нами по адресу:',
    s10_p2: 'Электронная почта:',
    footer_brand: 'Лига и Создатель Турниров',
    footer_by: 'от',
  },
  ja: {
    _title: 'プライバシーポリシー – リーグ＆トーナメントメーカー',
    _description: 'Sogeppsによるリーグ＆トーナメントメーカーモバイルアプリケーションのプライバシーポリシー。',
    nav_back: '← トーナメントメーカー',
    nav_privacy: 'プライバシーポリシー',
    nav_delete: 'アカウント削除',
    page_title: '🔐 プライバシーポリシー',
    page_date: '最終更新日：2026年2月28日',
    intro: 'このプライバシーポリシーは、モバイルアプリケーション<strong>リーグ &amp; トーナメントメーカー</strong>（「アプリ」）をご利用いただく際に、お客様の情報をどのように収集、使用、保護するかについて説明します。アプリを使用することにより、このポリシーに従った情報の収集と使用に同意したものとみなされます。',
    s1_title: '1. 収集する情報',
    s1a_title: 'a) 個人情報',
    s1a_p1: '氏名、住所、電話番号などの個人を特定できる情報の提供を求めることはありません。',
    s1a_p2: 'サードパーティサービス（Googleサインインなど）を使用してサインインする場合、認証データはそれぞれのプロバイダーによって安全に処理され、当社が直接保存することはありません。',
    s1b_title: 'b) 使用データ',
    s1b_p1: '以下を含む限定的な非個人情報を自動的に収集する場合があります：',
    s1b_li1: 'アプリの使用統計',
    s1b_li2: 'デバイスの種類とオペレーティングシステム',
    s1b_li3: 'クラッシュレポートとパフォーマンスデータ',
    s1b_p2: 'このデータは、アプリの安定性とユーザーエクスペリエンスの向上のためにのみ使用されます。',
    s1c_title: 'c) 広告データ',
    s1c_p1: '当アプリは、Google AdMobが提供する広告を表示する場合があります。',
    s1c_p2: 'AdMobは以下のような情報を収集・処理する場合があります：',
    s1c_li1: 'デバイス識別子',
    s1c_li2: 'おおよその位置情報（国レベル）',
    s1c_li3: '広告インタラクションデータ',
    s1c_p3: 'この情報は広告の表示とパフォーマンスの測定に使用されます。',
    s2_title: '2. 広告と同意',
    s2a_title: 'a) ユーザーの同意',
    s2a_p1: '同意が必要な地域（欧州経済領域、英国、スイスなど）のユーザーに対しては、パーソナライズド広告を表示する前にユーザーの同意を求めます。',
    s2a_p2: 'ユーザーは以下を選択できます：',
    s2a_li1: 'パーソナライズド広告',
    s2a_li2: '非パーソナライズド広告',
    s2a_li3: 'または該当する場合、同意を拒否',
    s2a_p3: '広告配信の動作はユーザーの同意の選択を尊重します。',
    s2b_title: 'b) 非パーソナライズド広告',
    s2b_p1: '同意が得られない場合でも、Googleのポリシーに従って非パーソナライズド形式で広告が表示される場合があります。',
    s3_title: '3. クレジット、無料利用とプレミアム機能',
    s3_p1: 'アプリはクレジットベースのシステムを通じて限定的な無料利用を提供しています。',
    s3_p2: '無料クレジットは定められた待機期間後に自動的に更新される場合があります。',
    s3_p3: 'オプションのプレミアム機能はアプリ内購入を通じて利用可能な場合があります。',
    s3_p4: 'コア機能へのアクセスに広告視聴が必須となることはありません。',
    s4_title: '4. データの共有',
    s4_p1: 'ユーザーデータを第三者に販売、交換、または貸与することはありません。',
    s4_p2: '限定的なデータは、以下の目的に限り、信頼できるサービスプロバイダーと共有される場合があります：',
    s4_li1: 'アナリティクス',
    s4_li2: '広告',
    s4_li3: 'アプリのパフォーマンス監視',
    s4_p3: 'これらのプロバイダーはすべて、適用されるデータ保護規制に準拠しています。',
    s5_title: '5. 子どものプライバシー',
    s5_p1: '当アプリは13歳未満の子どもを対象としていません。',
    s5_p2: '子どもから意図的に個人情報を収集することはありません。子どもがアプリを通じて個人データを提供したと思われる場合は、情報を削除できるようお問い合わせください。',
    s6_title: '6. データセキュリティ',
    s6_p1: 'ユーザーデータを不正アクセス、改ざん、または開示から保護するための合理的な対策を講じています。',
    s6_p2: 'ただし、電子的な送信や保存の方法で100%安全なものはありません。',
    s7_title: '7. サードパーティサービス',
    s7_p1: 'アプリは独自のプライバシーポリシーを持つサードパーティサービスを使用する場合があります。これには以下が含まれますが、これらに限定されません：',
    s7_li1: 'Google AdMob',
    s7_li2: 'Google Analytics for Firebase',
    s7_p2: '詳細については、これらのプロバイダーのプライバシーポリシーを確認することをお勧めします。',
    s8_title: '8. お客様の権利',
    s8_p1: 'お住まいの地域によっては、以下の権利を有する場合があります：',
    s8_li1: 'データへのアクセス',
    s8_li2: 'データの削除を要求',
    s8_li3: 'パーソナライズド広告への同意の撤回',
    s8_p2: 'リクエストは以下の連絡先情報を使用して行うことができます。',
    s9_title: '9. このポリシーの変更',
    s9_p1: '本プライバシーポリシーは随時更新される場合があります。',
    s9_p2: '変更がある場合は、更新された改訂日とともにこのページに掲載されます。',
    s10_title: '10. お問い合わせ',
    s10_p1: 'このプライバシーポリシーについてご質問やご懸念がある場合は、以下までお問い合わせください：',
    s10_p2: 'メール：',
    footer_brand: 'リーグ＆トーナメントメーカー',
    footer_by: '提供',
  },
  ko: {
    _title: '개인정보 처리방침 – 리그 & 토너먼트 메이커',
    _description: 'Sogepps의 리그 & 토너먼트 메이커 모바일 애플리케이션 개인정보 처리방침.',
    nav_back: '← 토너먼트 메이커',
    nav_privacy: '개인정보 처리방침',
    nav_delete: '계정 삭제',
    page_title: '🔐 개인정보 처리방침',
    page_date: '최종 업데이트: 2026년 2월 28일',
    intro: '본 개인정보 처리방침은 모바일 애플리케이션 <strong>리그 &amp; 토너먼트 메이커</strong>("앱")를 사용할 때 귀하의 정보를 어떻게 수집, 사용 및 보호하는지 설명합니다. 앱을 사용함으로써 귀하는 본 방침에 따른 정보 수집 및 사용에 동의하게 됩니다.',
    s1_title: '1. 수집하는 정보',
    s1a_title: 'a) 개인 정보',
    s1a_p1: '이름, 주소 또는 전화번호와 같은 개인 식별 정보를 제공하도록 요구하지 않습니다.',
    s1a_p2: '타사 서비스(예: Google 로그인)를 사용하여 로그인하는 경우, 인증 데이터는 해당 제공업체에 의해 안전하게 처리되며 당사가 직접 저장하지 않습니다.',
    s1b_title: 'b) 사용 데이터',
    s1b_p1: '다음을 포함한 제한적인 비개인 정보를 자동으로 수집할 수 있습니다:',
    s1b_li1: '앱 사용 통계',
    s1b_li2: '기기 유형 및 운영 체제',
    s1b_li3: '충돌 보고서 및 성능 데이터',
    s1b_p2: '이 데이터는 앱 안정성과 사용자 경험을 개선하기 위해서만 사용됩니다.',
    s1c_title: 'c) 광고 데이터',
    s1c_p1: '본 앱은 Google AdMob에서 제공하는 광고를 표시할 수 있습니다.',
    s1c_p2: 'AdMob은 다음과 같은 정보를 수집하고 처리할 수 있습니다:',
    s1c_li1: '기기 식별자',
    s1c_li2: '대략적인 위치(국가 수준)',
    s1c_li3: '광고 상호 작용 데이터',
    s1c_p3: '이 정보는 광고를 표시하고 성과를 측정하는 데 사용됩니다.',
    s2_title: '2. 광고 및 동의',
    s2a_title: 'a) 사용자 동의',
    s2a_p1: '동의가 필요한 지역(유럽 경제 지역, 영국, 스위스 등)에 있는 사용자의 경우, 맞춤형 광고를 표시하기 전에 사용자 동의를 요청합니다.',
    s2a_p2: '사용자는 다음을 선택할 수 있습니다:',
    s2a_li1: '맞춤형 광고',
    s2a_li2: '비맞춤형 광고',
    s2a_li3: '또는 해당되는 경우 동의 거부',
    s2a_p3: '광고 게재 동작은 사용자의 동의 선택을 존중합니다.',
    s2b_title: 'b) 비맞춤형 광고',
    s2b_p1: '동의가 제공되지 않은 경우에도 Google 정책에 따라 비맞춤형 방식으로 광고가 표시될 수 있습니다.',
    s3_title: '3. 크레딧, 무료 사용 및 프리미엄 기능',
    s3_p1: '앱은 크레딧 기반 시스템을 통해 제한된 무료 사용을 제공합니다.',
    s3_p2: '무료 크레딧은 정해진 대기 기간 후 자동으로 갱신될 수 있습니다.',
    s3_p3: '선택적 프리미엄 기능은 인앱 구매를 통해 이용할 수 있습니다.',
    s3_p4: '핵심 기능에 접근하기 위해 광고 시청이 필수적이지 않습니다.',
    s4_title: '4. 데이터 공유',
    s4_p1: '사용자 데이터를 제3자에게 판매, 거래 또는 임대하지 않습니다.',
    s4_p2: '제한된 데이터는 다음 목적으로만 신뢰할 수 있는 서비스 제공업체와 공유될 수 있습니다:',
    s4_li1: '분석',
    s4_li2: '광고',
    s4_li3: '앱 성능 모니터링',
    s4_p3: '이러한 모든 제공업체는 적용 가능한 데이터 보호 규정을 준수합니다.',
    s5_title: '5. 아동 개인정보 보호',
    s5_p1: '본 앱은 13세 미만 아동을 대상으로 하지 않습니다.',
    s5_p2: '아동으로부터 의도적으로 개인 정보를 수집하지 않습니다. 아동이 앱을 통해 개인 데이터를 제공했다고 생각되시면, 해당 정보를 삭제할 수 있도록 저희에게 연락해 주십시오.',
    s6_title: '6. 데이터 보안',
    s6_p1: '무단 접근, 변경 또는 공개로부터 사용자 데이터를 보호하기 위한 합리적인 조치를 취합니다.',
    s6_p2: '그러나 전자 전송이나 저장 방법 중 100% 안전한 것은 없습니다.',
    s7_title: '7. 타사 서비스',
    s7_p1: '앱은 다음을 포함하되 이에 국한되지 않는 자체 개인정보 처리방침을 가진 타사 서비스를 사용할 수 있습니다:',
    s7_li1: 'Google AdMob',
    s7_li2: 'Google Analytics for Firebase',
    s7_p2: '자세한 내용은 이러한 제공업체의 개인정보 처리방침을 검토하시기 바랍니다.',
    s8_title: '8. 귀하의 권리',
    s8_p1: '귀하의 위치에 따라 다음과 같은 권리가 있을 수 있습니다:',
    s8_li1: '데이터에 대한 접근',
    s8_li2: '데이터 삭제 요청',
    s8_li3: '맞춤형 광고에 대한 동의 철회',
    s8_p2: '요청은 아래 연락처 정보를 사용하여 할 수 있습니다.',
    s9_title: '9. 본 방침의 변경',
    s9_p1: '본 개인정보 처리방침은 수시로 업데이트될 수 있습니다.',
    s9_p2: '변경 사항은 업데이트된 개정 날짜와 함께 이 페이지에 게시됩니다.',
    s10_title: '10. 문의하기',
    s10_p1: '본 개인정보 처리방침에 대한 질문이나 우려 사항이 있으시면 다음으로 문의하실 수 있습니다:',
    s10_p2: '이메일:',
    footer_brand: '리그 & 토너먼트 메이커',
    footer_by: '제작',
  },
  ar: {
    _title: 'سياسة الخصوصية – صانع الدوري والبطولات',
    _description: 'سياسة الخصوصية لتطبيق صانع الدوري والبطولات من Sogepps.',
    nav_back: '← صانع البطولات',
    nav_privacy: 'سياسة الخصوصية',
    nav_delete: 'حذف الحساب',
    page_title: '🔐 سياسة الخصوصية',
    page_date: 'آخر تحديث: 28 فبراير 2026',
    intro: 'توضح سياسة الخصوصية هذه كيفية جمع واستخدام وحماية معلوماتك عند استخدام تطبيقنا المحمول <strong>صانع الدوري &amp; والبطولات</strong> ("التطبيق"). باستخدام التطبيق، فإنك توافق على جمع واستخدام المعلومات وفقاً لهذه السياسة.',
    s1_title: '1. المعلومات التي نجمعها',
    s1a_title: 'أ) المعلومات الشخصية',
    s1a_p1: 'لا نطلب من المستخدمين تقديم معلومات تعريف شخصية مثل الاسم أو العنوان أو رقم الهاتف.',
    s1a_p2: 'إذا قمت بتسجيل الدخول باستخدام خدمات الطرف الثالث (مثل تسجيل الدخول بحساب Google)، تتم معالجة بيانات المصادقة بشكل آمن من قبل المزود المعني ولا يتم تخزينها مباشرة من قبلنا.',
    s1b_title: 'ب) بيانات الاستخدام',
    s1b_p1: 'قد نجمع تلقائياً معلومات محدودة وغير شخصية، بما في ذلك:',
    s1b_li1: 'إحصائيات استخدام التطبيق',
    s1b_li2: 'نوع الجهاز ونظام التشغيل',
    s1b_li3: 'تقارير الأعطال وبيانات الأداء',
    s1b_p2: 'تُستخدم هذه البيانات فقط لتحسين استقرار التطبيق وتجربة المستخدم.',
    s1c_title: 'ج) بيانات الإعلانات',
    s1c_p1: 'قد يعرض تطبيقنا إعلانات مقدمة من Google AdMob.',
    s1c_p2: 'قد يجمع AdMob ويعالج معلومات مثل:',
    s1c_li1: 'معرّفات الجهاز',
    s1c_li2: 'الموقع التقريبي (على مستوى الدولة)',
    s1c_li3: 'بيانات التفاعل مع الإعلانات',
    s1c_p3: 'تُستخدم هذه المعلومات لعرض الإعلانات وقياس أدائها.',
    s2_title: '2. الإعلانات والموافقة',
    s2a_title: 'أ) موافقة المستخدم',
    s2a_p1: 'بالنسبة للمستخدمين الموجودين في مناطق تتطلب الموافقة (مثل المنطقة الاقتصادية الأوروبية والمملكة المتحدة وسويسرا)، نطلب موافقة المستخدم قبل عرض إعلانات مخصصة.',
    s2a_p2: 'يمكن للمستخدمين اختيار:',
    s2a_li1: 'إعلانات مخصصة',
    s2a_li2: 'إعلانات غير مخصصة',
    s2a_li3: 'أو رفض الموافقة حيثما ينطبق ذلك',
    s2a_p3: 'يحترم سلوك عرض الإعلانات خيارات موافقة المستخدم.',
    s2b_title: 'ب) الإعلانات غير المخصصة',
    s2b_p1: 'إذا لم يتم تقديم الموافقة، فقد يتم عرض الإعلانات بطريقة غير مخصصة، وفقاً لسياسات Google.',
    s3_title: '3. الرصيد والاستخدام المجاني والميزات المميزة',
    s3_p1: 'يوفر التطبيق استخداماً مجانياً محدوداً من خلال نظام قائم على الرصيد.',
    s3_p2: 'قد يتم تجديد الرصيد المجاني تلقائياً بعد فترة انتظار محددة.',
    s3_p3: 'قد تتوفر ميزات مميزة اختيارية من خلال عمليات الشراء داخل التطبيق.',
    s3_p4: 'مشاهدة الإعلانات ليست إلزامية أبداً للوصول إلى الوظائف الأساسية.',
    s4_title: '4. مشاركة البيانات',
    s4_p1: 'لا نبيع أو نتاجر أو نؤجر بيانات المستخدمين لأطراف ثالثة.',
    s4_p2: 'قد تتم مشاركة بيانات محدودة مع مقدمي خدمات موثوقين حصرياً لأغراض:',
    s4_li1: 'التحليلات',
    s4_li2: 'الإعلانات',
    s4_li3: 'مراقبة أداء التطبيق',
    s4_p3: 'يلتزم جميع هؤلاء المزودين بلوائح حماية البيانات المعمول بها.',
    s5_title: '5. خصوصية الأطفال',
    s5_p1: 'تطبيقنا غير مخصص للأطفال دون سن 13 عاماً.',
    s5_p2: 'لا نجمع عن قصد معلومات شخصية من الأطفال. إذا كنت تعتقد أن طفلاً قد قدم بيانات شخصية عبر التطبيق، يرجى الاتصال بنا حتى نتمكن من إزالة المعلومات.',
    s6_title: '6. أمان البيانات',
    s6_p1: 'نتخذ تدابير معقولة لحماية بيانات المستخدمين من الوصول غير المصرح به أو التعديل أو الإفصاح.',
    s6_p2: 'ومع ذلك، لا توجد طريقة للنقل أو التخزين الإلكتروني آمنة بنسبة 100%.',
    s7_title: '7. خدمات الطرف الثالث',
    s7_p1: 'قد يستخدم التطبيق خدمات طرف ثالث لها سياسات خصوصية خاصة بها، بما في ذلك على سبيل المثال لا الحصر:',
    s7_li1: 'Google AdMob',
    s7_li2: 'Google Analytics for Firebase',
    s7_p2: 'نوصي بمراجعة سياسات الخصوصية لهؤلاء المزودين للحصول على مزيد من المعلومات.',
    s8_title: '8. حقوقك',
    s8_p1: 'حسب موقعك، قد يكون لديك الحق في:',
    s8_li1: 'الوصول إلى بياناتك',
    s8_li2: 'طلب حذف بياناتك',
    s8_li3: 'سحب الموافقة على الإعلانات المخصصة',
    s8_p2: 'يمكن تقديم الطلبات باستخدام معلومات الاتصال أدناه.',
    s9_title: '9. التغييرات على هذه السياسة',
    s9_p1: 'قد نقوم بتحديث سياسة الخصوصية هذه من وقت لآخر.',
    s9_p2: 'سيتم نشر أي تغييرات على هذه الصفحة مع تاريخ مراجعة محدث.',
    s10_title: '10. اتصل بنا',
    s10_p1: 'إذا كانت لديك أي أسئلة أو مخاوف بشأن سياسة الخصوصية هذه، يمكنك التواصل معنا على:',
    s10_p2: 'البريد الإلكتروني:',
    footer_brand: 'صانع الدوري والبطولات',
    footer_by: 'بواسطة',
  },
  hi: {
    _title: 'गोपनीयता नीति – लीग और टूर्नामेंट मेकर',
    _description: 'Sogepps द्वारा लीग और टूर्नामेंट मेकर मोबाइल एप्लिकेशन के लिए गोपनीयता नीति।',
    nav_back: '← टूर्नामेंट मेकर',
    nav_privacy: 'गोपनीयता नीति',
    nav_delete: 'खाता हटाएं',
    page_title: '🔐 गोपनीयता नीति',
    page_date: 'अंतिम अपडेट: 28 फरवरी 2026',
    intro: 'यह गोपनीयता नीति बताती है कि जब आप हमारे मोबाइल एप्लिकेशन <strong>लीग &amp; टूर्नामेंट मेकर</strong> ("ऐप") का उपयोग करते हैं तो हम आपकी जानकारी कैसे एकत्र, उपयोग और सुरक्षित करते हैं। ऐप का उपयोग करके, आप इस नीति के अनुसार जानकारी के संग्रह और उपयोग के लिए सहमत होते हैं।',
    s1_title: '1. हम जो जानकारी एकत्र करते हैं',
    s1a_title: 'क) व्यक्तिगत जानकारी',
    s1a_p1: 'हम उपयोगकर्ताओं से नाम, पता या फोन नंबर जैसी व्यक्तिगत पहचान योग्य जानकारी प्रदान करने की आवश्यकता नहीं रखते।',
    s1a_p2: 'यदि आप तृतीय-पक्ष सेवाओं (जैसे Google साइन-इन) का उपयोग करके साइन इन करते हैं, तो प्रमाणीकरण डेटा संबंधित प्रदाता द्वारा सुरक्षित रूप से संभाला जाता है और हमारे द्वारा सीधे संग्रहीत नहीं किया जाता।',
    s1b_title: 'ख) उपयोग डेटा',
    s1b_p1: 'हम स्वचालित रूप से सीमित, गैर-व्यक्तिगत जानकारी एकत्र कर सकते हैं, जिसमें शामिल हैं:',
    s1b_li1: 'ऐप उपयोग आंकड़े',
    s1b_li2: 'डिवाइस प्रकार और ऑपरेटिंग सिस्टम',
    s1b_li3: 'क्रैश रिपोर्ट और प्रदर्शन डेटा',
    s1b_p2: 'यह डेटा केवल ऐप स्थिरता और उपयोगकर्ता अनुभव को बेहतर बनाने के लिए उपयोग किया जाता है।',
    s1c_title: 'ग) विज्ञापन डेटा',
    s1c_p1: 'हमारा ऐप Google AdMob द्वारा प्रदान किए गए विज्ञापन प्रदर्शित कर सकता है।',
    s1c_p2: 'AdMob निम्नलिखित जैसी जानकारी एकत्र और संसाधित कर सकता है:',
    s1c_li1: 'डिवाइस पहचानकर्ता',
    s1c_li2: 'अनुमानित स्थान (देश-स्तर)',
    s1c_li3: 'विज्ञापन इंटरैक्शन डेटा',
    s1c_p3: 'यह जानकारी विज्ञापन प्रदर्शित करने और उनके प्रदर्शन को मापने के लिए उपयोग की जाती है।',
    s2_title: '2. विज्ञापन और सहमति',
    s2a_title: 'क) उपयोगकर्ता सहमति',
    s2a_p1: 'उन क्षेत्रों में स्थित उपयोगकर्ताओं के लिए जहां सहमति आवश्यक है (जैसे यूरोपीय आर्थिक क्षेत्र, यूनाइटेड किंगडम और स्विट्जरलैंड), हम व्यक्तिगत विज्ञापन दिखाने से पहले उपयोगकर्ता की सहमति का अनुरोध करते हैं।',
    s2a_p2: 'उपयोगकर्ता चुन सकते हैं:',
    s2a_li1: 'व्यक्तिगत विज्ञापन',
    s2a_li2: 'गैर-व्यक्तिगत विज्ञापन',
    s2a_li3: 'या जहां लागू हो, सहमति अस्वीकार करना',
    s2a_p3: 'विज्ञापन प्रदर्शन व्यवहार उपयोगकर्ता की सहमति विकल्पों का सम्मान करता है।',
    s2b_title: 'ख) गैर-व्यक्तिगत विज्ञापन',
    s2b_p1: 'यदि सहमति प्रदान नहीं की जाती है, तो विज्ञापन Google की नीतियों के अनुसार गैर-व्यक्तिगत तरीके से दिखाए जा सकते हैं।',
    s3_title: '3. क्रेडिट, मुफ्त उपयोग और प्रीमियम सुविधाएं',
    s3_p1: 'ऐप क्रेडिट-आधारित प्रणाली के माध्यम से सीमित मुफ्त उपयोग प्रदान करता है।',
    s3_p2: 'मुफ्त क्रेडिट एक निर्धारित प्रतीक्षा अवधि के बाद स्वचालित रूप से नवीनीकृत हो सकते हैं।',
    s3_p3: 'वैकल्पिक प्रीमियम सुविधाएं इन-ऐप खरीदारी के माध्यम से उपलब्ध हो सकती हैं।',
    s3_p4: 'मूल कार्यक्षमता तक पहुंचने के लिए विज्ञापन देखना कभी अनिवार्य नहीं है।',
    s4_title: '4. डेटा साझाकरण',
    s4_p1: 'हम उपयोगकर्ता डेटा को तृतीय पक्षों को बेचते, व्यापार करते या किराए पर नहीं देते।',
    s4_p2: 'सीमित डेटा विश्वसनीय सेवा प्रदाताओं के साथ केवल निम्नलिखित के लिए साझा किया जा सकता है:',
    s4_li1: 'विश्लेषण',
    s4_li2: 'विज्ञापन',
    s4_li3: 'ऐप प्रदर्शन निगरानी',
    s4_p3: 'सभी ऐसे प्रदाता लागू डेटा सुरक्षा विनियमों का अनुपालन करते हैं।',
    s5_title: '5. बच्चों की गोपनीयता',
    s5_p1: 'हमारा ऐप 13 वर्ष से कम आयु के बच्चों के लिए नहीं है।',
    s5_p2: 'हम जानबूझकर बच्चों से व्यक्तिगत जानकारी एकत्र नहीं करते। यदि आपको लगता है कि किसी बच्चे ने ऐप के माध्यम से व्यक्तिगत डेटा प्रदान किया है, तो कृपया हमसे संपर्क करें ताकि हम जानकारी हटा सकें।',
    s6_title: '6. डेटा सुरक्षा',
    s6_p1: 'हम उपयोगकर्ता डेटा को अनधिकृत पहुंच, परिवर्तन या प्रकटीकरण से बचाने के लिए उचित उपाय करते हैं।',
    s6_p2: 'हालांकि, इलेक्ट्रॉनिक संचरण या भंडारण की कोई भी विधि 100% सुरक्षित नहीं है।',
    s7_title: '7. तृतीय-पक्ष सेवाएं',
    s7_p1: 'ऐप तृतीय-पक्ष सेवाओं का उपयोग कर सकता है जिनकी अपनी गोपनीयता नीतियां हैं, जिसमें शामिल हैं लेकिन इन तक सीमित नहीं हैं:',
    s7_li1: 'Google AdMob',
    s7_li2: 'Google Analytics for Firebase',
    s7_p2: 'अधिक जानकारी के लिए हम इन प्रदाताओं की गोपनीयता नीतियों की समीक्षा करने की अनुशंसा करते हैं।',
    s8_title: '8. आपके अधिकार',
    s8_p1: 'आपके स्थान के आधार पर, आपके पास निम्नलिखित अधिकार हो सकते हैं:',
    s8_li1: 'अपने डेटा तक पहुंच',
    s8_li2: 'अपने डेटा को हटाने का अनुरोध',
    s8_li3: 'व्यक्तिगत विज्ञापन के लिए सहमति वापस लेना',
    s8_p2: 'अनुरोध नीचे दी गई संपर्क जानकारी का उपयोग करके किए जा सकते हैं।',
    s9_title: '9. इस नीति में परिवर्तन',
    s9_p1: 'हम समय-समय पर इस गोपनीयता नीति को अपडेट कर सकते हैं।',
    s9_p2: 'कोई भी परिवर्तन अपडेट की गई संशोधन तिथि के साथ इस पृष्ठ पर पोस्ट किया जाएगा।',
    s10_title: '10. हमसे संपर्क करें',
    s10_p1: 'यदि इस गोपनीयता नीति के बारे में आपके कोई प्रश्न या चिंताएं हैं, तो आप हमसे यहां संपर्क कर सकते हैं:',
    s10_p2: 'ईमेल:',
    footer_brand: 'लीग और टूर्नामेंट मेकर',
    footer_by: 'द्वारा',
  },
  id: {
    _title: 'Kebijakan Privasi – Liga & Pembuat Turnamen',
    _description: 'Kebijakan Privasi untuk aplikasi mobile Liga & Pembuat Turnamen oleh Sogepps.',
    nav_back: '← Pembuat Turnamen',
    nav_privacy: 'Kebijakan Privasi',
    nav_delete: 'Hapus Akun',
    page_title: '🔐 Kebijakan Privasi',
    page_date: 'Terakhir diperbarui: 28 Februari 2026',
    intro: 'Kebijakan Privasi ini menjelaskan bagaimana kami mengumpulkan, menggunakan, dan melindungi informasi Anda saat menggunakan aplikasi mobile kami <strong>Liga &amp; Pembuat Turnamen</strong> ("Aplikasi"). Dengan menggunakan Aplikasi, Anda menyetujui pengumpulan dan penggunaan informasi sesuai dengan kebijakan ini.',
    s1_title: '1. Informasi yang Kami Kumpulkan',
    s1a_title: 'a) Informasi Pribadi',
    s1a_p1: 'Kami tidak mengharuskan pengguna memberikan informasi identitas pribadi seperti nama, alamat, atau nomor telepon.',
    s1a_p2: 'Jika Anda masuk menggunakan layanan pihak ketiga (seperti Google Sign-In), data autentikasi ditangani secara aman oleh penyedia terkait dan tidak disimpan langsung oleh kami.',
    s1b_title: 'b) Data Penggunaan',
    s1b_p1: 'Kami dapat secara otomatis mengumpulkan informasi terbatas dan non-pribadi, termasuk:',
    s1b_li1: 'Statistik penggunaan aplikasi',
    s1b_li2: 'Jenis perangkat dan sistem operasi',
    s1b_li3: 'Laporan kerusakan dan data kinerja',
    s1b_p2: 'Data ini digunakan semata-mata untuk meningkatkan stabilitas aplikasi dan pengalaman pengguna.',
    s1c_title: 'c) Data Iklan',
    s1c_p1: 'Aplikasi kami dapat menampilkan iklan yang disediakan oleh Google AdMob.',
    s1c_p2: 'AdMob dapat mengumpulkan dan memproses informasi seperti:',
    s1c_li1: 'Pengidentifikasi perangkat',
    s1c_li2: 'Lokasi perkiraan (tingkat negara)',
    s1c_li3: 'Data interaksi iklan',
    s1c_p3: 'Informasi ini digunakan untuk menampilkan iklan dan mengukur kinerjanya.',
    s2_title: '2. Iklan & Persetujuan',
    s2a_title: 'a) Persetujuan Pengguna',
    s2a_p1: 'Untuk pengguna yang berada di wilayah yang memerlukan persetujuan (seperti Wilayah Ekonomi Eropa, Inggris Raya, dan Swiss), kami meminta persetujuan pengguna sebelum menampilkan iklan yang dipersonalisasi.',
    s2a_p2: 'Pengguna dapat memilih:',
    s2a_li1: 'Iklan yang dipersonalisasi',
    s2a_li2: 'Iklan yang tidak dipersonalisasi',
    s2a_li3: 'Atau menolak persetujuan jika berlaku',
    s2a_p3: 'Perilaku penayangan iklan menghormati pilihan persetujuan pengguna.',
    s2b_title: 'b) Iklan Tidak Dipersonalisasi',
    s2b_p1: 'Jika persetujuan tidak diberikan, iklan masih dapat ditampilkan secara tidak dipersonalisasi, sesuai dengan kebijakan Google.',
    s3_title: '3. Kredit, Penggunaan Gratis & Fitur Premium',
    s3_p1: 'Aplikasi menawarkan penggunaan gratis terbatas melalui sistem berbasis kredit.',
    s3_p2: 'Kredit gratis dapat diperbarui secara otomatis setelah periode tunggu yang ditentukan.',
    s3_p3: 'Fitur premium opsional mungkin tersedia melalui pembelian dalam aplikasi.',
    s3_p4: 'Menonton iklan tidak pernah wajib untuk mengakses fungsionalitas inti.',
    s4_title: '4. Berbagi Data',
    s4_p1: 'Kami tidak menjual, memperdagangkan, atau menyewakan data pengguna kepada pihak ketiga.',
    s4_p2: 'Data terbatas dapat dibagikan dengan penyedia layanan tepercaya secara ketat untuk:',
    s4_li1: 'Analitik',
    s4_li2: 'Periklanan',
    s4_li3: 'Pemantauan kinerja aplikasi',
    s4_p3: 'Semua penyedia tersebut mematuhi peraturan perlindungan data yang berlaku.',
    s5_title: '5. Privasi Anak',
    s5_p1: 'Aplikasi kami tidak ditujukan untuk anak-anak di bawah usia 13 tahun.',
    s5_p2: 'Kami tidak secara sengaja mengumpulkan informasi pribadi dari anak-anak. Jika Anda percaya bahwa seorang anak telah memberikan data pribadi melalui Aplikasi, silakan hubungi kami agar kami dapat menghapus informasi tersebut.',
    s6_title: '6. Keamanan Data',
    s6_p1: 'Kami mengambil langkah-langkah yang wajar untuk melindungi data pengguna dari akses, perubahan, atau pengungkapan yang tidak sah.',
    s6_p2: 'Namun, tidak ada metode transmisi atau penyimpanan elektronik yang 100% aman.',
    s7_title: '7. Layanan Pihak Ketiga',
    s7_p1: 'Aplikasi dapat menggunakan layanan pihak ketiga yang memiliki kebijakan privasi mereka sendiri, termasuk tetapi tidak terbatas pada:',
    s7_li1: 'Google AdMob',
    s7_li2: 'Google Analytics for Firebase',
    s7_p2: 'Kami menyarankan untuk meninjau kebijakan privasi penyedia ini untuk informasi lebih lanjut.',
    s8_title: '8. Hak Anda',
    s8_p1: 'Tergantung pada lokasi Anda, Anda mungkin memiliki hak untuk:',
    s8_li1: 'Mengakses data Anda',
    s8_li2: 'Meminta penghapusan data Anda',
    s8_li3: 'Menarik persetujuan untuk iklan yang dipersonalisasi',
    s8_p2: 'Permintaan dapat diajukan menggunakan informasi kontak di bawah ini.',
    s9_title: '9. Perubahan pada Kebijakan Ini',
    s9_p1: 'Kami dapat memperbarui Kebijakan Privasi ini dari waktu ke waktu.',
    s9_p2: 'Setiap perubahan akan diposting di halaman ini dengan tanggal revisi yang diperbarui.',
    s10_title: '10. Hubungi Kami',
    s10_p1: 'Jika Anda memiliki pertanyaan atau kekhawatiran tentang Kebijakan Privasi ini, Anda dapat menghubungi kami di:',
    s10_p2: 'Email:',
    footer_brand: 'Liga & Pembuat Turnamen',
    footer_by: 'oleh',
  },
  pl: {
    _title: 'Polityka Prywatności – Liga i Kreator Turniejów',
    _description: 'Polityka Prywatności aplikacji mobilnej Liga i Kreator Turniejów firmy Sogepps.',
    nav_back: '← Kreator Turniejów',
    nav_privacy: 'Polityka Prywatności',
    nav_delete: 'Usuń konto',
    page_title: '🔐 Polityka Prywatności',
    page_date: 'Ostatnia aktualizacja: 28 lutego 2026',
    intro: 'Niniejsza Polityka Prywatności wyjaśnia, w jaki sposób zbieramy, wykorzystujemy i chronimy Twoje informacje podczas korzystania z naszej aplikacji mobilnej <strong>Liga &amp; Kreator Turniejów</strong> („Aplikacja"). Korzystając z Aplikacji, wyrażasz zgodę na gromadzenie i wykorzystywanie informacji zgodnie z niniejszą polityką.',
    s1_title: '1. Informacje, które zbieramy',
    s1a_title: 'a) Dane osobowe',
    s1a_p1: 'Nie wymagamy od użytkowników podawania danych osobowych, takich jak imię i nazwisko, adres czy numer telefonu.',
    s1a_p2: 'Jeśli logujesz się za pomocą usług stron trzecich (takich jak Logowanie przez Google), dane uwierzytelniające są bezpiecznie przetwarzane przez odpowiedniego dostawcę i nie są przechowywane bezpośrednio przez nas.',
    s1b_title: 'b) Dane o użytkowaniu',
    s1b_p1: 'Możemy automatycznie zbierać ograniczone, nieosobowe informacje, w tym:',
    s1b_li1: 'Statystyki użytkowania aplikacji',
    s1b_li2: 'Typ urządzenia i system operacyjny',
    s1b_li3: 'Raporty o awariach i dane wydajnościowe',
    s1b_p2: 'Te dane są wykorzystywane wyłącznie w celu poprawy stabilności aplikacji i doświadczenia użytkownika.',
    s1c_title: 'c) Dane reklamowe',
    s1c_p1: 'Nasza Aplikacja może wyświetlać reklamy dostarczane przez Google AdMob.',
    s1c_p2: 'AdMob może zbierać i przetwarzać informacje takie jak:',
    s1c_li1: 'Identyfikatory urządzenia',
    s1c_li2: 'Przybliżona lokalizacja (na poziomie kraju)',
    s1c_li3: 'Dane interakcji z reklamami',
    s1c_p3: 'Te informacje są wykorzystywane do wyświetlania reklam i mierzenia ich skuteczności.',
    s2_title: '2. Reklamy i zgoda',
    s2a_title: 'a) Zgoda użytkownika',
    s2a_p1: 'Dla użytkowników znajdujących się w regionach, w których wymagana jest zgoda (takich jak Europejski Obszar Gospodarczy, Wielka Brytania i Szwajcaria), prosimy o zgodę użytkownika przed wyświetleniem spersonalizowanych reklam.',
    s2a_p2: 'Użytkownicy mogą wybrać:',
    s2a_li1: 'Reklamy spersonalizowane',
    s2a_li2: 'Reklamy niespersonalizowane',
    s2a_li3: 'Lub odmówić zgody, jeśli dotyczy',
    s2a_p3: 'Zachowanie wyświetlania reklam respektuje wybory dotyczące zgody użytkownika.',
    s2b_title: 'b) Reklamy niespersonalizowane',
    s2b_p1: 'Jeśli zgoda nie zostanie udzielona, reklamy mogą nadal być wyświetlane w sposób niespersonalizowany, zgodnie z politykami Google.',
    s3_title: '3. Kredyty, darmowe korzystanie i funkcje Premium',
    s3_p1: 'Aplikacja oferuje ograniczone darmowe korzystanie poprzez system oparty na kredytach.',
    s3_p2: 'Darmowe kredyty mogą odnawiać się automatycznie po określonym czasie oczekiwania.',
    s3_p3: 'Opcjonalne funkcje premium mogą być dostępne za pośrednictwem zakupów w aplikacji.',
    s3_p4: 'Oglądanie reklam nigdy nie jest wymagane, aby uzyskać dostęp do podstawowej funkcjonalności.',
    s4_title: '4. Udostępnianie danych',
    s4_p1: 'Nie sprzedajemy, nie wymieniamy ani nie wynajmujemy danych użytkowników stronom trzecim.',
    s4_p2: 'Ograniczone dane mogą być udostępniane zaufanym dostawcom usług wyłącznie w celu:',
    s4_li1: 'Analityki',
    s4_li2: 'Reklamy',
    s4_li3: 'Monitorowania wydajności aplikacji',
    s4_p3: 'Wszyscy tacy dostawcy przestrzegają obowiązujących przepisów o ochronie danych.',
    s5_title: '5. Prywatność dzieci',
    s5_p1: 'Nasza Aplikacja nie jest przeznaczona dla dzieci poniżej 13. roku życia.',
    s5_p2: 'Nie zbieramy świadomie danych osobowych od dzieci. Jeśli uważasz, że dziecko udostępniło dane osobowe za pośrednictwem Aplikacji, skontaktuj się z nami, abyśmy mogli usunąć te informacje.',
    s6_title: '6. Bezpieczeństwo danych',
    s6_p1: 'Podejmujemy rozsądne środki w celu ochrony danych użytkowników przed nieautoryzowanym dostępem, zmianą lub ujawnieniem.',
    s6_p2: 'Jednakże żadna metoda transmisji elektronicznej ani przechowywania nie jest w 100% bezpieczna.',
    s7_title: '7. Usługi stron trzecich',
    s7_p1: 'Aplikacja może korzystać z usług stron trzecich, które mają własne polityki prywatności, w tym między innymi:',
    s7_li1: 'Google AdMob',
    s7_li2: 'Google Analytics for Firebase',
    s7_p2: 'Zalecamy zapoznanie się z politykami prywatności tych dostawców w celu uzyskania dalszych informacji.',
    s8_title: '8. Twoje prawa',
    s8_p1: 'W zależności od Twojej lokalizacji, możesz mieć prawo do:',
    s8_li1: 'Dostępu do swoich danych',
    s8_li2: 'Żądania usunięcia swoich danych',
    s8_li3: 'Wycofania zgody na spersonalizowaną reklamę',
    s8_p2: 'Wnioski można składać za pomocą poniższych danych kontaktowych.',
    s9_title: '9. Zmiany w niniejszej polityce',
    s9_p1: 'Możemy od czasu do czasu aktualizować niniejszą Politykę Prywatności.',
    s9_p2: 'Wszelkie zmiany zostaną opublikowane na tej stronie z zaktualizowaną datą rewizji.',
    s10_title: '10. Skontaktuj się z nami',
    s10_p1: 'Jeśli masz jakiekolwiek pytania lub wątpliwości dotyczące niniejszej Polityki Prywatności, możesz się z nami skontaktować pod adresem:',
    s10_p2: 'E-mail:',
    footer_brand: 'Liga i Kreator Turniejów',
    footer_by: 'od',
  },
};
