var LANDING_TRANSLATIONS = {
  en: {
    _title: 'Sogepps – Mobile Apps & Software',
    _description: 'Sogepps builds mobile applications that simplify everyday tasks. Explore our apps.',
    nav_about: 'About',
    nav_apps: 'Apps',
    nav_contact: 'Contact',
    hero_badge: '⚡ Building useful mobile apps',
    hero_title: 'We build apps that<br /><span>simplify your life</span>',
    hero_desc: 'Sogepps creates intuitive mobile applications designed to solve real-world problems. Simple, reliable, and built with care.',
    hero_cta: 'Explore Our Apps ↓',
    about_label: '◆ About Us',
    about_title: 'Who We Are',
    about_desc: 'Sogepps is a software studio focused on mobile application development. We believe great software should be simple to use, reliable, and accessible to everyone. Our apps are designed with user experience as the top priority.',
    stat_apps: 'Published Apps',
    stat_fast: 'Fast & Reliable',
    stat_privacy: 'Privacy First',
    stat_languages: '16+ Languages',
    apps_label: '◆ Our Apps',
    apps_title: 'Applications',
    apps_desc: 'Explore our published mobile applications.',
    app_name: 'League & Tournament Maker',
    app_desc: 'Create leagues, knockout brackets, and round-robin tournaments in seconds. Track scores, view live standings, export results as PDF — all from your phone. Available on Android.',
    badge_sports: '⚽ Sports',
    badge_tournaments: '🏆 Tournaments',
    badge_standings: '📈 Standings',
    badge_brackets: '⚖ Brackets',
    app_view: 'View Details →',
    footer_brand: 'Sogepps',
    footer_desc: 'Building useful mobile applications. Simple, reliable, and privacy-focused.',
    footer_apps: 'Apps',
    footer_legal: 'Legal',
    footer_privacy: 'Privacy Policy',
    footer_delete: 'Delete Account',
    footer_contact: 'Contact',
    footer_rights: '© 2026 Sogepps. All rights reserved.',
  },
  tr: {
    _title: 'Sogepps – Mobil Uygulamalar ve Yazılım',
    _description: 'Sogepps, günlük işlerinizi kolaylaştıran mobil uygulamalar geliştiriyor.',
    nav_about: 'Hakkımızda',
    nav_apps: 'Uygulamalar',
    nav_contact: 'İletişim',
    hero_badge: '⚡ Kullanışlı mobil uygulamalar geliştiriyoruz',
    hero_title: 'Hayatınızı<br /><span>kolaylaştıran uygulamalar</span>',
    hero_desc: 'Sogepps, gerçek dünya sorunlarını çözmek için tasarlanmış, sezgisel mobil uygulamalar geliştiriyor. Basit, güvenilir ve özenle yapılmış.',
    hero_cta: 'Uygulamalarımızı Keşfet ↓',
    about_label: '◆ Hakkımızda',
    about_title: 'Biz Kimiz',
    about_desc: 'Sogepps, mobil uygulama geliştirmeye odaklanan bir yazılım stüdyosudur. Harika yazılımların kullanımı kolay, güvenilir ve herkes için erişilebilir olması gerektiğine inanıyoruz.',
    stat_apps: 'Yayınlanan Uygulama',
    stat_fast: 'Hızlı ve Güvenilir',
    stat_privacy: 'Gizlilik Öncelikli',
    stat_languages: '16+ Dil',
    apps_label: '◆ Uygulamalarımız',
    apps_title: 'Uygulamalar',
    apps_desc: 'Yayınlanan mobil uygulamalarımızı keşfedin.',
    app_name: 'Lig ve Turnuva Oluşturucu',
    app_desc: 'Saniyeler içinde lig, eleme tabloları ve çift devreli turnuvalar oluşturun. Skorları girin, canlı puan durumunu görüntüleyin, sonuçları PDF olarak dışa aktarın.',
    badge_sports: '⚽ Sporlar',
    badge_tournaments: '🏆 Turnuvalar',
    badge_standings: '📈 Puan Durumu',
    badge_brackets: '⚖ Tablolar',
    app_view: 'Detayları Gör →',
    footer_brand: 'Sogepps',
    footer_desc: 'Kullanışlı mobil uygulamalar geliştiriyoruz. Basit, güvenilir ve gizlilik odaklı.',
    footer_apps: 'Uygulamalar',
    footer_legal: 'Yasal',
    footer_privacy: 'Gizlilik Politikası',
    footer_delete: 'Hesap Sil',
    footer_contact: 'İletişim',
    footer_rights: '© 2026 Sogepps. Tüm hakları saklıdır.',
  },
  de: {
    _title: 'Sogepps – Mobile Apps & Software',
    _description: 'Sogepps entwickelt mobile Anwendungen, die den Alltag vereinfachen. Entdecken Sie unsere Apps.',
    nav_about: 'Über uns',
    nav_apps: 'Apps',
    nav_contact: 'Kontakt',
    hero_badge: '⚡ Wir entwickeln nützliche mobile Apps',
    hero_title: 'Wir entwickeln Apps, die<br /><span>Ihr Leben vereinfachen</span>',
    hero_desc: 'Sogepps erstellt intuitive mobile Anwendungen, die reale Probleme lösen. Einfach, zuverlässig und mit Sorgfalt entwickelt.',
    hero_cta: 'Unsere Apps entdecken ↓',
    about_label: '◆ Über uns',
    about_title: 'Wer wir sind',
    about_desc: 'Sogepps ist ein Softwarestudio mit Fokus auf mobile App-Entwicklung. Wir glauben, dass großartige Software einfach zu bedienen, zuverlässig und für jeden zugänglich sein sollte. Unsere Apps werden mit höchster Priorität auf Benutzererfahrung entwickelt.',
    stat_apps: 'Veröffentlichte Apps',
    stat_fast: 'Schnell & Zuverlässig',
    stat_privacy: 'Datenschutz zuerst',
    stat_languages: '16+ Sprachen',
    apps_label: '◆ Unsere Apps',
    apps_title: 'Anwendungen',
    apps_desc: 'Entdecken Sie unsere veröffentlichten mobilen Anwendungen.',
    app_name: 'Liga- & Turnier-Ersteller',
    app_desc: 'Erstellen Sie in Sekunden Ligen, K.O.-Turnierbäume und Rundenturniere. Verfolgen Sie Ergebnisse, sehen Sie Live-Tabellen und exportieren Sie Resultate als PDF — alles von Ihrem Handy. Verfügbar auf Android.',
    badge_sports: '⚽ Sport',
    badge_tournaments: '🏆 Turniere',
    badge_standings: '📈 Tabellen',
    badge_brackets: '⚖ Turnierbäume',
    app_view: 'Details ansehen →',
    footer_brand: 'Sogepps',
    footer_desc: 'Wir entwickeln nützliche mobile Anwendungen. Einfach, zuverlässig und datenschutzorientiert.',
    footer_apps: 'Apps',
    footer_legal: 'Rechtliches',
    footer_privacy: 'Datenschutzrichtlinie',
    footer_delete: 'Konto löschen',
    footer_contact: 'Kontakt',
    footer_rights: '© 2026 Sogepps. Alle Rechte vorbehalten.',
  },
  fr: {
    _title: 'Sogepps – Applications Mobiles & Logiciels',
    _description: 'Sogepps développe des applications mobiles qui simplifient le quotidien. Découvrez nos apps.',
    nav_about: 'À propos',
    nav_apps: 'Applications',
    nav_contact: 'Contact',
    hero_badge: '⚡ Nous créons des applications mobiles utiles',
    hero_title: 'Nous créons des apps qui<br /><span>simplifient votre vie</span>',
    hero_desc: 'Sogepps crée des applications mobiles intuitives conçues pour résoudre des problèmes concrets. Simples, fiables et développées avec soin.',
    hero_cta: 'Découvrir nos apps ↓',
    about_label: '◆ À propos',
    about_title: 'Qui sommes-nous',
    about_desc: 'Sogepps est un studio logiciel spécialisé dans le développement d\'applications mobiles. Nous croyons qu\'un excellent logiciel doit être simple à utiliser, fiable et accessible à tous. Nos apps sont conçues avec l\'expérience utilisateur comme priorité absolue.',
    stat_apps: 'Applications publiées',
    stat_fast: 'Rapide & Fiable',
    stat_privacy: 'Confidentialité d\'abord',
    stat_languages: '16+ Langues',
    apps_label: '◆ Nos Applications',
    apps_title: 'Applications',
    apps_desc: 'Découvrez nos applications mobiles publiées.',
    app_name: 'Créateur de Ligues & Tournois',
    app_desc: 'Créez des ligues, des tableaux à élimination directe et des tournois toutes rondes en quelques secondes. Suivez les scores, consultez les classements en direct, exportez les résultats en PDF — le tout depuis votre téléphone. Disponible sur Android.',
    badge_sports: '⚽ Sports',
    badge_tournaments: '🏆 Tournois',
    badge_standings: '📈 Classements',
    badge_brackets: '⚖ Tableaux',
    app_view: 'Voir les détails →',
    footer_brand: 'Sogepps',
    footer_desc: 'Nous développons des applications mobiles utiles. Simples, fiables et axées sur la confidentialité.',
    footer_apps: 'Applications',
    footer_legal: 'Mentions légales',
    footer_privacy: 'Politique de confidentialité',
    footer_delete: 'Supprimer le compte',
    footer_contact: 'Contact',
    footer_rights: '© 2026 Sogepps. Tous droits réservés.',
  },
  es: {
    _title: 'Sogepps – Aplicaciones Móviles y Software',
    _description: 'Sogepps desarrolla aplicaciones móviles que simplifican las tareas diarias. Explora nuestras apps.',
    nav_about: 'Nosotros',
    nav_apps: 'Aplicaciones',
    nav_contact: 'Contacto',
    hero_badge: '⚡ Creamos aplicaciones móviles útiles',
    hero_title: 'Creamos apps que<br /><span>simplifican tu vida</span>',
    hero_desc: 'Sogepps crea aplicaciones móviles intuitivas diseñadas para resolver problemas reales. Simples, confiables y desarrolladas con cuidado.',
    hero_cta: 'Explora nuestras apps ↓',
    about_label: '◆ Nosotros',
    about_title: 'Quiénes somos',
    about_desc: 'Sogepps es un estudio de software enfocado en el desarrollo de aplicaciones móviles. Creemos que un gran software debe ser fácil de usar, confiable y accesible para todos. Nuestras apps están diseñadas con la experiencia del usuario como máxima prioridad.',
    stat_apps: 'Apps publicadas',
    stat_fast: 'Rápido y Confiable',
    stat_privacy: 'Privacidad primero',
    stat_languages: '16+ Idiomas',
    apps_label: '◆ Nuestras Apps',
    apps_title: 'Aplicaciones',
    apps_desc: 'Explora nuestras aplicaciones móviles publicadas.',
    app_name: 'Creador de Ligas y Torneos',
    app_desc: 'Crea ligas, llaves de eliminación y torneos de todos contra todos en segundos. Registra puntuaciones, consulta clasificaciones en vivo, exporta resultados en PDF — todo desde tu teléfono. Disponible en Android.',
    badge_sports: '⚽ Deportes',
    badge_tournaments: '🏆 Torneos',
    badge_standings: '📈 Clasificaciones',
    badge_brackets: '⚖ Llaves',
    app_view: 'Ver detalles →',
    footer_brand: 'Sogepps',
    footer_desc: 'Desarrollamos aplicaciones móviles útiles. Simples, confiables y enfocadas en la privacidad.',
    footer_apps: 'Aplicaciones',
    footer_legal: 'Legal',
    footer_privacy: 'Política de privacidad',
    footer_delete: 'Eliminar cuenta',
    footer_contact: 'Contacto',
    footer_rights: '© 2026 Sogepps. Todos los derechos reservados.',
  },
  it: {
    _title: 'Sogepps – App Mobili e Software',
    _description: 'Sogepps sviluppa applicazioni mobili che semplificano le attività quotidiane. Scopri le nostre app.',
    nav_about: 'Chi siamo',
    nav_apps: 'App',
    nav_contact: 'Contatti',
    hero_badge: '⚡ Creiamo app mobili utili',
    hero_title: 'Creiamo app che<br /><span>semplificano la tua vita</span>',
    hero_desc: 'Sogepps crea applicazioni mobili intuitive progettate per risolvere problemi reali. Semplici, affidabili e sviluppate con cura.',
    hero_cta: 'Scopri le nostre app ↓',
    about_label: '◆ Chi siamo',
    about_title: 'Chi siamo',
    about_desc: 'Sogepps è uno studio software focalizzato sullo sviluppo di applicazioni mobili. Crediamo che un ottimo software debba essere semplice da usare, affidabile e accessibile a tutti. Le nostre app sono progettate con l\'esperienza utente come massima priorità.',
    stat_apps: 'App pubblicate',
    stat_fast: 'Veloce e Affidabile',
    stat_privacy: 'Privacy al primo posto',
    stat_languages: '16+ Lingue',
    apps_label: '◆ Le nostre App',
    apps_title: 'Applicazioni',
    apps_desc: 'Scopri le nostre applicazioni mobili pubblicate.',
    app_name: 'Creatore di Leghe e Tornei',
    app_desc: 'Crea leghe, tabelloni a eliminazione diretta e tornei all\'italiana in pochi secondi. Registra i punteggi, visualizza le classifiche in tempo reale, esporta i risultati in PDF — tutto dal tuo telefono. Disponibile su Android.',
    badge_sports: '⚽ Sport',
    badge_tournaments: '🏆 Tornei',
    badge_standings: '📈 Classifiche',
    badge_brackets: '⚖ Tabelloni',
    app_view: 'Vedi dettagli →',
    footer_brand: 'Sogepps',
    footer_desc: 'Sviluppiamo applicazioni mobili utili. Semplici, affidabili e orientate alla privacy.',
    footer_apps: 'App',
    footer_legal: 'Legale',
    footer_privacy: 'Informativa sulla privacy',
    footer_delete: 'Elimina account',
    footer_contact: 'Contatti',
    footer_rights: '© 2026 Sogepps. Tutti i diritti riservati.',
  },
  pt: {
    _title: 'Sogepps – Aplicativos Móveis e Software',
    _description: 'A Sogepps desenvolve aplicativos móveis que simplificam as tarefas do dia a dia. Conheça nossos apps.',
    nav_about: 'Sobre',
    nav_apps: 'Aplicativos',
    nav_contact: 'Contato',
    hero_badge: '⚡ Criamos aplicativos móveis úteis',
    hero_title: 'Criamos apps que<br /><span>simplificam sua vida</span>',
    hero_desc: 'A Sogepps cria aplicativos móveis intuitivos projetados para resolver problemas reais. Simples, confiáveis e desenvolvidos com cuidado.',
    hero_cta: 'Conheça nossos apps ↓',
    about_label: '◆ Sobre nós',
    about_title: 'Quem somos',
    about_desc: 'A Sogepps é um estúdio de software focado no desenvolvimento de aplicativos móveis. Acreditamos que um ótimo software deve ser fácil de usar, confiável e acessível a todos. Nossos apps são projetados com a experiência do usuário como prioridade máxima.',
    stat_apps: 'Apps publicados',
    stat_fast: 'Rápido e Confiável',
    stat_privacy: 'Privacidade em primeiro',
    stat_languages: '16+ Idiomas',
    apps_label: '◆ Nossos Apps',
    apps_title: 'Aplicativos',
    apps_desc: 'Conheça nossos aplicativos móveis publicados.',
    app_name: 'Criador de Ligas e Torneios',
    app_desc: 'Crie ligas, chaves eliminatórias e torneios todos contra todos em segundos. Registre placar, veja classificações ao vivo, exporte resultados em PDF — tudo pelo celular. Disponível no Android.',
    badge_sports: '⚽ Esportes',
    badge_tournaments: '🏆 Torneios',
    badge_standings: '📈 Classificações',
    badge_brackets: '⚖ Chaves',
    app_view: 'Ver detalhes →',
    footer_brand: 'Sogepps',
    footer_desc: 'Desenvolvemos aplicativos móveis úteis. Simples, confiáveis e focados em privacidade.',
    footer_apps: 'Aplicativos',
    footer_legal: 'Legal',
    footer_privacy: 'Política de Privacidade',
    footer_delete: 'Excluir conta',
    footer_contact: 'Contato',
    footer_rights: '© 2026 Sogepps. Todos os direitos reservados.',
  },
  nl: {
    _title: 'Sogepps – Mobiele Apps & Software',
    _description: 'Sogepps bouwt mobiele applicaties die dagelijkse taken vereenvoudigen. Ontdek onze apps.',
    nav_about: 'Over ons',
    nav_apps: 'Apps',
    nav_contact: 'Contact',
    hero_badge: '⚡ Wij bouwen nuttige mobiele apps',
    hero_title: 'Wij bouwen apps die<br /><span>je leven vereenvoudigen</span>',
    hero_desc: 'Sogepps creëert intuïtieve mobiele applicaties die zijn ontworpen om echte problemen op te lossen. Eenvoudig, betrouwbaar en met zorg gebouwd.',
    hero_cta: 'Ontdek onze apps ↓',
    about_label: '◆ Over ons',
    about_title: 'Wie wij zijn',
    about_desc: 'Sogepps is een softwarestudio gericht op de ontwikkeling van mobiele applicaties. Wij geloven dat geweldige software eenvoudig in gebruik, betrouwbaar en voor iedereen toegankelijk moet zijn. Onze apps zijn ontworpen met gebruikerservaring als topprioriteit.',
    stat_apps: 'Gepubliceerde apps',
    stat_fast: 'Snel & Betrouwbaar',
    stat_privacy: 'Privacy voorop',
    stat_languages: '16+ Talen',
    apps_label: '◆ Onze Apps',
    apps_title: 'Applicaties',
    apps_desc: 'Ontdek onze gepubliceerde mobiele applicaties.',
    app_name: 'Competitie- & Toernooimaker',
    app_desc: 'Maak in seconden competities, knock-outschema\'s en round-robintoernooien. Houd scores bij, bekijk live standen, exporteer resultaten als PDF — alles vanaf je telefoon. Beschikbaar op Android.',
    badge_sports: '⚽ Sport',
    badge_tournaments: '🏆 Toernooien',
    badge_standings: '📈 Standen',
    badge_brackets: '⚖ Schema\'s',
    app_view: 'Details bekijken →',
    footer_brand: 'Sogepps',
    footer_desc: 'Wij bouwen nuttige mobiele applicaties. Eenvoudig, betrouwbaar en privacygericht.',
    footer_apps: 'Apps',
    footer_legal: 'Juridisch',
    footer_privacy: 'Privacybeleid',
    footer_delete: 'Account verwijderen',
    footer_contact: 'Contact',
    footer_rights: '© 2026 Sogepps. Alle rechten voorbehouden.',
  },
  ru: {
    _title: 'Sogepps – Мобильные приложения и ПО',
    _description: 'Sogepps создаёт мобильные приложения, которые упрощают повседневные задачи. Ознакомьтесь с нашими приложениями.',
    nav_about: 'О нас',
    nav_apps: 'Приложения',
    nav_contact: 'Контакты',
    hero_badge: '⚡ Создаём полезные мобильные приложения',
    hero_title: 'Мы создаём приложения, которые<br /><span>упрощают вашу жизнь</span>',
    hero_desc: 'Sogepps разрабатывает интуитивно понятные мобильные приложения для решения реальных задач. Просто, надёжно и с заботой.',
    hero_cta: 'Наши приложения ↓',
    about_label: '◆ О нас',
    about_title: 'Кто мы',
    about_desc: 'Sogepps — это студия разработки мобильных приложений. Мы верим, что отличное ПО должно быть простым в использовании, надёжным и доступным каждому. Наши приложения разработаны с приоритетом на удобство пользователя.',
    stat_apps: 'Опубликовано приложений',
    stat_fast: 'Быстро и надёжно',
    stat_privacy: 'Приватность прежде всего',
    stat_languages: '16+ языков',
    apps_label: '◆ Наши приложения',
    apps_title: 'Приложения',
    apps_desc: 'Ознакомьтесь с нашими опубликованными мобильными приложениями.',
    app_name: 'Создатель лиг и турниров',
    app_desc: 'Создавайте лиги, сетки на выбывание и круговые турниры за секунды. Отслеживайте счёт, просматривайте турнирные таблицы в реальном времени, экспортируйте результаты в PDF — всё с телефона. Доступно на Android.',
    badge_sports: '⚽ Спорт',
    badge_tournaments: '🏆 Турниры',
    badge_standings: '📈 Таблицы',
    badge_brackets: '⚖ Сетки',
    app_view: 'Подробнее →',
    footer_brand: 'Sogepps',
    footer_desc: 'Создаём полезные мобильные приложения. Просто, надёжно и с заботой о приватности.',
    footer_apps: 'Приложения',
    footer_legal: 'Правовая информация',
    footer_privacy: 'Политика конфиденциальности',
    footer_delete: 'Удалить аккаунт',
    footer_contact: 'Контакты',
    footer_rights: '© 2026 Sogepps. Все права защищены.',
  },
  ja: {
    _title: 'Sogepps – モバイルアプリ＆ソフトウェア',
    _description: 'Sogeppsは日常のタスクを簡素化するモバイルアプリを開発しています。アプリをご覧ください。',
    nav_about: '私たちについて',
    nav_apps: 'アプリ',
    nav_contact: 'お問い合わせ',
    hero_badge: '⚡ 便利なモバイルアプリを開発',
    hero_title: '生活を<br /><span>シンプルにするアプリ</span>',
    hero_desc: 'Sogeppsは、実際の問題を解決するために設計された直感的なモバイルアプリケーションを開発しています。シンプルで信頼性が高く、丁寧に作られています。',
    hero_cta: 'アプリを見る ↓',
    about_label: '◆ 私たちについて',
    about_title: '私たちについて',
    about_desc: 'Sogeppsはモバイルアプリ開発に特化したソフトウェアスタジオです。優れたソフトウェアは使いやすく、信頼性が高く、誰でもアクセスできるべきだと考えています。私たちのアプリはユーザー体験を最優先に設計されています。',
    stat_apps: '公開済みアプリ',
    stat_fast: '高速＆信頼性',
    stat_privacy: 'プライバシー優先',
    stat_languages: '16以上の言語',
    apps_label: '◆ アプリ一覧',
    apps_title: 'アプリケーション',
    apps_desc: '公開中のモバイルアプリケーションをご覧ください。',
    app_name: 'リーグ＆トーナメントメーカー',
    app_desc: 'リーグ、トーナメント表、総当たり戦を数秒で作成。スコアを記録し、リアルタイムの順位表を確認し、結果をPDFでエクスポート — すべてスマホから。Androidで利用可能。',
    badge_sports: '⚽ スポーツ',
    badge_tournaments: '🏆 トーナメント',
    badge_standings: '📈 順位表',
    badge_brackets: '⚖ 対戦表',
    app_view: '詳細を見る →',
    footer_brand: 'Sogepps',
    footer_desc: '便利なモバイルアプリを開発しています。シンプル、信頼性、プライバシー重視。',
    footer_apps: 'アプリ',
    footer_legal: '法的情報',
    footer_privacy: 'プライバシーポリシー',
    footer_delete: 'アカウント削除',
    footer_contact: 'お問い合わせ',
    footer_rights: '© 2026 Sogepps. All rights reserved.',
  },
  ko: {
    _title: 'Sogepps – 모바일 앱 & 소프트웨어',
    _description: 'Sogepps는 일상 업무를 간소화하는 모바일 앱을 개발합니다. 우리의 앱을 살펴보세요.',
    nav_about: '소개',
    nav_apps: '앱',
    nav_contact: '문의',
    hero_badge: '⚡ 유용한 모바일 앱 개발',
    hero_title: '생활을<br /><span>간편하게 하는 앱</span>',
    hero_desc: 'Sogepps는 실제 문제를 해결하기 위해 설계된 직관적인 모바일 앱을 개발합니다. 간단하고, 안정적이며, 정성을 담아 만들었습니다.',
    hero_cta: '앱 살펴보기 ↓',
    about_label: '◆ 소개',
    about_title: '우리는 누구인가',
    about_desc: 'Sogepps는 모바일 앱 개발에 집중하는 소프트웨어 스튜디오입니다. 훌륭한 소프트웨어는 사용하기 쉽고, 안정적이며, 모든 사람이 접근할 수 있어야 한다고 믿습니다. 우리의 앱은 사용자 경험을 최우선으로 설계됩니다.',
    stat_apps: '출시된 앱',
    stat_fast: '빠르고 안정적',
    stat_privacy: '개인정보 보호 우선',
    stat_languages: '16개 이상의 언어',
    apps_label: '◆ 우리의 앱',
    apps_title: '애플리케이션',
    apps_desc: '출시된 모바일 앱을 살펴보세요.',
    app_name: '리그 & 토너먼트 메이커',
    app_desc: '몇 초 만에 리그, 토너먼트 대진표, 라운드 로빈 토너먼트를 만드세요. 점수를 기록하고, 실시간 순위를 확인하고, 결과를 PDF로 내보내세요 — 모두 휴대폰에서. Android에서 이용 가능.',
    badge_sports: '⚽ 스포츠',
    badge_tournaments: '🏆 토너먼트',
    badge_standings: '📈 순위',
    badge_brackets: '⚖ 대진표',
    app_view: '자세히 보기 →',
    footer_brand: 'Sogepps',
    footer_desc: '유용한 모바일 앱을 개발합니다. 간단하고, 안정적이며, 개인정보 보호에 중점을 둡니다.',
    footer_apps: '앱',
    footer_legal: '법적 고지',
    footer_privacy: '개인정보 처리방침',
    footer_delete: '계정 삭제',
    footer_contact: '문의',
    footer_rights: '© 2026 Sogepps. All rights reserved.',
  },
  ar: {
    _title: 'Sogepps – تطبيقات الهاتف والبرمجيات',
    _description: 'Sogepps تبني تطبيقات هاتف تبسّط المهام اليومية. استكشف تطبيقاتنا.',
    nav_about: 'من نحن',
    nav_apps: 'التطبيقات',
    nav_contact: 'اتصل بنا',
    hero_badge: '⚡ نبني تطبيقات هاتف مفيدة',
    hero_title: 'نبني تطبيقات<br /><span>تبسّط حياتك</span>',
    hero_desc: 'Sogepps تصنع تطبيقات هاتف بديهية مصممة لحل مشاكل حقيقية. بسيطة وموثوقة ومصنوعة بعناية.',
    hero_cta: 'استكشف تطبيقاتنا ↓',
    about_label: '◆ من نحن',
    about_title: 'من نحن',
    about_desc: 'Sogepps هو استوديو برمجيات متخصص في تطوير تطبيقات الهاتف. نؤمن بأن البرمجيات الرائعة يجب أن تكون سهلة الاستخدام وموثوقة ومتاحة للجميع. تطبيقاتنا مصممة مع إعطاء الأولوية لتجربة المستخدم.',
    stat_apps: 'تطبيقات منشورة',
    stat_fast: 'سريع وموثوق',
    stat_privacy: 'الخصوصية أولاً',
    stat_languages: '+16 لغة',
    apps_label: '◆ تطبيقاتنا',
    apps_title: 'التطبيقات',
    apps_desc: 'استكشف تطبيقاتنا المنشورة للهاتف.',
    app_name: 'صانع الدوريات والبطولات',
    app_desc: 'أنشئ دوريات وجداول خروج المغلوب وبطولات دوري كامل في ثوانٍ. تتبع النتائج، شاهد الترتيب المباشر، صدّر النتائج كملف PDF — كل ذلك من هاتفك. متاح على أندرويد.',
    badge_sports: '⚽ رياضة',
    badge_tournaments: '🏆 بطولات',
    badge_standings: '📈 الترتيب',
    badge_brackets: '⚖ الجداول',
    app_view: 'عرض التفاصيل →',
    footer_brand: 'Sogepps',
    footer_desc: 'نبني تطبيقات هاتف مفيدة. بسيطة وموثوقة وتركز على الخصوصية.',
    footer_apps: 'التطبيقات',
    footer_legal: 'قانوني',
    footer_privacy: 'سياسة الخصوصية',
    footer_delete: 'حذف الحساب',
    footer_contact: 'اتصل بنا',
    footer_rights: '© 2026 Sogepps. جميع الحقوق محفوظة.',
  },
  hi: {
    _title: 'Sogepps – मोबाइल ऐप्स और सॉफ़्टवेयर',
    _description: 'Sogepps ऐसे मोबाइल ऐप्स बनाता है जो रोज़मर्रा के कामों को आसान बनाते हैं। हमारे ऐप्स देखें।',
    nav_about: 'हमारे बारे में',
    nav_apps: 'ऐप्स',
    nav_contact: 'संपर्क',
    hero_badge: '⚡ उपयोगी मोबाइल ऐप्स बनाते हैं',
    hero_title: 'हम ऐसे ऐप्स बनाते हैं जो<br /><span>आपकी ज़िंदगी आसान करें</span>',
    hero_desc: 'Sogepps वास्तविक समस्याओं को हल करने के लिए डिज़ाइन किए गए सहज मोबाइल ऐप्स बनाता है। सरल, विश्वसनीय और ध्यान से बनाए गए।',
    hero_cta: 'हमारे ऐप्स देखें ↓',
    about_label: '◆ हमारे बारे में',
    about_title: 'हम कौन हैं',
    about_desc: 'Sogepps मोबाइल ऐप विकास पर केंद्रित एक सॉफ़्टवेयर स्टूडियो है। हम मानते हैं कि बेहतरीन सॉफ़्टवेयर उपयोग में आसान, विश्वसनीय और सभी के लिए सुलभ होना चाहिए। हमारे ऐप्स उपयोगकर्ता अनुभव को सर्वोच्च प्राथमिकता देकर डिज़ाइन किए गए हैं।',
    stat_apps: 'प्रकाशित ऐप्स',
    stat_fast: 'तेज़ और विश्वसनीय',
    stat_privacy: 'गोपनीयता सर्वोपरि',
    stat_languages: '16+ भाषाएँ',
    apps_label: '◆ हमारे ऐप्स',
    apps_title: 'एप्लिकेशन',
    apps_desc: 'हमारे प्रकाशित मोबाइल एप्लिकेशन देखें।',
    app_name: 'लीग और टूर्नामेंट मेकर',
    app_desc: 'सेकंडों में लीग, नॉकआउट ब्रैकेट और राउंड-रॉबिन टूर्नामेंट बनाएँ। स्कोर ट्रैक करें, लाइव स्टैंडिंग देखें, परिणाम PDF में निर्यात करें — सब अपने फ़ोन से। Android पर उपलब्ध।',
    badge_sports: '⚽ खेल',
    badge_tournaments: '🏆 टूर्नामेंट',
    badge_standings: '📈 स्टैंडिंग',
    badge_brackets: '⚖ ब्रैकेट',
    app_view: 'विवरण देखें →',
    footer_brand: 'Sogepps',
    footer_desc: 'उपयोगी मोबाइल ऐप्स बनाते हैं। सरल, विश्वसनीय और गोपनीयता-केंद्रित।',
    footer_apps: 'ऐप्स',
    footer_legal: 'कानूनी',
    footer_privacy: 'गोपनीयता नीति',
    footer_delete: 'खाता हटाएँ',
    footer_contact: 'संपर्क',
    footer_rights: '© 2026 Sogepps. सर्वाधिकार सुरक्षित।',
  },
  id: {
    _title: 'Sogepps – Aplikasi Mobile & Perangkat Lunak',
    _description: 'Sogepps membangun aplikasi mobile yang menyederhanakan tugas sehari-hari. Jelajahi aplikasi kami.',
    nav_about: 'Tentang',
    nav_apps: 'Aplikasi',
    nav_contact: 'Kontak',
    hero_badge: '⚡ Membangun aplikasi mobile yang berguna',
    hero_title: 'Kami membuat aplikasi yang<br /><span>menyederhanakan hidup Anda</span>',
    hero_desc: 'Sogepps menciptakan aplikasi mobile intuitif yang dirancang untuk menyelesaikan masalah nyata. Sederhana, andal, dan dibuat dengan penuh perhatian.',
    hero_cta: 'Jelajahi Aplikasi Kami ↓',
    about_label: '◆ Tentang Kami',
    about_title: 'Siapa Kami',
    about_desc: 'Sogepps adalah studio perangkat lunak yang berfokus pada pengembangan aplikasi mobile. Kami percaya perangkat lunak yang hebat harus mudah digunakan, andal, dan dapat diakses oleh semua orang. Aplikasi kami dirancang dengan pengalaman pengguna sebagai prioritas utama.',
    stat_apps: 'Aplikasi Terbit',
    stat_fast: 'Cepat & Andal',
    stat_privacy: 'Privasi Utama',
    stat_languages: '16+ Bahasa',
    apps_label: '◆ Aplikasi Kami',
    apps_title: 'Aplikasi',
    apps_desc: 'Jelajahi aplikasi mobile kami yang telah diterbitkan.',
    app_name: 'Pembuat Liga & Turnamen',
    app_desc: 'Buat liga, bagan eliminasi, dan turnamen round-robin dalam hitungan detik. Catat skor, lihat klasemen langsung, ekspor hasil sebagai PDF — semua dari ponsel Anda. Tersedia di Android.',
    badge_sports: '⚽ Olahraga',
    badge_tournaments: '🏆 Turnamen',
    badge_standings: '📈 Klasemen',
    badge_brackets: '⚖ Bagan',
    app_view: 'Lihat Detail →',
    footer_brand: 'Sogepps',
    footer_desc: 'Membangun aplikasi mobile yang berguna. Sederhana, andal, dan berfokus pada privasi.',
    footer_apps: 'Aplikasi',
    footer_legal: 'Hukum',
    footer_privacy: 'Kebijakan Privasi',
    footer_delete: 'Hapus Akun',
    footer_contact: 'Kontak',
    footer_rights: '© 2026 Sogepps. Hak cipta dilindungi.',
  },
  pl: {
    _title: 'Sogepps – Aplikacje Mobilne i Oprogramowanie',
    _description: 'Sogepps tworzy aplikacje mobilne, które upraszczają codzienne zadania. Poznaj nasze aplikacje.',
    nav_about: 'O nas',
    nav_apps: 'Aplikacje',
    nav_contact: 'Kontakt',
    hero_badge: '⚡ Tworzymy przydatne aplikacje mobilne',
    hero_title: 'Tworzymy aplikacje, które<br /><span>upraszczają Twoje życie</span>',
    hero_desc: 'Sogepps tworzy intuicyjne aplikacje mobilne zaprojektowane do rozwiązywania rzeczywistych problemów. Proste, niezawodne i tworzone z dbałością.',
    hero_cta: 'Poznaj nasze aplikacje ↓',
    about_label: '◆ O nas',
    about_title: 'Kim jesteśmy',
    about_desc: 'Sogepps to studio programistyczne skupione na tworzeniu aplikacji mobilnych. Wierzymy, że świetne oprogramowanie powinno być proste w użyciu, niezawodne i dostępne dla każdego. Nasze aplikacje są projektowane z najwyższym priorytetem na doświadczenie użytkownika.',
    stat_apps: 'Opublikowane aplikacje',
    stat_fast: 'Szybko i niezawodnie',
    stat_privacy: 'Prywatność na pierwszym miejscu',
    stat_languages: '16+ Języków',
    apps_label: '◆ Nasze Aplikacje',
    apps_title: 'Aplikacje',
    apps_desc: 'Poznaj nasze opublikowane aplikacje mobilne.',
    app_name: 'Kreator Lig i Turniejów',
    app_desc: 'Twórz ligi, drabinki pucharowe i turnieje każdy z każdym w kilka sekund. Śledź wyniki, przeglądaj tabele na żywo, eksportuj wyniki do PDF — wszystko z telefonu. Dostępne na Androida.',
    badge_sports: '⚽ Sport',
    badge_tournaments: '🏆 Turnieje',
    badge_standings: '📈 Tabele',
    badge_brackets: '⚖ Drabinki',
    app_view: 'Zobacz szczegóły →',
    footer_brand: 'Sogepps',
    footer_desc: 'Tworzymy przydatne aplikacje mobilne. Proste, niezawodne i zorientowane na prywatność.',
    footer_apps: 'Aplikacje',
    footer_legal: 'Informacje prawne',
    footer_privacy: 'Polityka prywatności',
    footer_delete: 'Usuń konto',
    footer_contact: 'Kontakt',
    footer_rights: '© 2026 Sogepps. Wszelkie prawa zastrzeżone.',
  },
};
