var PORTAL_TRANSLATIONS = {
  en: {
    _title: 'League & Tournament Maker – Create Tournaments Easily',
    _description: 'Create leagues, knockout brackets, and round-robin tournaments in seconds. Track scores, view standings, share results.',
    nav_back: '← Sogepps',
    nav_features: 'Features',
    nav_privacy: 'Privacy Policy',
    nav_delete: 'Delete Account',
    hero_badge: '🏆 #1 Tournament Organizer',
    hero_title: 'Create Tournaments<br /><span class="grad">Like a Pro</span>',
    hero_desc: 'Set up leagues, knockout brackets, and round-robin tournaments in under a minute. Enter scores, track live standings, and share results — all from your phone.',
    btn_google_play: 'Get it on Google Play',
    btn_see_features: 'See Features ↓',
    feat_label: '◆ Features',
    feat_title: 'Everything You Need to Organize',
    feat_desc: 'Powerful tools for any tournament format, right in your pocket.',
    feat1_title: 'League & Round-Robin',
    feat1_desc: 'Create round-robin leagues with single or double round support. Customize match settings for up to 20 teams per league.',
    feat2_title: 'Knockout Brackets',
    feat2_desc: 'Single-elimination brackets for 2 to 32 participants. Automatic bracket sizing with BYE support for uneven numbers.',
    feat3_title: 'Live Standings & Export',
    feat3_desc: 'Real-time standings with points, goals, wins, draws, and losses. Export as PDF, CSV, or share as a screenshot image.',
    feat4_title: 'Multiple Sports',
    feat4_desc: 'Built-in support for football, basketball, volleyball, tennis, and custom sports. Sport-specific scoring rules included.',
    feat5_title: 'Privacy Focused',
    feat5_desc: 'No personal data collected. No tracking. Your tournaments stay yours. Full GDPR compliance with user consent management.',
    feat6_title: '16+ Languages',
    feat6_desc: 'Available in Turkish, English, German, French, Spanish, Italian, Portuguese, Dutch, Russian, Japanese, Korean, Arabic, and more.',
    how_label: '◆ How It Works',
    how_title: 'Three Simple Steps',
    step1_title: 'Choose Format',
    step1_desc: 'Pick between league (round-robin) or knockout (elimination bracket) format.',
    step2_title: 'Add Teams',
    step2_desc: 'Enter team or player names. The fixture is generated automatically.',
    step3_title: 'Play & Track',
    step3_desc: 'Enter match scores as you play. Standings and brackets update in real time.',
    cta_title: 'Ready to Organize?',
    cta_desc: 'Download the app and create your first tournament in under a minute. Free to use with optional premium features.',
    cta_btn: 'Download Free on Google Play',
    footer_brand: 'League & Tournament Maker',
    footer_by: 'by',
    footer_app: 'App',
    footer_google_play: 'Google Play',
    footer_features: 'Features',
    footer_legal: 'Legal',
    footer_privacy: 'Privacy Policy',
    footer_delete: 'Delete Account',
    footer_contact: 'Contact',
    footer_rights: '© 2026',
  },
  tr: {
    _title: 'Lig ve Turnuva Oluşturucu – Kolayca Turnuva Oluşturun',
    _description: 'Saniyeler içinde lig, eleme tabloları ve turnuvalar oluşturun. Skorları girin, puan durumunu görüntüleyin.',
    nav_back: '← Sogepps',
    nav_features: 'Özellikler',
    nav_privacy: 'Gizlilik Politikası',
    nav_delete: 'Hesap Sil',
    hero_badge: '🏆 #1 Turnuva Organizatörü',
    hero_title: 'Profesyonel Gibi<br /><span class="grad">Turnuva Oluşturun</span>',
    hero_desc: 'Bir dakikadan kısa sürede lig, eleme tabloları ve çift devreli turnuvalar kurun. Skorları girin, canlı puan durumunu takip edin ve sonuçları paylaşın.',
    btn_google_play: 'Google Play\'den İndir',
    btn_see_features: 'Özellikleri Gör ↓',
    feat_label: '◆ Özellikler',
    feat_title: 'Organize Etmek İçin İhtiyacınız Olan Her Şey',
    feat_desc: 'Her turnuva formatı için güçlü araçlar, cebinizde.',
    feat1_title: 'Lig ve Çift Devreli',
    feat1_desc: 'Tek veya çift devreli lig turnuvaları oluşturun. Lig başına 20 takıma kadar maç ayarlarını özelleştirin.',
    feat2_title: 'Eleme Tabloları',
    feat2_desc: '2 ile 32 katılımcı için tek eleme tabloları. Tek sayılı katılımcılar için BYE desteğiyle otomatik tablo boyutlandırma.',
    feat3_title: 'Canlı Puan Durumu ve Dışa Aktarma',
    feat3_desc: 'Puanlar, goller, galibiyetler, beraberlikler ve mağlubiyetlerle gerçek zamanlı puan durumu. PDF, CSV veya ekran görüntüsü olarak dışa aktarın.',
    feat4_title: 'Çoklu Spor Dalları',
    feat4_desc: 'Futbol, basketbol, voleybol, tenis ve özel sporlar için yerleşik destek. Spora özel puanlama kuralları dahil.',
    feat5_title: 'Gizlilik Odaklı',
    feat5_desc: 'Kişisel veri toplanmaz. Takip yok. Turnuvalarınız sizin. Kullanıcı onay yönetimi ile tam GDPR uyumluluğu.',
    feat6_title: '16+ Dil Desteği',
    feat6_desc: 'Türkçe, İngilizce, Almanca, Fransızca, İspanyolca, İtalyanca, Portekizce, Felemenkçe, Rusça, Japonca, Korece, Arapça ve daha fazlası.',
    how_label: '◆ Nasıl Çalışır',
    how_title: 'Üç Basit Adım',
    step1_title: 'Format Seçin',
    step1_desc: 'Lig (çift devreli) veya eleme (tek eleme tablosu) formatı arasında seçim yapın.',
    step2_title: 'Takımları Ekleyin',
    step2_desc: 'Takım veya oyuncu isimlerini girin. Fikstür otomatik olarak oluşturulur.',
    step3_title: 'Oyna ve Takip Et',
    step3_desc: 'Oynarken maç skorlarını girin. Puan durumu ve tablolar gerçek zamanlı güncellenir.',
    cta_title: 'Organize Etmeye Hazır mısınız?',
    cta_desc: 'Uygulamayı indirin ve bir dakikadan kısa sürede ilk turnuvanızı oluşturun. Opsiyonel premium özelliklerle ücretsiz kullanın.',
    cta_btn: 'Google Play\'den Ücretsiz İndir',
    footer_brand: 'Lig ve Turnuva Oluşturucu',
    footer_by: 'yapımcı',
    footer_app: 'Uygulama',
    footer_google_play: 'Google Play',
    footer_features: 'Özellikler',
    footer_legal: 'Yasal',
    footer_privacy: 'Gizlilik Politikası',
    footer_delete: 'Hesap Sil',
    footer_contact: 'İletişim',
    footer_rights: '© 2026',
  },
  de: {
    _title: 'Liga & Turnier Ersteller – Turniere einfach erstellen',
    _description: 'Erstellen Sie Ligen, K.o.-Tabellen und Rundenturniere in Sekunden. Ergebnisse eingeben, Tabellen anzeigen, Resultate teilen.',
    nav_back: '← Sogepps',
    nav_features: 'Funktionen',
    nav_privacy: 'Datenschutzrichtlinie',
    nav_delete: 'Konto löschen',
    hero_badge: '🏆 #1 Turnierorganisator',
    hero_title: 'Turniere erstellen<br /><span class="grad">Wie ein Profi</span>',
    hero_desc: 'Erstellen Sie Ligen, K.o.-Tabellen und Rundenturniere in unter einer Minute. Ergebnisse eingeben, Live-Tabellen verfolgen und Resultate teilen — alles von Ihrem Handy.',
    btn_google_play: 'Bei Google Play herunterladen',
    btn_see_features: 'Funktionen ansehen ↓',
    feat_label: '◆ Funktionen',
    feat_title: 'Alles, was Sie zum Organisieren brauchen',
    feat_desc: 'Leistungsstarke Werkzeuge für jedes Turnierformat, direkt in Ihrer Tasche.',
    feat1_title: 'Liga & Rundenturnier',
    feat1_desc: 'Erstellen Sie Rundenturniere mit Einzel- oder Doppelrunden-Unterstützung. Passen Sie Spieleinstellungen für bis zu 20 Teams pro Liga an.',
    feat2_title: 'K.o.-Tabellen',
    feat2_desc: 'Einzeleliminierungstabellen für 2 bis 32 Teilnehmer. Automatische Tabellengröße mit BYE-Unterstützung für ungerade Anzahlen.',
    feat3_title: 'Live-Tabellen & Export',
    feat3_desc: 'Echtzeit-Tabellen mit Punkten, Toren, Siegen, Unentschieden und Niederlagen. Export als PDF, CSV oder als Screenshot-Bild teilen.',
    feat4_title: 'Mehrere Sportarten',
    feat4_desc: 'Integrierte Unterstützung für Fußball, Basketball, Volleyball, Tennis und benutzerdefinierte Sportarten. Sportspezifische Wertungsregeln inklusive.',
    feat5_title: 'Datenschutzorientiert',
    feat5_desc: 'Keine persönlichen Daten gesammelt. Kein Tracking. Ihre Turniere bleiben Ihnen. Volle DSGVO-Konformität mit Einwilligungsverwaltung.',
    feat6_title: '16+ Sprachen',
    feat6_desc: 'Verfügbar in Türkisch, Englisch, Deutsch, Französisch, Spanisch, Italienisch, Portugiesisch, Niederländisch, Russisch, Japanisch, Koreanisch, Arabisch und mehr.',
    how_label: '◆ So funktioniert es',
    how_title: 'Drei einfache Schritte',
    step1_title: 'Format wählen',
    step1_desc: 'Wählen Sie zwischen Liga (Rundenturnier) oder K.o. (Eliminierungstabelle) Format.',
    step2_title: 'Teams hinzufügen',
    step2_desc: 'Geben Sie Team- oder Spielernamen ein. Der Spielplan wird automatisch erstellt.',
    step3_title: 'Spielen & Verfolgen',
    step3_desc: 'Geben Sie Spielergebnisse ein, während Sie spielen. Tabellen und K.o.-Runden aktualisieren sich in Echtzeit.',
    cta_title: 'Bereit zum Organisieren?',
    cta_desc: 'Laden Sie die App herunter und erstellen Sie Ihr erstes Turnier in unter einer Minute. Kostenlos nutzbar mit optionalen Premium-Funktionen.',
    cta_btn: 'Kostenlos bei Google Play herunterladen',
    footer_brand: 'Liga & Turnier Ersteller',
    footer_by: 'von',
    footer_app: 'App',
    footer_google_play: 'Google Play',
    footer_features: 'Funktionen',
    footer_legal: 'Rechtliches',
    footer_privacy: 'Datenschutzrichtlinie',
    footer_delete: 'Konto löschen',
    footer_contact: 'Kontakt',
    footer_rights: '© 2026',
  },
  fr: {
    _title: 'Créateur de Ligues & Tournois – Créez des tournois facilement',
    _description: 'Créez des ligues, des tableaux à élimination directe et des tournois toutes rondes en quelques secondes. Suivez les scores, consultez les classements, partagez les résultats.',
    nav_back: '← Sogepps',
    nav_features: 'Fonctionnalités',
    nav_privacy: 'Politique de confidentialité',
    nav_delete: 'Supprimer le compte',
    hero_badge: '🏆 #1 Organisateur de tournois',
    hero_title: 'Créez des tournois<br /><span class="grad">Comme un pro</span>',
    hero_desc: 'Mettez en place des ligues, des tableaux à élimination directe et des tournois toutes rondes en moins d\'une minute. Entrez les scores, suivez les classements en direct et partagez les résultats — le tout depuis votre téléphone.',
    btn_google_play: 'Télécharger sur Google Play',
    btn_see_features: 'Voir les fonctionnalités ↓',
    feat_label: '◆ Fonctionnalités',
    feat_title: 'Tout ce dont vous avez besoin pour organiser',
    feat_desc: 'Des outils puissants pour tout format de tournoi, directement dans votre poche.',
    feat1_title: 'Ligue & Toutes rondes',
    feat1_desc: 'Créez des ligues toutes rondes avec support simple ou double tour. Personnalisez les paramètres de match pour jusqu\'à 20 équipes par ligue.',
    feat2_title: 'Tableaux à élimination',
    feat2_desc: 'Tableaux à élimination directe pour 2 à 32 participants. Dimensionnement automatique avec support BYE pour les nombres impairs.',
    feat3_title: 'Classements en direct & Export',
    feat3_desc: 'Classements en temps réel avec points, buts, victoires, nuls et défaites. Exportez en PDF, CSV ou partagez sous forme de capture d\'écran.',
    feat4_title: 'Sports multiples',
    feat4_desc: 'Support intégré pour le football, le basketball, le volleyball, le tennis et les sports personnalisés. Règles de notation spécifiques au sport incluses.',
    feat5_title: 'Axé sur la confidentialité',
    feat5_desc: 'Aucune donnée personnelle collectée. Pas de suivi. Vos tournois restent les vôtres. Conformité RGPD complète avec gestion du consentement.',
    feat6_title: '16+ Langues',
    feat6_desc: 'Disponible en turc, anglais, allemand, français, espagnol, italien, portugais, néerlandais, russe, japonais, coréen, arabe et plus encore.',
    how_label: '◆ Comment ça marche',
    how_title: 'Trois étapes simples',
    step1_title: 'Choisir le format',
    step1_desc: 'Choisissez entre ligue (toutes rondes) ou élimination (tableau à élimination directe).',
    step2_title: 'Ajouter des équipes',
    step2_desc: 'Entrez les noms des équipes ou des joueurs. Le calendrier est généré automatiquement.',
    step3_title: 'Jouez & Suivez',
    step3_desc: 'Entrez les scores des matchs au fur et à mesure. Les classements et tableaux se mettent à jour en temps réel.',
    cta_title: 'Prêt à organiser ?',
    cta_desc: 'Téléchargez l\'application et créez votre premier tournoi en moins d\'une minute. Gratuit avec des fonctionnalités premium optionnelles.',
    cta_btn: 'Télécharger gratuitement sur Google Play',
    footer_brand: 'Créateur de Ligues & Tournois',
    footer_by: 'par',
    footer_app: 'Application',
    footer_google_play: 'Google Play',
    footer_features: 'Fonctionnalités',
    footer_legal: 'Mentions légales',
    footer_privacy: 'Politique de confidentialité',
    footer_delete: 'Supprimer le compte',
    footer_contact: 'Contact',
    footer_rights: '© 2026',
  },
  es: {
    _title: 'Creador de Ligas y Torneos – Crea torneos fácilmente',
    _description: 'Crea ligas, cuadros eliminatorios y torneos de todos contra todos en segundos. Registra puntuaciones, consulta clasificaciones, comparte resultados.',
    nav_back: '← Sogepps',
    nav_features: 'Características',
    nav_privacy: 'Política de privacidad',
    nav_delete: 'Eliminar cuenta',
    hero_badge: '🏆 #1 Organizador de torneos',
    hero_title: 'Crea torneos<br /><span class="grad">Como un profesional</span>',
    hero_desc: 'Configura ligas, cuadros eliminatorios y torneos de todos contra todos en menos de un minuto. Introduce puntuaciones, sigue clasificaciones en vivo y comparte resultados — todo desde tu teléfono.',
    btn_google_play: 'Disponible en Google Play',
    btn_see_features: 'Ver características ↓',
    feat_label: '◆ Características',
    feat_title: 'Todo lo que necesitas para organizar',
    feat_desc: 'Herramientas potentes para cualquier formato de torneo, directamente en tu bolsillo.',
    feat1_title: 'Liga y todos contra todos',
    feat1_desc: 'Crea ligas de todos contra todos con soporte de una o dos vueltas. Personaliza los ajustes de partido para hasta 20 equipos por liga.',
    feat2_title: 'Cuadros eliminatorios',
    feat2_desc: 'Cuadros de eliminación directa para 2 a 32 participantes. Dimensionamiento automático con soporte BYE para números impares.',
    feat3_title: 'Clasificaciones en vivo y exportación',
    feat3_desc: 'Clasificaciones en tiempo real con puntos, goles, victorias, empates y derrotas. Exporta como PDF, CSV o comparte como captura de pantalla.',
    feat4_title: 'Múltiples deportes',
    feat4_desc: 'Soporte integrado para fútbol, baloncesto, voleibol, tenis y deportes personalizados. Reglas de puntuación específicas del deporte incluidas.',
    feat5_title: 'Enfocado en la privacidad',
    feat5_desc: 'No se recopilan datos personales. Sin seguimiento. Tus torneos son tuyos. Cumplimiento total del RGPD con gestión del consentimiento del usuario.',
    feat6_title: '16+ Idiomas',
    feat6_desc: 'Disponible en turco, inglés, alemán, francés, español, italiano, portugués, neerlandés, ruso, japonés, coreano, árabe y más.',
    how_label: '◆ Cómo funciona',
    how_title: 'Tres pasos sencillos',
    step1_title: 'Elige el formato',
    step1_desc: 'Elige entre liga (todos contra todos) o eliminatoria (cuadro de eliminación directa).',
    step2_title: 'Añade equipos',
    step2_desc: 'Introduce los nombres de los equipos o jugadores. El calendario se genera automáticamente.',
    step3_title: 'Juega y sigue',
    step3_desc: 'Introduce los resultados de los partidos mientras juegas. Las clasificaciones y cuadros se actualizan en tiempo real.',
    cta_title: '¿Listo para organizar?',
    cta_desc: 'Descarga la aplicación y crea tu primer torneo en menos de un minuto. Gratis con funciones premium opcionales.',
    cta_btn: 'Descargar gratis en Google Play',
    footer_brand: 'Creador de Ligas y Torneos',
    footer_by: 'por',
    footer_app: 'Aplicación',
    footer_google_play: 'Google Play',
    footer_features: 'Características',
    footer_legal: 'Legal',
    footer_privacy: 'Política de privacidad',
    footer_delete: 'Eliminar cuenta',
    footer_contact: 'Contacto',
    footer_rights: '© 2026',
  },
  it: {
    _title: 'Creatore di Leghe e Tornei – Crea tornei facilmente',
    _description: 'Crea leghe, tabelloni a eliminazione e tornei all\'italiana in pochi secondi. Inserisci punteggi, visualizza classifiche, condividi risultati.',
    nav_back: '← Sogepps',
    nav_features: 'Funzionalità',
    nav_privacy: 'Informativa sulla privacy',
    nav_delete: 'Elimina account',
    hero_badge: '🏆 #1 Organizzatore di tornei',
    hero_title: 'Crea tornei<br /><span class="grad">Come un professionista</span>',
    hero_desc: 'Configura leghe, tabelloni a eliminazione e tornei all\'italiana in meno di un minuto. Inserisci punteggi, segui le classifiche in diretta e condividi i risultati — tutto dal tuo telefono.',
    btn_google_play: 'Scarica su Google Play',
    btn_see_features: 'Vedi funzionalità ↓',
    feat_label: '◆ Funzionalità',
    feat_title: 'Tutto ciò che ti serve per organizzare',
    feat_desc: 'Strumenti potenti per qualsiasi formato di torneo, direttamente in tasca.',
    feat1_title: 'Lega e girone all\'italiana',
    feat1_desc: 'Crea leghe all\'italiana con supporto per turno singolo o doppio. Personalizza le impostazioni delle partite per un massimo di 20 squadre per lega.',
    feat2_title: 'Tabelloni a eliminazione',
    feat2_desc: 'Tabelloni a eliminazione diretta per 2-32 partecipanti. Dimensionamento automatico con supporto BYE per numeri dispari.',
    feat3_title: 'Classifiche in diretta ed esportazione',
    feat3_desc: 'Classifiche in tempo reale con punti, gol, vittorie, pareggi e sconfitte. Esporta come PDF, CSV o condividi come screenshot.',
    feat4_title: 'Sport multipli',
    feat4_desc: 'Supporto integrato per calcio, basket, pallavolo, tennis e sport personalizzati. Regole di punteggio specifiche per sport incluse.',
    feat5_title: 'Orientato alla privacy',
    feat5_desc: 'Nessun dato personale raccolto. Nessun tracciamento. I tuoi tornei restano tuoi. Piena conformità GDPR con gestione del consenso utente.',
    feat6_title: '16+ Lingue',
    feat6_desc: 'Disponibile in turco, inglese, tedesco, francese, spagnolo, italiano, portoghese, olandese, russo, giapponese, coreano, arabo e altro.',
    how_label: '◆ Come funziona',
    how_title: 'Tre semplici passaggi',
    step1_title: 'Scegli il formato',
    step1_desc: 'Scegli tra lega (girone all\'italiana) o eliminazione (tabellone a eliminazione diretta).',
    step2_title: 'Aggiungi squadre',
    step2_desc: 'Inserisci i nomi delle squadre o dei giocatori. Il calendario viene generato automaticamente.',
    step3_title: 'Gioca e segui',
    step3_desc: 'Inserisci i risultati delle partite mentre giochi. Classifiche e tabelloni si aggiornano in tempo reale.',
    cta_title: 'Pronto a organizzare?',
    cta_desc: 'Scarica l\'app e crea il tuo primo torneo in meno di un minuto. Gratuito con funzionalità premium opzionali.',
    cta_btn: 'Scarica gratis su Google Play',
    footer_brand: 'Creatore di Leghe e Tornei',
    footer_by: 'di',
    footer_app: 'App',
    footer_google_play: 'Google Play',
    footer_features: 'Funzionalità',
    footer_legal: 'Legale',
    footer_privacy: 'Informativa sulla privacy',
    footer_delete: 'Elimina account',
    footer_contact: 'Contatti',
    footer_rights: '© 2026',
  },
  pt: {
    _title: 'Criador de Ligas e Torneios – Crie torneios facilmente',
    _description: 'Crie ligas, chaves eliminatórias e torneios todos contra todos em segundos. Registre pontuações, veja classificações, compartilhe resultados.',
    nav_back: '← Sogepps',
    nav_features: 'Recursos',
    nav_privacy: 'Política de Privacidade',
    nav_delete: 'Excluir Conta',
    hero_badge: '🏆 #1 Organizador de Torneios',
    hero_title: 'Crie torneios<br /><span class="grad">Como um profissional</span>',
    hero_desc: 'Configure ligas, chaves eliminatórias e torneios todos contra todos em menos de um minuto. Insira pontuações, acompanhe classificações ao vivo e compartilhe resultados — tudo pelo seu celular.',
    btn_google_play: 'Disponível no Google Play',
    btn_see_features: 'Ver recursos ↓',
    feat_label: '◆ Recursos',
    feat_title: 'Tudo o que você precisa para organizar',
    feat_desc: 'Ferramentas poderosas para qualquer formato de torneio, direto no seu bolso.',
    feat1_title: 'Liga e todos contra todos',
    feat1_desc: 'Crie ligas todos contra todos com suporte para turno simples ou duplo. Personalize as configurações de partida para até 20 times por liga.',
    feat2_title: 'Chaves eliminatórias',
    feat2_desc: 'Chaves de eliminação direta para 2 a 32 participantes. Dimensionamento automático com suporte BYE para números ímpares.',
    feat3_title: 'Classificações ao vivo e exportação',
    feat3_desc: 'Classificações em tempo real com pontos, gols, vitórias, empates e derrotas. Exporte como PDF, CSV ou compartilhe como captura de tela.',
    feat4_title: 'Múltiplos esportes',
    feat4_desc: 'Suporte integrado para futebol, basquete, vôlei, tênis e esportes personalizados. Regras de pontuação específicas do esporte incluídas.',
    feat5_title: 'Focado em privacidade',
    feat5_desc: 'Nenhum dado pessoal coletado. Sem rastreamento. Seus torneios permanecem seus. Conformidade total com LGPD/GDPR com gerenciamento de consentimento do usuário.',
    feat6_title: '16+ Idiomas',
    feat6_desc: 'Disponível em turco, inglês, alemão, francês, espanhol, italiano, português, holandês, russo, japonês, coreano, árabe e mais.',
    how_label: '◆ Como funciona',
    how_title: 'Três passos simples',
    step1_title: 'Escolha o formato',
    step1_desc: 'Escolha entre liga (todos contra todos) ou eliminatória (chave de eliminação direta).',
    step2_title: 'Adicione times',
    step2_desc: 'Insira os nomes dos times ou jogadores. O calendário é gerado automaticamente.',
    step3_title: 'Jogue e acompanhe',
    step3_desc: 'Insira os resultados das partidas enquanto joga. Classificações e chaves se atualizam em tempo real.',
    cta_title: 'Pronto para organizar?',
    cta_desc: 'Baixe o aplicativo e crie seu primeiro torneio em menos de um minuto. Gratuito com recursos premium opcionais.',
    cta_btn: 'Baixar grátis no Google Play',
    footer_brand: 'Criador de Ligas e Torneios',
    footer_by: 'por',
    footer_app: 'Aplicativo',
    footer_google_play: 'Google Play',
    footer_features: 'Recursos',
    footer_legal: 'Jurídico',
    footer_privacy: 'Política de Privacidade',
    footer_delete: 'Excluir Conta',
    footer_contact: 'Contato',
    footer_rights: '© 2026',
  },
  nl: {
    _title: 'Competitie & Toernooi Maker – Maak eenvoudig toernooien',
    _description: 'Maak competities, knock-out schema\'s en round-robin toernooien in seconden. Scores bijhouden, standen bekijken, resultaten delen.',
    nav_back: '← Sogepps',
    nav_features: 'Functies',
    nav_privacy: 'Privacybeleid',
    nav_delete: 'Account verwijderen',
    hero_badge: '🏆 #1 Toernooiorganisator',
    hero_title: 'Maak toernooien<br /><span class="grad">Als een professional</span>',
    hero_desc: 'Stel competities, knock-out schema\'s en round-robin toernooien op in minder dan een minuut. Voer scores in, volg live standen en deel resultaten — allemaal vanaf je telefoon.',
    btn_google_play: 'Downloaden via Google Play',
    btn_see_features: 'Bekijk functies ↓',
    feat_label: '◆ Functies',
    feat_title: 'Alles wat je nodig hebt om te organiseren',
    feat_desc: 'Krachtige tools voor elk toernooiformaat, direct in je zak.',
    feat1_title: 'Competitie & Round-Robin',
    feat1_desc: 'Maak round-robin competities met enkele of dubbele ronde ondersteuning. Pas wedstrijdinstellingen aan voor maximaal 20 teams per competitie.',
    feat2_title: 'Knock-out schema\'s',
    feat2_desc: 'Enkele eliminatie schema\'s voor 2 tot 32 deelnemers. Automatische schemagrootte met BYE-ondersteuning voor oneven aantallen.',
    feat3_title: 'Live standen & Export',
    feat3_desc: 'Realtime standen met punten, doelpunten, overwinningen, gelijkspelen en nederlagen. Exporteer als PDF, CSV of deel als screenshot.',
    feat4_title: 'Meerdere sporten',
    feat4_desc: 'Ingebouwde ondersteuning voor voetbal, basketbal, volleybal, tennis en aangepaste sporten. Sportspecifieke scoreregels inbegrepen.',
    feat5_title: 'Privacy gericht',
    feat5_desc: 'Geen persoonlijke gegevens verzameld. Geen tracking. Je toernooien blijven van jou. Volledige AVG-naleving met toestemmingsbeheer.',
    feat6_title: '16+ Talen',
    feat6_desc: 'Beschikbaar in Turks, Engels, Duits, Frans, Spaans, Italiaans, Portugees, Nederlands, Russisch, Japans, Koreaans, Arabisch en meer.',
    how_label: '◆ Hoe het werkt',
    how_title: 'Drie eenvoudige stappen',
    step1_title: 'Kies het formaat',
    step1_desc: 'Kies tussen competitie (round-robin) of knock-out (eliminatie schema) formaat.',
    step2_title: 'Teams toevoegen',
    step2_desc: 'Voer team- of spelernamen in. Het speelschema wordt automatisch gegenereerd.',
    step3_title: 'Speel & Volg',
    step3_desc: 'Voer wedstrijdscores in terwijl je speelt. Standen en schema\'s worden in realtime bijgewerkt.',
    cta_title: 'Klaar om te organiseren?',
    cta_desc: 'Download de app en maak je eerste toernooi in minder dan een minuut. Gratis te gebruiken met optionele premium functies.',
    cta_btn: 'Gratis downloaden via Google Play',
    footer_brand: 'Competitie & Toernooi Maker',
    footer_by: 'door',
    footer_app: 'App',
    footer_google_play: 'Google Play',
    footer_features: 'Functies',
    footer_legal: 'Juridisch',
    footer_privacy: 'Privacybeleid',
    footer_delete: 'Account verwijderen',
    footer_contact: 'Contact',
    footer_rights: '© 2026',
  },
  ru: {
    _title: 'Создатель Лиг и Турниров – Создавайте турниры легко',
    _description: 'Создавайте лиги, сетки плей-офф и круговые турниры за секунды. Вводите счёт, просматривайте таблицы, делитесь результатами.',
    nav_back: '← Sogepps',
    nav_features: 'Функции',
    nav_privacy: 'Политика конфиденциальности',
    nav_delete: 'Удалить аккаунт',
    hero_badge: '🏆 #1 Организатор турниров',
    hero_title: 'Создавайте турниры<br /><span class="grad">Как профессионал</span>',
    hero_desc: 'Создавайте лиги, сетки плей-офф и круговые турниры менее чем за минуту. Вводите счёт, отслеживайте таблицы в реальном времени и делитесь результатами — всё с вашего телефона.',
    btn_google_play: 'Скачать в Google Play',
    btn_see_features: 'Смотреть функции ↓',
    feat_label: '◆ Функции',
    feat_title: 'Всё, что нужно для организации',
    feat_desc: 'Мощные инструменты для любого формата турнира, прямо в вашем кармане.',
    feat1_title: 'Лига и круговой турнир',
    feat1_desc: 'Создавайте круговые лиги с поддержкой одного или двух кругов. Настраивайте параметры матчей для до 20 команд в лиге.',
    feat2_title: 'Сетки плей-офф',
    feat2_desc: 'Сетки с одиночным выбыванием для 2-32 участников. Автоматическое масштабирование сетки с поддержкой BYE для нечётного числа участников.',
    feat3_title: 'Таблицы в реальном времени и экспорт',
    feat3_desc: 'Таблицы в реальном времени с очками, голами, победами, ничьими и поражениями. Экспорт в PDF, CSV или отправка в виде скриншота.',
    feat4_title: 'Множество видов спорта',
    feat4_desc: 'Встроенная поддержка футбола, баскетбола, волейбола, тенниса и пользовательских видов спорта. Правила подсчёта очков для каждого вида спорта включены.',
    feat5_title: 'Ориентация на конфиденциальность',
    feat5_desc: 'Никаких личных данных не собирается. Без отслеживания. Ваши турниры остаются вашими. Полное соответствие GDPR с управлением согласием пользователей.',
    feat6_title: '16+ Языков',
    feat6_desc: 'Доступно на турецком, английском, немецком, французском, испанском, итальянском, португальском, нидерландском, русском, японском, корейском, арабском и других языках.',
    how_label: '◆ Как это работает',
    how_title: 'Три простых шага',
    step1_title: 'Выберите формат',
    step1_desc: 'Выберите между лигой (круговой турнир) или плей-офф (сетка на выбывание).',
    step2_title: 'Добавьте команды',
    step2_desc: 'Введите названия команд или имена игроков. Расписание создаётся автоматически.',
    step3_title: 'Играйте и отслеживайте',
    step3_desc: 'Вводите счёт матчей по ходу игры. Таблицы и сетки обновляются в реальном времени.',
    cta_title: 'Готовы организовать?',
    cta_desc: 'Скачайте приложение и создайте свой первый турнир менее чем за минуту. Бесплатно с дополнительными премиум-функциями.',
    cta_btn: 'Скачать бесплатно в Google Play',
    footer_brand: 'Создатель Лиг и Турниров',
    footer_by: 'от',
    footer_app: 'Приложение',
    footer_google_play: 'Google Play',
    footer_features: 'Функции',
    footer_legal: 'Правовая информация',
    footer_privacy: 'Политика конфиденциальности',
    footer_delete: 'Удалить аккаунт',
    footer_contact: 'Контакты',
    footer_rights: '© 2026',
  },
  ja: {
    _title: 'リーグ＆トーナメントメーカー – 簡単にトーナメントを作成',
    _description: 'リーグ、トーナメント表、総当たり戦を数秒で作成。スコアを記録し、順位表を確認し、結果を共有。',
    nav_back: '← Sogepps',
    nav_features: '機能',
    nav_privacy: 'プライバシーポリシー',
    nav_delete: 'アカウント削除',
    hero_badge: '🏆 #1 トーナメントオーガナイザー',
    hero_title: 'トーナメントを作成<br /><span class="grad">プロのように</span>',
    hero_desc: 'リーグ、トーナメント表、総当たり戦を1分以内にセットアップ。スコアを入力し、リアルタイムで順位を追跡し、結果を共有 — すべてスマートフォンから。',
    btn_google_play: 'Google Playで入手',
    btn_see_features: '機能を見る ↓',
    feat_label: '◆ 機能',
    feat_title: '整理に必要なすべて',
    feat_desc: 'あらゆるトーナメント形式に対応する強力なツール。',
    feat1_title: 'リーグ＆総当たり戦',
    feat1_desc: 'シングルまたはダブルラウンド対応の総当たりリーグを作成。リーグあたり最大20チームの試合設定をカスタマイズ。',
    feat2_title: 'トーナメント表',
    feat2_desc: '2～32名の参加者向けシングルエリミネーション表。奇数参加者のBYEサポート付き自動サイズ調整。',
    feat3_title: 'リアルタイム順位表＆エクスポート',
    feat3_desc: 'ポイント、得点、勝利、引き分け、敗北を含むリアルタイム順位表。PDF、CSVでエクスポート、またはスクリーンショットとして共有。',
    feat4_title: '複数のスポーツ',
    feat4_desc: 'サッカー、バスケットボール、バレーボール、テニス、カスタムスポーツの組み込みサポート。スポーツ固有のスコアリングルール付き。',
    feat5_title: 'プライバシー重視',
    feat5_desc: '個人データの収集なし。トラッキングなし。あなたのトーナメントはあなたのもの。ユーザー同意管理による完全なGDPR準拠。',
    feat6_title: '16以上の言語',
    feat6_desc: 'トルコ語、英語、ドイツ語、フランス語、スペイン語、イタリア語、ポルトガル語、オランダ語、ロシア語、日本語、韓国語、アラビア語などで利用可能。',
    how_label: '◆ 使い方',
    how_title: '3つの簡単なステップ',
    step1_title: 'フォーマットを選択',
    step1_desc: 'リーグ（総当たり）またはトーナメント（エリミネーション）形式を選択。',
    step2_title: 'チームを追加',
    step2_desc: 'チーム名または選手名を入力。対戦表が自動で生成されます。',
    step3_title: 'プレー＆追跡',
    step3_desc: '試合スコアを入力。順位表とトーナメント表がリアルタイムで更新。',
    cta_title: '整理する準備はできましたか？',
    cta_desc: 'アプリをダウンロードして、1分以内に最初のトーナメントを作成しましょう。オプションのプレミアム機能付きで無料。',
    cta_btn: 'Google Playで無料ダウンロード',
    footer_brand: 'リーグ＆トーナメントメーカー',
    footer_by: '制作',
    footer_app: 'アプリ',
    footer_google_play: 'Google Play',
    footer_features: '機能',
    footer_legal: '法的情報',
    footer_privacy: 'プライバシーポリシー',
    footer_delete: 'アカウント削除',
    footer_contact: 'お問い合わせ',
    footer_rights: '© 2026',
  },
  ko: {
    _title: '리그 & 토너먼트 메이커 – 쉽게 토너먼트 만들기',
    _description: '몇 초 만에 리그, 토너먼트 대진표, 라운드 로빈 토너먼트를 만드세요. 점수를 기록하고, 순위를 확인하고, 결과를 공유하세요.',
    nav_back: '← Sogepps',
    nav_features: '기능',
    nav_privacy: '개인정보 처리방침',
    nav_delete: '계정 삭제',
    hero_badge: '🏆 #1 토너먼트 오거나이저',
    hero_title: '토너먼트를 만드세요<br /><span class="grad">프로처럼</span>',
    hero_desc: '1분 이내에 리그, 토너먼트 대진표, 라운드 로빈 토너먼트를 설정하세요. 점수를 입력하고, 실시간 순위를 추적하고, 결과를 공유하세요 — 모두 휴대폰에서.',
    btn_google_play: 'Google Play에서 다운로드',
    btn_see_features: '기능 보기 ↓',
    feat_label: '◆ 기능',
    feat_title: '조직에 필요한 모든 것',
    feat_desc: '모든 토너먼트 형식을 위한 강력한 도구, 주머니 속에.',
    feat1_title: '리그 & 라운드 로빈',
    feat1_desc: '싱글 또는 더블 라운드 지원으로 라운드 로빈 리그를 만드세요. 리그당 최대 20팀의 경기 설정을 사용자 지정하세요.',
    feat2_title: '토너먼트 대진표',
    feat2_desc: '2~32명 참가자를 위한 싱글 엘리미네이션 대진표. 홀수 참가자를 위한 BYE 지원으로 자동 크기 조정.',
    feat3_title: '실시간 순위 & 내보내기',
    feat3_desc: '포인트, 골, 승, 무, 패가 포함된 실시간 순위표. PDF, CSV로 내보내거나 스크린샷으로 공유.',
    feat4_title: '다양한 스포츠',
    feat4_desc: '축구, 농구, 배구, 테니스 및 사용자 정의 스포츠에 대한 기본 지원. 스포츠별 점수 규칙 포함.',
    feat5_title: '개인정보 보호 중심',
    feat5_desc: '개인 데이터를 수집하지 않습니다. 추적 없음. 토너먼트는 여러분의 것입니다. 사용자 동의 관리를 통한 완전한 GDPR 준수.',
    feat6_title: '16개 이상의 언어',
    feat6_desc: '터키어, 영어, 독일어, 프랑스어, 스페인어, 이탈리아어, 포르투갈어, 네덜란드어, 러시아어, 일본어, 한국어, 아랍어 등으로 제공.',
    how_label: '◆ 사용 방법',
    how_title: '세 가지 간단한 단계',
    step1_title: '형식 선택',
    step1_desc: '리그(라운드 로빈) 또는 토너먼트(엘리미네이션 대진표) 형식 중 선택하세요.',
    step2_title: '팀 추가',
    step2_desc: '팀 또는 선수 이름을 입력하세요. 대진표가 자동으로 생성됩니다.',
    step3_title: '플레이 & 추적',
    step3_desc: '경기하면서 점수를 입력하세요. 순위와 대진표가 실시간으로 업데이트됩니다.',
    cta_title: '조직할 준비가 되셨나요?',
    cta_desc: '앱을 다운로드하고 1분 이내에 첫 번째 토너먼트를 만드세요. 선택적 프리미엄 기능과 함께 무료로 사용.',
    cta_btn: 'Google Play에서 무료 다운로드',
    footer_brand: '리그 & 토너먼트 메이커',
    footer_by: '제작',
    footer_app: '앱',
    footer_google_play: 'Google Play',
    footer_features: '기능',
    footer_legal: '법적 고지',
    footer_privacy: '개인정보 처리방침',
    footer_delete: '계정 삭제',
    footer_contact: '문의',
    footer_rights: '© 2026',
  },
  ar: {
    _title: 'صانع الدوريات والبطولات – أنشئ بطولات بسهولة',
    _description: 'أنشئ دوريات وجداول خروج المغلوب وبطولات دورية في ثوانٍ. سجّل النتائج، تابع الترتيب، شارك النتائج.',
    nav_back: '← Sogepps',
    nav_features: 'المميزات',
    nav_privacy: 'سياسة الخصوصية',
    nav_delete: 'حذف الحساب',
    hero_badge: '🏆 #1 منظم البطولات',
    hero_title: 'أنشئ بطولات<br /><span class="grad">كالمحترفين</span>',
    hero_desc: 'أنشئ دوريات وجداول خروج المغلوب وبطولات دورية في أقل من دقيقة. أدخل النتائج، تابع الترتيب المباشر، وشارك النتائج — كل ذلك من هاتفك.',
    btn_google_play: 'احصل عليه من Google Play',
    btn_see_features: 'شاهد المميزات ↓',
    feat_label: '◆ المميزات',
    feat_title: 'كل ما تحتاجه للتنظيم',
    feat_desc: 'أدوات قوية لأي تنسيق بطولة، مباشرة في جيبك.',
    feat1_title: 'الدوري والدوري الكامل',
    feat1_desc: 'أنشئ دوريات دورية بدعم جولة واحدة أو جولتين. خصّص إعدادات المباراة لما يصل إلى 20 فريقًا في الدوري.',
    feat2_title: 'جداول خروج المغلوب',
    feat2_desc: 'جداول إقصاء فردي لـ 2 إلى 32 مشاركًا. تحجيم تلقائي للجدول مع دعم BYE للأعداد الفردية.',
    feat3_title: 'ترتيب مباشر وتصدير',
    feat3_desc: 'ترتيب في الوقت الفعلي مع النقاط والأهداف والانتصارات والتعادلات والخسائر. تصدير كـ PDF أو CSV أو مشاركة كلقطة شاشة.',
    feat4_title: 'رياضات متعددة',
    feat4_desc: 'دعم مدمج لكرة القدم وكرة السلة والكرة الطائرة والتنس والرياضات المخصصة. قواعد تسجيل خاصة بكل رياضة مضمنة.',
    feat5_title: 'التركيز على الخصوصية',
    feat5_desc: 'لا يتم جمع بيانات شخصية. لا تتبع. بطولاتك تبقى لك. امتثال كامل لـ GDPR مع إدارة موافقة المستخدم.',
    feat6_title: '16+ لغة',
    feat6_desc: 'متوفر بالتركية والإنجليزية والألمانية والفرنسية والإسبانية والإيطالية والبرتغالية والهولندية والروسية واليابانية والكورية والعربية والمزيد.',
    how_label: '◆ كيف يعمل',
    how_title: 'ثلاث خطوات بسيطة',
    step1_title: 'اختر التنسيق',
    step1_desc: 'اختر بين الدوري (دوري كامل) أو خروج المغلوب (جدول إقصائي).',
    step2_title: 'أضف الفرق',
    step2_desc: 'أدخل أسماء الفرق أو اللاعبين. يتم إنشاء الجدول تلقائيًا.',
    step3_title: 'العب وتابع',
    step3_desc: 'أدخل نتائج المباريات أثناء اللعب. يتم تحديث الترتيب والجداول في الوقت الفعلي.',
    cta_title: 'مستعد للتنظيم؟',
    cta_desc: 'حمّل التطبيق وأنشئ أول بطولة لك في أقل من دقيقة. مجاني مع ميزات مميزة اختيارية.',
    cta_btn: 'تحميل مجاني من Google Play',
    footer_brand: 'صانع الدوريات والبطولات',
    footer_by: 'بواسطة',
    footer_app: 'التطبيق',
    footer_google_play: 'Google Play',
    footer_features: 'المميزات',
    footer_legal: 'قانوني',
    footer_privacy: 'سياسة الخصوصية',
    footer_delete: 'حذف الحساب',
    footer_contact: 'اتصل بنا',
    footer_rights: '© 2026',
  },
  hi: {
    _title: 'लीग और टूर्नामेंट मेकर – आसानी से टूर्नामेंट बनाएं',
    _description: 'सेकंडों में लीग, नॉकआउट ब्रैकेट और राउंड-रॉबिन टूर्नामेंट बनाएं। स्कोर दर्ज करें, स्टैंडिंग देखें, परिणाम साझा करें।',
    nav_back: '← Sogepps',
    nav_features: 'विशेषताएं',
    nav_privacy: 'गोपनीयता नीति',
    nav_delete: 'खाता हटाएं',
    hero_badge: '🏆 #1 टूर्नामेंट आयोजक',
    hero_title: 'टूर्नामेंट बनाएं<br /><span class="grad">प्रो की तरह</span>',
    hero_desc: 'एक मिनट से कम समय में लीग, नॉकआउट ब्रैकेट और राउंड-रॉबिन टूर्नामेंट सेट करें। स्कोर दर्ज करें, लाइव स्टैंडिंग ट्रैक करें और परिणाम साझा करें — सब कुछ अपने फोन से।',
    btn_google_play: 'Google Play पर डाउनलोड करें',
    btn_see_features: 'विशेषताएं देखें ↓',
    feat_label: '◆ विशेषताएं',
    feat_title: 'आयोजन के लिए आपको जो कुछ भी चाहिए',
    feat_desc: 'किसी भी टूर्नामेंट प्रारूप के लिए शक्तिशाली उपकरण, सीधे आपकी जेब में।',
    feat1_title: 'लीग और राउंड-रॉबिन',
    feat1_desc: 'सिंगल या डबल राउंड सपोर्ट के साथ राउंड-रॉबिन लीग बनाएं। प्रति लीग 20 टीमों तक के लिए मैच सेटिंग्स कस्टमाइज़ करें।',
    feat2_title: 'नॉकआउट ब्रैकेट',
    feat2_desc: '2 से 32 प्रतिभागियों के लिए सिंगल-एलिमिनेशन ब्रैकेट। विषम संख्याओं के लिए BYE सपोर्ट के साथ ऑटोमैटिक ब्रैकेट साइज़िंग।',
    feat3_title: 'लाइव स्टैंडिंग और एक्सपोर्ट',
    feat3_desc: 'अंक, गोल, जीत, ड्रॉ और हार के साथ रियल-टाइम स्टैंडिंग। PDF, CSV के रूप में एक्सपोर्ट करें या स्क्रीनशॉट इमेज के रूप में शेयर करें।',
    feat4_title: 'एकाधिक खेल',
    feat4_desc: 'फुटबॉल, बास्केटबॉल, वॉलीबॉल, टेनिस और कस्टम खेलों के लिए बिल्ट-इन सपोर्ट। खेल-विशिष्ट स्कोरिंग नियम शामिल।',
    feat5_title: 'गोपनीयता केंद्रित',
    feat5_desc: 'कोई व्यक्तिगत डेटा एकत्र नहीं किया जाता। कोई ट्रैकिंग नहीं। आपके टूर्नामेंट आपके रहते हैं। उपयोगकर्ता सहमति प्रबंधन के साथ पूर्ण GDPR अनुपालन।',
    feat6_title: '16+ भाषाएं',
    feat6_desc: 'तुर्की, अंग्रेजी, जर्मन, फ्रेंच, स्पेनिश, इतालवी, पुर्तगाली, डच, रूसी, जापानी, कोरियाई, अरबी और अधिक में उपलब्ध।',
    how_label: '◆ यह कैसे काम करता है',
    how_title: 'तीन सरल चरण',
    step1_title: 'प्रारूप चुनें',
    step1_desc: 'लीग (राउंड-रॉबिन) या नॉकआउट (एलिमिनेशन ब्रैकेट) प्रारूप में से चुनें।',
    step2_title: 'टीमें जोड़ें',
    step2_desc: 'टीम या खिलाड़ी के नाम दर्ज करें। फिक्स्चर स्वचालित रूप से बनता है।',
    step3_title: 'खेलें और ट्रैक करें',
    step3_desc: 'खेलते समय मैच स्कोर दर्ज करें। स्टैंडिंग और ब्रैकेट रियल टाइम में अपडेट होते हैं।',
    cta_title: 'आयोजन के लिए तैयार हैं?',
    cta_desc: 'ऐप डाउनलोड करें और एक मिनट से कम समय में अपना पहला टूर्नामेंट बनाएं। वैकल्पिक प्रीमियम सुविधाओं के साथ मुफ्त उपयोग करें।',
    cta_btn: 'Google Play पर मुफ्त डाउनलोड करें',
    footer_brand: 'लीग और टूर्नामेंट मेकर',
    footer_by: 'द्वारा',
    footer_app: 'ऐप',
    footer_google_play: 'Google Play',
    footer_features: 'विशेषताएं',
    footer_legal: 'कानूनी',
    footer_privacy: 'गोपनीयता नीति',
    footer_delete: 'खाता हटाएं',
    footer_contact: 'संपर्क',
    footer_rights: '© 2026',
  },
  id: {
    _title: 'Pembuat Liga & Turnamen – Buat Turnamen dengan Mudah',
    _description: 'Buat liga, bagan eliminasi, dan turnamen round-robin dalam hitungan detik. Catat skor, lihat klasemen, bagikan hasil.',
    nav_back: '← Sogepps',
    nav_features: 'Fitur',
    nav_privacy: 'Kebijakan Privasi',
    nav_delete: 'Hapus Akun',
    hero_badge: '🏆 #1 Penyelenggara Turnamen',
    hero_title: 'Buat Turnamen<br /><span class="grad">Seperti Profesional</span>',
    hero_desc: 'Siapkan liga, bagan eliminasi, dan turnamen round-robin dalam waktu kurang dari satu menit. Masukkan skor, pantau klasemen langsung, dan bagikan hasil — semuanya dari ponsel Anda.',
    btn_google_play: 'Dapatkan di Google Play',
    btn_see_features: 'Lihat Fitur ↓',
    feat_label: '◆ Fitur',
    feat_title: 'Semua yang Anda Butuhkan untuk Mengorganisir',
    feat_desc: 'Alat canggih untuk format turnamen apa pun, langsung di saku Anda.',
    feat1_title: 'Liga & Round-Robin',
    feat1_desc: 'Buat liga round-robin dengan dukungan putaran tunggal atau ganda. Sesuaikan pengaturan pertandingan untuk hingga 20 tim per liga.',
    feat2_title: 'Bagan Eliminasi',
    feat2_desc: 'Bagan eliminasi tunggal untuk 2 hingga 32 peserta. Ukuran bagan otomatis dengan dukungan BYE untuk jumlah ganjil.',
    feat3_title: 'Klasemen Langsung & Ekspor',
    feat3_desc: 'Klasemen real-time dengan poin, gol, kemenangan, seri, dan kekalahan. Ekspor sebagai PDF, CSV, atau bagikan sebagai tangkapan layar.',
    feat4_title: 'Berbagai Olahraga',
    feat4_desc: 'Dukungan bawaan untuk sepak bola, bola basket, bola voli, tenis, dan olahraga kustom. Aturan penilaian khusus olahraga disertakan.',
    feat5_title: 'Berfokus pada Privasi',
    feat5_desc: 'Tidak ada data pribadi yang dikumpulkan. Tanpa pelacakan. Turnamen Anda tetap milik Anda. Kepatuhan GDPR penuh dengan manajemen persetujuan pengguna.',
    feat6_title: '16+ Bahasa',
    feat6_desc: 'Tersedia dalam bahasa Turki, Inggris, Jerman, Prancis, Spanyol, Italia, Portugis, Belanda, Rusia, Jepang, Korea, Arab, dan lainnya.',
    how_label: '◆ Cara Kerja',
    how_title: 'Tiga Langkah Sederhana',
    step1_title: 'Pilih Format',
    step1_desc: 'Pilih antara liga (round-robin) atau eliminasi (bagan eliminasi) format.',
    step2_title: 'Tambah Tim',
    step2_desc: 'Masukkan nama tim atau pemain. Jadwal pertandingan dibuat secara otomatis.',
    step3_title: 'Main & Pantau',
    step3_desc: 'Masukkan skor pertandingan saat bermain. Klasemen dan bagan diperbarui secara real-time.',
    cta_title: 'Siap Mengorganisir?',
    cta_desc: 'Unduh aplikasi dan buat turnamen pertama Anda dalam waktu kurang dari satu menit. Gratis digunakan dengan fitur premium opsional.',
    cta_btn: 'Unduh Gratis di Google Play',
    footer_brand: 'Pembuat Liga & Turnamen',
    footer_by: 'oleh',
    footer_app: 'Aplikasi',
    footer_google_play: 'Google Play',
    footer_features: 'Fitur',
    footer_legal: 'Hukum',
    footer_privacy: 'Kebijakan Privasi',
    footer_delete: 'Hapus Akun',
    footer_contact: 'Kontak',
    footer_rights: '© 2026',
  },
  pl: {
    _title: 'Kreator Lig i Turniejów – Twórz turnieje z łatwością',
    _description: 'Twórz ligi, drabinki pucharowe i turnieje każdy z każdym w kilka sekund. Zapisuj wyniki, sprawdzaj tabele, udostępniaj rezultaty.',
    nav_back: '← Sogepps',
    nav_features: 'Funkcje',
    nav_privacy: 'Polityka prywatności',
    nav_delete: 'Usuń konto',
    hero_badge: '🏆 #1 Organizator turniejów',
    hero_title: 'Twórz turnieje<br /><span class="grad">Jak profesjonalista</span>',
    hero_desc: 'Skonfiguruj ligi, drabinki pucharowe i turnieje każdy z każdym w mniej niż minutę. Wprowadzaj wyniki, śledź tabele na żywo i udostępniaj rezultaty — wszystko z telefonu.',
    btn_google_play: 'Pobierz z Google Play',
    btn_see_features: 'Zobacz funkcje ↓',
    feat_label: '◆ Funkcje',
    feat_title: 'Wszystko, czego potrzebujesz do organizacji',
    feat_desc: 'Potężne narzędzia do każdego formatu turnieju, prosto w Twojej kieszeni.',
    feat1_title: 'Liga i każdy z każdym',
    feat1_desc: 'Twórz ligi każdy z każdym z obsługą jednej lub dwóch rund. Dostosuj ustawienia meczów dla maksymalnie 20 drużyn na ligę.',
    feat2_title: 'Drabinki pucharowe',
    feat2_desc: 'Drabinki eliminacji pojedynczej dla 2 do 32 uczestników. Automatyczne dopasowanie rozmiaru drabinki z obsługą BYE dla nieparzystych liczb.',
    feat3_title: 'Tabele na żywo i eksport',
    feat3_desc: 'Tabele w czasie rzeczywistym z punktami, bramkami, wygranymi, remisami i przegranymi. Eksportuj jako PDF, CSV lub udostępnij jako zrzut ekranu.',
    feat4_title: 'Wiele dyscyplin sportowych',
    feat4_desc: 'Wbudowane wsparcie dla piłki nożnej, koszykówki, siatkówki, tenisa i sportów niestandardowych. Reguły punktacji specyficzne dla danego sportu.',
    feat5_title: 'Skupienie na prywatności',
    feat5_desc: 'Żadne dane osobowe nie są zbierane. Bez śledzenia. Twoje turnieje pozostają Twoje. Pełna zgodność z RODO z zarządzaniem zgodami użytkowników.',
    feat6_title: '16+ Języków',
    feat6_desc: 'Dostępny w tureckim, angielskim, niemieckim, francuskim, hiszpańskim, włoskim, portugalskim, niderlandzkim, rosyjskim, japońskim, koreańskim, arabskim i innych.',
    how_label: '◆ Jak to działa',
    how_title: 'Trzy proste kroki',
    step1_title: 'Wybierz format',
    step1_desc: 'Wybierz między ligą (każdy z każdym) a pucharem (drabinka eliminacyjna).',
    step2_title: 'Dodaj drużyny',
    step2_desc: 'Wprowadź nazwy drużyn lub zawodników. Terminarz jest generowany automatycznie.',
    step3_title: 'Graj i śledź',
    step3_desc: 'Wprowadzaj wyniki meczów w trakcie gry. Tabele i drabinki aktualizują się w czasie rzeczywistym.',
    cta_title: 'Gotowy do organizacji?',
    cta_desc: 'Pobierz aplikację i stwórz swój pierwszy turniej w mniej niż minutę. Darmowa z opcjonalnymi funkcjami premium.',
    cta_btn: 'Pobierz za darmo z Google Play',
    footer_brand: 'Kreator Lig i Turniejów',
    footer_by: 'od',
    footer_app: 'Aplikacja',
    footer_google_play: 'Google Play',
    footer_features: 'Funkcje',
    footer_legal: 'Informacje prawne',
    footer_privacy: 'Polityka prywatności',
    footer_delete: 'Usuń konto',
    footer_contact: 'Kontakt',
    footer_rights: '© 2026',
  },
};
