var DELETE_TRANSLATIONS = {
  en: {
    _title: 'Delete Account – League & Tournament Maker',
    _description: 'Permanently delete your League & Tournament Maker account and all associated data.',
    nav_back: '← Tournament Maker',
    nav_privacy: 'Privacy Policy',
    nav_delete: 'Delete Account',
    title: 'Delete Account',
    subtitle: 'Sign in with your email and password, then type the confirmation phrase to permanently delete your account and all associated data.',
    info1_title: 'What will be deleted',
    info1_li1: 'Account profile information',
    info1_li2: 'Authentication credentials linked to the account',
    info1_li3: 'User-created tournament and league records',
    info1_li4: 'Any user-associated app preferences and settings',
    info2_title: 'Data retention',
    info2_desc: 'All personal data is permanently deleted after account deletion. No personal data is retained. We do not keep any copy of your data; there is no retention period after deletion.',
    info3_title: 'Deletion timing',
    info3_desc: 'Deletion is processed immediately after successful confirmation. Your account and data are removed as soon as you complete the form.',
    label_email: 'Email',
    label_password: 'Password',
    label_confirm: 'Confirmation phrase',
    placeholder_email: 'you@example.com',
    placeholder_confirm: 'I confirm',
    hint: 'You must type exactly <strong>I confirm</strong> (in English, case-insensitive). This action is permanent and cannot be undone.',
    btn_delete: 'Delete my account',
    btn_loading: 'Please wait…',
    msg_invalid: 'Invalid email or password. Please try again.',
    msg_wrong_phrase: 'Confirmation phrase is incorrect. Please type exactly: I confirm',
    msg_api_error: 'We could not complete account deletion right now. Please try again later.',
    msg_success: 'Your account deletion request was completed successfully.\nDeleted data: account profile, authentication credentials, and all tournament/league records linked to this account.',
    footer_brand: 'League & Tournament Maker',
    footer_by: 'by',
    footer_support: 'Support:',
  },
  tr: {
    _title: 'Hesap Sil – Lig ve Turnuva Oluşturucu',
    _description: 'Lig ve Turnuva Oluşturucu hesabınızı ve tüm ilişkili verileri kalıcı olarak silin.',
    nav_back: '← Turnuva Oluşturucu',
    nav_privacy: 'Gizlilik Politikası',
    nav_delete: 'Hesap Sil',
    title: 'Hesap Sil',
    subtitle: 'E-posta ve şifrenizle giriş yapın, ardından hesabınızı ve tüm ilişkili verileri kalıcı olarak silmek için onay ifadesini yazın.',
    info1_title: 'Silinecekler',
    info1_li1: 'Hesap profil bilgileri',
    info1_li2: 'Hesaba bağlı kimlik doğrulama bilgileri',
    info1_li3: 'Kullanıcının oluşturduğu turnuva ve lig kayıtları',
    info1_li4: 'Kullanıcıya ait uygulama tercihleri ve ayarları',
    info2_title: 'Veri saklama',
    info2_desc: 'Hesap silindikten sonra tüm kişisel veriler kalıcı olarak silinir. Hiçbir kişisel veri saklanmaz. Verilerinizin hiçbir kopyasını tutmuyoruz; silme sonrası saklama süresi yoktur.',
    info3_title: 'Silme zamanlaması',
    info3_desc: 'Silme işlemi başarılı onaydan hemen sonra gerçekleştirilir. Formu tamamlar tamamlamaz hesabınız ve verileriniz kaldırılır.',
    label_email: 'E-posta',
    label_password: 'Şifre',
    label_confirm: 'Onay ifadesi',
    placeholder_email: 'ornek@email.com',
    placeholder_confirm: 'I confirm',
    hint: 'Tam olarak <strong>I confirm</strong> yazmalısınız (İngilizce, büyük/küçük harf duyarsız). Bu işlem kalıcıdır ve geri alınamaz.',
    btn_delete: 'Hesabımı sil',
    btn_loading: 'Lütfen bekleyin…',
    msg_invalid: 'Geçersiz e-posta veya şifre. Lütfen tekrar deneyin.',
    msg_wrong_phrase: 'Onay ifadesi yanlış. Lütfen tam olarak yazın: I confirm',
    msg_api_error: 'Hesap silme şu anda tamamlanamadı. Lütfen daha sonra tekrar deneyin.',
    msg_success: 'Hesap silme talebiniz başarıyla tamamlandı.\nSilinen veriler: hesap profili, kimlik doğrulama bilgileri ve bu hesaba bağlı tüm turnuva/lig kayıtları.',
    footer_brand: 'Lig ve Turnuva Oluşturucu',
    footer_by: 'yapımcı',
    footer_support: 'Destek:',
  },
  de: {
    _title: 'Konto löschen – Liga- & Turnier-Ersteller',
    _description: 'Löschen Sie Ihr Liga- & Turnier-Ersteller-Konto und alle zugehörigen Daten dauerhaft.',
    nav_back: '← Turnier-Ersteller',
    nav_privacy: 'Datenschutzrichtlinie',
    nav_delete: 'Konto löschen',
    title: 'Konto löschen',
    subtitle: 'Melden Sie sich mit Ihrer E-Mail-Adresse und Ihrem Passwort an und geben Sie dann die Bestätigungsphrase ein, um Ihr Konto und alle zugehörigen Daten dauerhaft zu löschen.',
    info1_title: 'Was gelöscht wird',
    info1_li1: 'Kontoprofilinformationen',
    info1_li2: 'Mit dem Konto verknüpfte Anmeldedaten',
    info1_li3: 'Vom Benutzer erstellte Turnier- und Ligaeinträge',
    info1_li4: 'Alle benutzerbezogenen App-Einstellungen und Präferenzen',
    info2_title: 'Datenaufbewahrung',
    info2_desc: 'Alle personenbezogenen Daten werden nach der Kontolöschung dauerhaft gelöscht. Es werden keine personenbezogenen Daten aufbewahrt. Wir bewahren keine Kopie Ihrer Daten auf; es gibt keine Aufbewahrungsfrist nach der Löschung.',
    info3_title: 'Zeitpunkt der Löschung',
    info3_desc: 'Die Löschung wird sofort nach erfolgreicher Bestätigung durchgeführt. Ihr Konto und Ihre Daten werden entfernt, sobald Sie das Formular abgeschlossen haben.',
    label_email: 'E-Mail',
    label_password: 'Passwort',
    label_confirm: 'Bestätigungsphrase',
    placeholder_email: 'name@beispiel.de',
    placeholder_confirm: 'I confirm',
    hint: 'Sie müssen genau <strong>I confirm</strong> eingeben (auf Englisch, Groß-/Kleinschreibung wird nicht berücksichtigt). Diese Aktion ist dauerhaft und kann nicht rückgängig gemacht werden.',
    btn_delete: 'Mein Konto löschen',
    btn_loading: 'Bitte warten…',
    msg_invalid: 'Ungültige E-Mail oder ungültiges Passwort. Bitte versuchen Sie es erneut.',
    msg_wrong_phrase: 'Die Bestätigungsphrase ist falsch. Bitte geben Sie genau ein: I confirm',
    msg_api_error: 'Die Kontolöschung konnte derzeit nicht abgeschlossen werden. Bitte versuchen Sie es später erneut.',
    msg_success: 'Ihre Kontolöschungsanfrage wurde erfolgreich abgeschlossen.\nGelöschte Daten: Kontoprofil, Anmeldedaten und alle mit diesem Konto verknüpften Turnier-/Ligaeinträge.',
    footer_brand: 'Liga- & Turnier-Ersteller',
    footer_by: 'von',
    footer_support: 'Support:',
  },
  fr: {
    _title: 'Supprimer le compte – Créateur de Ligues et Tournois',
    _description: 'Supprimez définitivement votre compte Créateur de Ligues et Tournois et toutes les données associées.',
    nav_back: '← Créateur de Tournois',
    nav_privacy: 'Politique de confidentialité',
    nav_delete: 'Supprimer le compte',
    title: 'Supprimer le compte',
    subtitle: 'Connectez-vous avec votre adresse e-mail et votre mot de passe, puis saisissez la phrase de confirmation pour supprimer définitivement votre compte et toutes les données associées.',
    info1_title: 'Ce qui sera supprimé',
    info1_li1: 'Informations du profil du compte',
    info1_li2: 'Identifiants d\'authentification liés au compte',
    info1_li3: 'Enregistrements de tournois et de ligues créés par l\'utilisateur',
    info1_li4: 'Toutes les préférences et paramètres de l\'application associés à l\'utilisateur',
    info2_title: 'Conservation des données',
    info2_desc: 'Toutes les données personnelles sont définitivement supprimées après la suppression du compte. Aucune donnée personnelle n\'est conservée. Nous ne conservons aucune copie de vos données ; il n\'y a pas de période de conservation après la suppression.',
    info3_title: 'Délai de suppression',
    info3_desc: 'La suppression est traitée immédiatement après une confirmation réussie. Votre compte et vos données sont supprimés dès que vous avez rempli le formulaire.',
    label_email: 'E-mail',
    label_password: 'Mot de passe',
    label_confirm: 'Phrase de confirmation',
    placeholder_email: 'vous@exemple.com',
    placeholder_confirm: 'I confirm',
    hint: 'Vous devez saisir exactement <strong>I confirm</strong> (en anglais, insensible à la casse). Cette action est permanente et ne peut pas être annulée.',
    btn_delete: 'Supprimer mon compte',
    btn_loading: 'Veuillez patienter…',
    msg_invalid: 'E-mail ou mot de passe invalide. Veuillez réessayer.',
    msg_wrong_phrase: 'La phrase de confirmation est incorrecte. Veuillez saisir exactement : I confirm',
    msg_api_error: 'Nous n\'avons pas pu terminer la suppression du compte pour le moment. Veuillez réessayer plus tard.',
    msg_success: 'Votre demande de suppression de compte a été traitée avec succès.\nDonnées supprimées : profil du compte, identifiants d\'authentification et tous les enregistrements de tournois/ligues liés à ce compte.',
    footer_brand: 'Créateur de Ligues et Tournois',
    footer_by: 'par',
    footer_support: 'Assistance :',
  },
  es: {
    _title: 'Eliminar cuenta – Creador de Ligas y Torneos',
    _description: 'Elimine permanentemente su cuenta de Creador de Ligas y Torneos y todos los datos asociados.',
    nav_back: '← Creador de Torneos',
    nav_privacy: 'Política de privacidad',
    nav_delete: 'Eliminar cuenta',
    title: 'Eliminar cuenta',
    subtitle: 'Inicie sesión con su correo electrónico y contraseña, luego escriba la frase de confirmación para eliminar permanentemente su cuenta y todos los datos asociados.',
    info1_title: 'Qué se eliminará',
    info1_li1: 'Información del perfil de la cuenta',
    info1_li2: 'Credenciales de autenticación vinculadas a la cuenta',
    info1_li3: 'Registros de torneos y ligas creados por el usuario',
    info1_li4: 'Todas las preferencias y configuraciones de la aplicación asociadas al usuario',
    info2_title: 'Retención de datos',
    info2_desc: 'Todos los datos personales se eliminan permanentemente después de la eliminación de la cuenta. No se conservan datos personales. No guardamos ninguna copia de sus datos; no hay período de retención después de la eliminación.',
    info3_title: 'Plazo de eliminación',
    info3_desc: 'La eliminación se procesa inmediatamente después de una confirmación exitosa. Su cuenta y sus datos se eliminan tan pronto como complete el formulario.',
    label_email: 'Correo electrónico',
    label_password: 'Contraseña',
    label_confirm: 'Frase de confirmación',
    placeholder_email: 'tu@ejemplo.com',
    placeholder_confirm: 'I confirm',
    hint: 'Debe escribir exactamente <strong>I confirm</strong> (en inglés, sin distinguir mayúsculas y minúsculas). Esta acción es permanente y no se puede deshacer.',
    btn_delete: 'Eliminar mi cuenta',
    btn_loading: 'Por favor espere…',
    msg_invalid: 'Correo electrónico o contraseña no válidos. Por favor, inténtelo de nuevo.',
    msg_wrong_phrase: 'La frase de confirmación es incorrecta. Escriba exactamente: I confirm',
    msg_api_error: 'No pudimos completar la eliminación de la cuenta en este momento. Por favor, inténtelo más tarde.',
    msg_success: 'Su solicitud de eliminación de cuenta se completó con éxito.\nDatos eliminados: perfil de la cuenta, credenciales de autenticación y todos los registros de torneos/ligas vinculados a esta cuenta.',
    footer_brand: 'Creador de Ligas y Torneos',
    footer_by: 'por',
    footer_support: 'Soporte:',
  },
  it: {
    _title: 'Elimina account – Creatore di Leghe e Tornei',
    _description: 'Elimina definitivamente il tuo account Creatore di Leghe e Tornei e tutti i dati associati.',
    nav_back: '← Creatore di Tornei',
    nav_privacy: 'Informativa sulla privacy',
    nav_delete: 'Elimina account',
    title: 'Elimina account',
    subtitle: 'Accedi con la tua email e password, quindi digita la frase di conferma per eliminare definitivamente il tuo account e tutti i dati associati.',
    info1_title: 'Cosa verrà eliminato',
    info1_li1: 'Informazioni del profilo dell\'account',
    info1_li2: 'Credenziali di autenticazione collegate all\'account',
    info1_li3: 'Record di tornei e leghe creati dall\'utente',
    info1_li4: 'Tutte le preferenze e impostazioni dell\'app associate all\'utente',
    info2_title: 'Conservazione dei dati',
    info2_desc: 'Tutti i dati personali vengono eliminati definitivamente dopo la cancellazione dell\'account. Nessun dato personale viene conservato. Non conserviamo alcuna copia dei tuoi dati; non esiste un periodo di conservazione dopo l\'eliminazione.',
    info3_title: 'Tempistica di eliminazione',
    info3_desc: 'L\'eliminazione viene elaborata immediatamente dopo la conferma avvenuta con successo. Il tuo account e i tuoi dati vengono rimossi non appena completi il modulo.',
    label_email: 'Email',
    label_password: 'Password',
    label_confirm: 'Frase di conferma',
    placeholder_email: 'tu@esempio.com',
    placeholder_confirm: 'I confirm',
    hint: 'Devi digitare esattamente <strong>I confirm</strong> (in inglese, senza distinzione tra maiuscole e minuscole). Questa azione è permanente e non può essere annullata.',
    btn_delete: 'Elimina il mio account',
    btn_loading: 'Attendere prego…',
    msg_invalid: 'Email o password non validi. Per favore riprova.',
    msg_wrong_phrase: 'La frase di conferma non è corretta. Digita esattamente: I confirm',
    msg_api_error: 'Non è stato possibile completare l\'eliminazione dell\'account in questo momento. Riprova più tardi.',
    msg_success: 'La tua richiesta di eliminazione dell\'account è stata completata con successo.\nDati eliminati: profilo dell\'account, credenziali di autenticazione e tutti i record di tornei/leghe collegati a questo account.',
    footer_brand: 'Creatore di Leghe e Tornei',
    footer_by: 'di',
    footer_support: 'Supporto:',
  },
  pt: {
    _title: 'Excluir conta – Criador de Ligas e Torneios',
    _description: 'Exclua permanentemente sua conta do Criador de Ligas e Torneios e todos os dados associados.',
    nav_back: '← Criador de Torneios',
    nav_privacy: 'Política de Privacidade',
    nav_delete: 'Excluir conta',
    title: 'Excluir conta',
    subtitle: 'Faça login com seu e-mail e senha, depois digite a frase de confirmação para excluir permanentemente sua conta e todos os dados associados.',
    info1_title: 'O que será excluído',
    info1_li1: 'Informações do perfil da conta',
    info1_li2: 'Credenciais de autenticação vinculadas à conta',
    info1_li3: 'Registros de torneios e ligas criados pelo usuário',
    info1_li4: 'Todas as preferências e configurações do aplicativo associadas ao usuário',
    info2_title: 'Retenção de dados',
    info2_desc: 'Todos os dados pessoais são excluídos permanentemente após a exclusão da conta. Nenhum dado pessoal é retido. Não mantemos nenhuma cópia dos seus dados; não há período de retenção após a exclusão.',
    info3_title: 'Prazo de exclusão',
    info3_desc: 'A exclusão é processada imediatamente após a confirmação bem-sucedida. Sua conta e seus dados são removidos assim que você preencher o formulário.',
    label_email: 'E-mail',
    label_password: 'Senha',
    label_confirm: 'Frase de confirmação',
    placeholder_email: 'voce@exemplo.com',
    placeholder_confirm: 'I confirm',
    hint: 'Você deve digitar exatamente <strong>I confirm</strong> (em inglês, sem distinção entre maiúsculas e minúsculas). Esta ação é permanente e não pode ser desfeita.',
    btn_delete: 'Excluir minha conta',
    btn_loading: 'Por favor, aguarde…',
    msg_invalid: 'E-mail ou senha inválidos. Por favor, tente novamente.',
    msg_wrong_phrase: 'A frase de confirmação está incorreta. Digite exatamente: I confirm',
    msg_api_error: 'Não foi possível concluir a exclusão da conta no momento. Por favor, tente novamente mais tarde.',
    msg_success: 'Sua solicitação de exclusão de conta foi concluída com sucesso.\nDados excluídos: perfil da conta, credenciais de autenticação e todos os registros de torneios/ligas vinculados a esta conta.',
    footer_brand: 'Criador de Ligas e Torneios',
    footer_by: 'por',
    footer_support: 'Suporte:',
  },
  nl: {
    _title: 'Account verwijderen – Liga- & Toernooimaker',
    _description: 'Verwijder uw Liga- & Toernooimaker-account en alle bijbehorende gegevens permanent.',
    nav_back: '← Toernooimaker',
    nav_privacy: 'Privacybeleid',
    nav_delete: 'Account verwijderen',
    title: 'Account verwijderen',
    subtitle: 'Log in met uw e-mailadres en wachtwoord en typ vervolgens de bevestigingszin om uw account en alle bijbehorende gegevens permanent te verwijderen.',
    info1_title: 'Wat wordt verwijderd',
    info1_li1: 'Accountprofielinformatie',
    info1_li2: 'Aan het account gekoppelde inloggegevens',
    info1_li3: 'Door de gebruiker aangemaakte toernooi- en competitierecords',
    info1_li4: 'Alle aan de gebruiker gekoppelde app-voorkeuren en -instellingen',
    info2_title: 'Gegevensbewaring',
    info2_desc: 'Alle persoonlijke gegevens worden permanent verwijderd na het verwijderen van het account. Er worden geen persoonlijke gegevens bewaard. Wij bewaren geen kopie van uw gegevens; er is geen bewaartermijn na verwijdering.',
    info3_title: 'Tijdstip van verwijdering',
    info3_desc: 'De verwijdering wordt onmiddellijk verwerkt na succesvolle bevestiging. Uw account en gegevens worden verwijderd zodra u het formulier heeft ingevuld.',
    label_email: 'E-mail',
    label_password: 'Wachtwoord',
    label_confirm: 'Bevestigingszin',
    placeholder_email: 'u@voorbeeld.nl',
    placeholder_confirm: 'I confirm',
    hint: 'U moet exact <strong>I confirm</strong> typen (in het Engels, niet hoofdlettergevoelig). Deze actie is permanent en kan niet ongedaan worden gemaakt.',
    btn_delete: 'Mijn account verwijderen',
    btn_loading: 'Even geduld…',
    msg_invalid: 'Ongeldig e-mailadres of wachtwoord. Probeer het opnieuw.',
    msg_wrong_phrase: 'De bevestigingszin is onjuist. Typ exact: I confirm',
    msg_api_error: 'Het verwijderen van het account kon op dit moment niet worden voltooid. Probeer het later opnieuw.',
    msg_success: 'Uw verzoek tot accountverwijdering is succesvol voltooid.\nVerwijderde gegevens: accountprofiel, inloggegevens en alle toernooi-/competitierecords die aan dit account zijn gekoppeld.',
    footer_brand: 'Liga- & Toernooimaker',
    footer_by: 'door',
    footer_support: 'Ondersteuning:',
  },
  ru: {
    _title: 'Удалить аккаунт – Создатель Лиг и Турниров',
    _description: 'Удалите свой аккаунт Создателя Лиг и Турниров и все связанные данные навсегда.',
    nav_back: '← Создатель Турниров',
    nav_privacy: 'Политика конфиденциальности',
    nav_delete: 'Удалить аккаунт',
    title: 'Удалить аккаунт',
    subtitle: 'Войдите с помощью электронной почты и пароля, затем введите фразу подтверждения, чтобы навсегда удалить свой аккаунт и все связанные данные.',
    info1_title: 'Что будет удалено',
    info1_li1: 'Информация профиля аккаунта',
    info1_li2: 'Учётные данные для аутентификации, привязанные к аккаунту',
    info1_li3: 'Созданные пользователем записи турниров и лиг',
    info1_li4: 'Все пользовательские настройки и предпочтения приложения',
    info2_title: 'Хранение данных',
    info2_desc: 'Все персональные данные удаляются навсегда после удаления аккаунта. Никакие персональные данные не сохраняются. Мы не храним никаких копий ваших данных; срок хранения после удаления отсутствует.',
    info3_title: 'Сроки удаления',
    info3_desc: 'Удаление выполняется сразу после успешного подтверждения. Ваш аккаунт и данные удаляются, как только вы заполните форму.',
    label_email: 'Электронная почта',
    label_password: 'Пароль',
    label_confirm: 'Фраза подтверждения',
    placeholder_email: 'вы@пример.com',
    placeholder_confirm: 'I confirm',
    hint: 'Вы должны ввести точно <strong>I confirm</strong> (на английском, без учёта регистра). Это действие необратимо и не может быть отменено.',
    btn_delete: 'Удалить мой аккаунт',
    btn_loading: 'Пожалуйста, подождите…',
    msg_invalid: 'Неверный адрес электронной почты или пароль. Пожалуйста, попробуйте снова.',
    msg_wrong_phrase: 'Фраза подтверждения неверна. Пожалуйста, введите точно: I confirm',
    msg_api_error: 'Не удалось завершить удаление аккаунта в данный момент. Пожалуйста, попробуйте позже.',
    msg_success: 'Ваш запрос на удаление аккаунта успешно выполнен.\nУдалённые данные: профиль аккаунта, учётные данные для аутентификации и все записи турниров/лиг, связанные с этим аккаунтом.',
    footer_brand: 'Создатель Лиг и Турниров',
    footer_by: 'от',
    footer_support: 'Поддержка:',
  },
  ja: {
    _title: 'アカウント削除 – リーグ＆トーナメントメーカー',
    _description: 'リーグ＆トーナメントメーカーのアカウントと関連するすべてのデータを完全に削除します。',
    nav_back: '← トーナメントメーカー',
    nav_privacy: 'プライバシーポリシー',
    nav_delete: 'アカウント削除',
    title: 'アカウント削除',
    subtitle: 'メールアドレスとパスワードでログインし、確認フレーズを入力して、アカウントと関連するすべてのデータを完全に削除してください。',
    info1_title: '削除される内容',
    info1_li1: 'アカウントプロフィール情報',
    info1_li2: 'アカウントに紐付けられた認証情報',
    info1_li3: 'ユーザーが作成したトーナメントおよびリーグの記録',
    info1_li4: 'ユーザーに関連するすべてのアプリの設定と環境設定',
    info2_title: 'データの保持',
    info2_desc: 'アカウント削除後、すべての個人データは完全に削除されます。個人データは一切保持されません。データのコピーは保管しません。削除後の保持期間はありません。',
    info3_title: '削除のタイミング',
    info3_desc: '削除は確認が成功した直後に処理されます。フォームの送信が完了すると、アカウントとデータは即座に削除されます。',
    label_email: 'メールアドレス',
    label_password: 'パスワード',
    label_confirm: '確認フレーズ',
    placeholder_email: 'you@example.com',
    placeholder_confirm: 'I confirm',
    hint: '正確に <strong>I confirm</strong> と入力してください（英語、大文字小文字を区別しません）。この操作は永続的であり、元に戻すことはできません。',
    btn_delete: 'アカウントを削除',
    btn_loading: 'お待ちください…',
    msg_invalid: 'メールアドレスまたはパスワードが無効です。もう一度お試しください。',
    msg_wrong_phrase: '確認フレーズが正しくありません。正確に入力してください: I confirm',
    msg_api_error: '現在アカウントの削除を完了できませんでした。後でもう一度お試しください。',
    msg_success: 'アカウント削除リクエストが正常に完了しました。\n削除されたデータ: アカウントプロフィール、認証情報、このアカウントに紐付けられたすべてのトーナメント/リーグの記録。',
    footer_brand: 'リーグ＆トーナメントメーカー',
    footer_by: '作成者',
    footer_support: 'サポート:',
  },
  ko: {
    _title: '계정 삭제 – 리그 & 토너먼트 메이커',
    _description: '리그 & 토너먼트 메이커 계정과 모든 관련 데이터를 영구적으로 삭제합니다.',
    nav_back: '← 토너먼트 메이커',
    nav_privacy: '개인정보 처리방침',
    nav_delete: '계정 삭제',
    title: '계정 삭제',
    subtitle: '이메일과 비밀번호로 로그인한 후 확인 문구를 입력하여 계정과 모든 관련 데이터를 영구적으로 삭제하세요.',
    info1_title: '삭제될 항목',
    info1_li1: '계정 프로필 정보',
    info1_li2: '계정에 연결된 인증 자격 증명',
    info1_li3: '사용자가 생성한 토너먼트 및 리그 기록',
    info1_li4: '사용자 관련 앱 환경 설정 및 설정',
    info2_title: '데이터 보존',
    info2_desc: '계정 삭제 후 모든 개인 데이터가 영구적으로 삭제됩니다. 개인 데이터는 보존되지 않습니다. 데이터의 사본을 보관하지 않으며, 삭제 후 보존 기간이 없습니다.',
    info3_title: '삭제 시점',
    info3_desc: '삭제는 확인 성공 후 즉시 처리됩니다. 양식을 작성하는 즉시 계정과 데이터가 제거됩니다.',
    label_email: '이메일',
    label_password: '비밀번호',
    label_confirm: '확인 문구',
    placeholder_email: 'you@example.com',
    placeholder_confirm: 'I confirm',
    hint: '정확히 <strong>I confirm</strong>을 입력해야 합니다 (영어, 대소문자 구분 없음). 이 작업은 영구적이며 되돌릴 수 없습니다.',
    btn_delete: '내 계정 삭제',
    btn_loading: '잠시만 기다려 주세요…',
    msg_invalid: '잘못된 이메일 또는 비밀번호입니다. 다시 시도해 주세요.',
    msg_wrong_phrase: '확인 문구가 올바르지 않습니다. 정확히 입력해 주세요: I confirm',
    msg_api_error: '현재 계정 삭제를 완료할 수 없습니다. 나중에 다시 시도해 주세요.',
    msg_success: '계정 삭제 요청이 성공적으로 완료되었습니다.\n삭제된 데이터: 계정 프로필, 인증 자격 증명 및 이 계정에 연결된 모든 토너먼트/리그 기록.',
    footer_brand: '리그 & 토너먼트 메이커',
    footer_by: '제작',
    footer_support: '지원:',
  },
  ar: {
    _title: 'حذف الحساب – صانع الدوريات والبطولات',
    _description: 'احذف حسابك في صانع الدوريات والبطولات وجميع البيانات المرتبطة به نهائيًا.',
    nav_back: '← صانع البطولات',
    nav_privacy: 'سياسة الخصوصية',
    nav_delete: 'حذف الحساب',
    title: 'حذف الحساب',
    subtitle: 'قم بتسجيل الدخول باستخدام بريدك الإلكتروني وكلمة المرور، ثم اكتب عبارة التأكيد لحذف حسابك وجميع البيانات المرتبطة به نهائيًا.',
    info1_title: 'ما سيتم حذفه',
    info1_li1: 'معلومات الملف الشخصي للحساب',
    info1_li2: 'بيانات المصادقة المرتبطة بالحساب',
    info1_li3: 'سجلات البطولات والدوريات التي أنشأها المستخدم',
    info1_li4: 'جميع تفضيلات وإعدادات التطبيق المرتبطة بالمستخدم',
    info2_title: 'الاحتفاظ بالبيانات',
    info2_desc: 'يتم حذف جميع البيانات الشخصية نهائيًا بعد حذف الحساب. لا يتم الاحتفاظ بأي بيانات شخصية. لا نحتفظ بأي نسخة من بياناتك؛ لا توجد فترة احتفاظ بعد الحذف.',
    info3_title: 'توقيت الحذف',
    info3_desc: 'تتم معالجة الحذف فورًا بعد التأكيد الناجح. يتم إزالة حسابك وبياناتك بمجرد إكمال النموذج.',
    label_email: 'البريد الإلكتروني',
    label_password: 'كلمة المرور',
    label_confirm: 'عبارة التأكيد',
    placeholder_email: 'you@example.com',
    placeholder_confirm: 'I confirm',
    hint: 'يجب كتابة <strong>I confirm</strong> بالضبط (بالإنجليزية، بدون تمييز بين الأحرف الكبيرة والصغيرة). هذا الإجراء نهائي ولا يمكن التراجع عنه.',
    btn_delete: 'حذف حسابي',
    btn_loading: 'يرجى الانتظار…',
    msg_invalid: 'البريد الإلكتروني أو كلمة المرور غير صالحة. يرجى المحاولة مرة أخرى.',
    msg_wrong_phrase: 'عبارة التأكيد غير صحيحة. يرجى كتابة: I confirm بالضبط',
    msg_api_error: 'لم نتمكن من إكمال حذف الحساب في الوقت الحالي. يرجى المحاولة مرة أخرى لاحقًا.',
    msg_success: 'تم إكمال طلب حذف حسابك بنجاح.\nالبيانات المحذوفة: الملف الشخصي للحساب، وبيانات المصادقة، وجميع سجلات البطولات/الدوريات المرتبطة بهذا الحساب.',
    footer_brand: 'صانع الدوريات والبطولات',
    footer_by: 'بواسطة',
    footer_support: 'الدعم:',
  },
  hi: {
    _title: 'खाता हटाएं – लीग और टूर्नामेंट मेकर',
    _description: 'अपना लीग और टूर्नामेंट मेकर खाता और सभी संबंधित डेटा स्थायी रूप से हटाएं।',
    nav_back: '← टूर्नामेंट मेकर',
    nav_privacy: 'गोपनीयता नीति',
    nav_delete: 'खाता हटाएं',
    title: 'खाता हटाएं',
    subtitle: 'अपने ईमेल और पासवर्ड से साइन इन करें, फिर अपना खाता और सभी संबंधित डेटा स्थायी रूप से हटाने के लिए पुष्टि वाक्यांश टाइप करें।',
    info1_title: 'क्या हटाया जाएगा',
    info1_li1: 'खाता प्रोफ़ाइल जानकारी',
    info1_li2: 'खाते से जुड़े प्रमाणीकरण क्रेडेंशियल',
    info1_li3: 'उपयोगकर्ता द्वारा बनाए गए टूर्नामेंट और लीग रिकॉर्ड',
    info1_li4: 'उपयोगकर्ता से संबंधित सभी ऐप प्राथमिकताएं और सेटिंग्स',
    info2_title: 'डेटा प्रतिधारण',
    info2_desc: 'खाता हटाने के बाद सभी व्यक्तिगत डेटा स्थायी रूप से हटा दिया जाता है। कोई व्यक्तिगत डेटा नहीं रखा जाता। हम आपके डेटा की कोई प्रति नहीं रखते हैं; हटाने के बाद कोई प्रतिधारण अवधि नहीं है।',
    info3_title: 'हटाने का समय',
    info3_desc: 'सफल पुष्टि के तुरंत बाद हटाने की प्रक्रिया शुरू हो जाती है। फ़ॉर्म पूरा करते ही आपका खाता और डेटा हटा दिया जाता है।',
    label_email: 'ईमेल',
    label_password: 'पासवर्ड',
    label_confirm: 'पुष्टि वाक्यांश',
    placeholder_email: 'you@example.com',
    placeholder_confirm: 'I confirm',
    hint: 'आपको ठीक <strong>I confirm</strong> टाइप करना होगा (अंग्रेज़ी में, केस-असंवेदनशील)। यह क्रिया स्थायी है और इसे पूर्ववत नहीं किया जा सकता।',
    btn_delete: 'मेरा खाता हटाएं',
    btn_loading: 'कृपया प्रतीक्षा करें…',
    msg_invalid: 'अमान्य ईमेल या पासवर्ड। कृपया पुनः प्रयास करें।',
    msg_wrong_phrase: 'पुष्टि वाक्यांश गलत है। कृपया ठीक यह टाइप करें: I confirm',
    msg_api_error: 'इस समय खाता हटाना पूरा नहीं किया जा सका। कृपया बाद में पुनः प्रयास करें।',
    msg_success: 'आपका खाता हटाने का अनुरोध सफलतापूर्वक पूरा हो गया।\nहटाया गया डेटा: खाता प्रोफ़ाइल, प्रमाणीकरण क्रेडेंशियल और इस खाते से जुड़े सभी टूर्नामेंट/लीग रिकॉर्ड।',
    footer_brand: 'लीग और टूर्नामेंट मेकर',
    footer_by: 'द्वारा',
    footer_support: 'सहायता:',
  },
  id: {
    _title: 'Hapus Akun – Pembuat Liga & Turnamen',
    _description: 'Hapus akun Pembuat Liga & Turnamen Anda dan semua data terkait secara permanen.',
    nav_back: '← Pembuat Turnamen',
    nav_privacy: 'Kebijakan Privasi',
    nav_delete: 'Hapus Akun',
    title: 'Hapus Akun',
    subtitle: 'Masuk dengan email dan kata sandi Anda, lalu ketik frasa konfirmasi untuk menghapus akun Anda dan semua data terkait secara permanen.',
    info1_title: 'Yang akan dihapus',
    info1_li1: 'Informasi profil akun',
    info1_li2: 'Kredensial autentikasi yang terkait dengan akun',
    info1_li3: 'Catatan turnamen dan liga yang dibuat pengguna',
    info1_li4: 'Semua preferensi dan pengaturan aplikasi terkait pengguna',
    info2_title: 'Penyimpanan data',
    info2_desc: 'Semua data pribadi dihapus secara permanen setelah penghapusan akun. Tidak ada data pribadi yang disimpan. Kami tidak menyimpan salinan data Anda; tidak ada periode penyimpanan setelah penghapusan.',
    info3_title: 'Waktu penghapusan',
    info3_desc: 'Penghapusan diproses segera setelah konfirmasi berhasil. Akun dan data Anda dihapus segera setelah Anda menyelesaikan formulir.',
    label_email: 'Email',
    label_password: 'Kata sandi',
    label_confirm: 'Frasa konfirmasi',
    placeholder_email: 'anda@contoh.com',
    placeholder_confirm: 'I confirm',
    hint: 'Anda harus mengetik persis <strong>I confirm</strong> (dalam bahasa Inggris, tidak peka huruf besar/kecil). Tindakan ini bersifat permanen dan tidak dapat dibatalkan.',
    btn_delete: 'Hapus akun saya',
    btn_loading: 'Harap tunggu…',
    msg_invalid: 'Email atau kata sandi tidak valid. Silakan coba lagi.',
    msg_wrong_phrase: 'Frasa konfirmasi salah. Silakan ketik persis: I confirm',
    msg_api_error: 'Kami tidak dapat menyelesaikan penghapusan akun saat ini. Silakan coba lagi nanti.',
    msg_success: 'Permintaan penghapusan akun Anda berhasil diselesaikan.\nData yang dihapus: profil akun, kredensial autentikasi, dan semua catatan turnamen/liga yang terkait dengan akun ini.',
    footer_brand: 'Pembuat Liga & Turnamen',
    footer_by: 'oleh',
    footer_support: 'Dukungan:',
  },
  pl: {
    _title: 'Usuń konto – Kreator Lig i Turniejów',
    _description: 'Trwale usuń swoje konto Kreatora Lig i Turniejów oraz wszystkie powiązane dane.',
    nav_back: '← Kreator Turniejów',
    nav_privacy: 'Polityka prywatności',
    nav_delete: 'Usuń konto',
    title: 'Usuń konto',
    subtitle: 'Zaloguj się za pomocą adresu e-mail i hasła, a następnie wpisz frazę potwierdzającą, aby trwale usunąć swoje konto i wszystkie powiązane dane.',
    info1_title: 'Co zostanie usunięte',
    info1_li1: 'Informacje o profilu konta',
    info1_li2: 'Dane uwierzytelniające powiązane z kontem',
    info1_li3: 'Rekordy turniejów i lig utworzone przez użytkownika',
    info1_li4: 'Wszystkie preferencje i ustawienia aplikacji powiązane z użytkownikiem',
    info2_title: 'Przechowywanie danych',
    info2_desc: 'Wszystkie dane osobowe są trwale usuwane po usunięciu konta. Żadne dane osobowe nie są przechowywane. Nie przechowujemy żadnej kopii Twoich danych; nie ma okresu przechowywania po usunięciu.',
    info3_title: 'Czas usunięcia',
    info3_desc: 'Usunięcie jest przetwarzane natychmiast po pomyślnym potwierdzeniu. Twoje konto i dane są usuwane, jak tylko wypełnisz formularz.',
    label_email: 'E-mail',
    label_password: 'Hasło',
    label_confirm: 'Fraza potwierdzająca',
    placeholder_email: 'ty@przyklad.pl',
    placeholder_confirm: 'I confirm',
    hint: 'Musisz wpisać dokładnie <strong>I confirm</strong> (po angielsku, bez rozróżniania wielkości liter). Ta czynność jest trwała i nie można jej cofnąć.',
    btn_delete: 'Usuń moje konto',
    btn_loading: 'Proszę czekać…',
    msg_invalid: 'Nieprawidłowy adres e-mail lub hasło. Spróbuj ponownie.',
    msg_wrong_phrase: 'Fraza potwierdzająca jest nieprawidłowa. Wpisz dokładnie: I confirm',
    msg_api_error: 'Nie udało się teraz ukończyć usuwania konta. Spróbuj ponownie później.',
    msg_success: 'Twoje żądanie usunięcia konta zostało pomyślnie zrealizowane.\nUsunięte dane: profil konta, dane uwierzytelniające oraz wszystkie rekordy turniejów/lig powiązane z tym kontem.',
    footer_brand: 'Kreator Lig i Turniejów',
    footer_by: 'autor',
    footer_support: 'Wsparcie:',
  },
};
