var SHOT_TRANSLATIONS = (function () {
  var en = {
    _title: 'Shot Çarkı - Party Wheel Game with Dares',
    _description: 'Shot Çarkı is a fun party wheel game for 2–12 players. Spin the wheel, get a dare by difficulty, complete it for points or take a shot. Highest score wins!',
    nav_home: '← Sogepps Home',
    nav_levels: 'Difficulties',
    nav_how: 'How To Play',
    nav_privacy: 'Privacy Policy',
    hero_title: 'Shot Çarkı<br />Spin, Dare &amp; Score',
    hero_lead: 'Shot Çarkı is a party wheel game for friends. Add 2–12 players, spin the animated wheel, get a task by difficulty level — complete it for points or take a shot. Highest score wins!',
    tag_1: '2–12 players',
    tag_2: 'Weighted wheel',
    tag_3: '5 difficulty levels',
    tag_4: 'Live scoreboard',
    levels_title: 'Difficulty Levels',
    levels_desc: 'Harder tasks are rarer but worth more points.',
    lv_1_t: 'Very Easy',
    lv_1_d: '30% chance · 10 points — verbal & simple',
    lv_2_t: 'Easy',
    lv_2_d: '25% chance · 20 points — light challenges',
    lv_3_t: 'Normal',
    lv_3_d: '20% chance · 30 points — medium tasks',
    lv_4_t: 'Hard',
    lv_4_d: '15% chance · 40 points — courage & action',
    lv_5_t: 'Very Hard',
    lv_5_d: '10% chance · 50 points — tough dares',
    how_title: 'How To Play Shot Çarkı',
    how_desc: 'Simple rules for a loud game night.',
    how_1_t: '1) Add players',
    how_1_d: 'Choose 2–12 players and enter everyone’s name.',
    how_2_t: '2) Spin the wheel',
    how_2_d: 'On your turn, tap Spin. The wheel lands on a difficulty.',
    how_3_t: '3) Do it or take a shot',
    how_3_d: 'Complete the task and tap Done for points — or take a shot and skip the points.',
    how_4_t: '4) Climb the scoreboard',
    how_4_d: 'Track scores and shots anytime. Most points wins!',
    feat_title: 'Why Shot Çarkı?',
    feat_desc: 'Built for parties, dorm nights and friend hangouts.',
    f_1_t: 'Animated SVG Wheel',
    f_1_d: 'Smooth 5-second spin with real weighted odds.',
    f_2_t: 'Huge Task Bank',
    f_2_d: '~30 tasks per level — from verbal fun to physical dares.',
    f_3_t: 'Score & Shots',
    f_3_d: 'Live scoreboard with points and shot count.',
    f_4_t: 'No Account Needed',
    f_4_d: 'Jump straight into the game without signing up.',
    warn_title: 'Play Responsibly',
    warn_desc: 'This is an entertainment app. Don’t force anyone. Don’t overdo alcohol. Players under 18 should not drink.',
    cta_title: 'Start The Party With Shot Çarkı',
    cta_desc: 'Shot Çarkı is the newest party game from the Sogepps family.',
    btn_home: 'Back to Sogepps home',
    btn_contact: 'Contact',
    footer_privacy: 'Privacy Policy'
  };

  var tr = {
    _title: 'Shot Çarkı - Görevli Parti Çarkı Oyunu',
    _description: 'Shot Çarkı; 2–12 kişilik eğlenceli parti çarkı. Çarkı çevir, zorluğa göre görev al, yapıp puan kazan veya shot at. En çok puanı toplayan kazanır!',
    nav_home: '← Sogepps ana sayfa',
    nav_levels: 'Zorluklar',
    nav_how: 'Nasıl Oynanır',
    nav_privacy: 'Gizlilik Politikası',
    hero_title: 'Shot Çarkı<br />Çevir, Görev Yap, Puan Topla',
    hero_lead: 'Shot Çarkı; arkadaşlarla oynanan çark tabanlı parti oyunudur. 2–12 oyuncu ekleyin, animasyonlu çarkı çevirin, zorluk seviyesine göre görev alın — tamamlayıp puan kazanın veya shot atın. En yüksek puan kazanır!',
    tag_1: '2–12 oyuncu',
    tag_2: 'Ağırlıklı çark',
    tag_3: '5 zorluk seviyesi',
    tag_4: 'Canlı skor tablosu',
    levels_title: 'Zorluk Seviyeleri',
    levels_desc: 'Zor görevler daha nadir gelir ama daha fazla puan verir.',
    lv_1_t: 'Çok Kolay',
    lv_1_d: '%30 şans · 10 puan — sözel ve basit',
    lv_2_t: 'Kolay',
    lv_2_d: '%25 şans · 20 puan — hafif görevler',
    lv_3_t: 'Normal',
    lv_3_d: '%20 şans · 30 puan — orta seviye',
    lv_4_t: 'Zor',
    lv_4_d: '%15 şans · 40 puan — cesaret ve aksiyon',
    lv_5_t: 'Çok Zor',
    lv_5_d: '%10 şans · 50 puan — zorlu cesaret görevleri',
    how_title: 'Shot Çarkı Nasıl Oynanır?',
    how_desc: 'Gürültülü oyun geceleri için basit kurallar.',
    how_1_t: '1) Oyuncuları ekle',
    how_1_d: '2–12 kişi seçin ve herkesin ismini girin.',
    how_2_t: '2) Çarkı çevir',
    how_2_d: 'Sırası gelen oyuncu Çarkı Çevir’e basar. Çark bir zorlukta durur.',
    how_3_t: '3) Yap veya shot at',
    how_3_d: 'Görevi yapıp Yaptım dersen puan kazanırsın. Yapamazsan Shot Attım — puan yok.',
    how_4_t: '4) Skorda yüksel',
    how_4_d: 'Puanları ve shot sayısını istediğin an takip et. En çok puan kazanan kazanır!',
    feat_title: 'Neden Shot Çarkı?',
    feat_desc: 'Partiler, yurt geceleri ve arkadaş buluşmaları için tasarlandı.',
    f_1_t: 'Animasyonlu SVG Çark',
    f_1_d: '5 saniyelik akıcı dönüş ve gerçek ağırlıklı olasılık.',
    f_2_t: 'Bol Görev Bankası',
    f_2_d: 'Her seviyede ~30 görev — sözelden fiziksel cesarete.',
    f_3_t: 'Skor ve Shot Sayacı',
    f_3_d: 'Puan + atılan shot sayısıyla canlı skor tablosu.',
    f_4_t: 'Hesap Gerekmez',
    f_4_d: 'Kayıt olmadan doğrudan oyuna başla.',
    warn_title: 'Sorumlu Oyna',
    warn_desc: 'Bu bir eğlence uygulamasıdır. Kimseyi zorlama. Alkolü abartma. 18 yaş altı içki içmemeli.',
    cta_title: 'Shot Çarkı ile Eğlenceyi Başlat',
    cta_desc: 'Shot Çarkı, Sogepps uygulama ailesinin yeni parti oyunudur.',
    btn_home: 'Sogepps ana sayfaya dön',
    btn_contact: 'İletişim',
    footer_privacy: 'Gizlilik Politikası'
  };

  var translations = {};
  var shared = ['de', 'fr', 'es', 'it', 'pt', 'nl', 'ru', 'ja', 'ko', 'ar', 'hi', 'id', 'pl'];
  translations.en = en;
  translations.tr = tr;
  shared.forEach(function (code) { translations[code] = en; });
  return translations;
})();
